-- Tests xmake.lua
-- Test helper: test_proj(name, source, callable)
--   callable: optional config callback for extra deps/includes/defines

local kimix_enable_tests = has_config("kimix_enable_tests")
if not kimix_enable_tests then
    return
end

local function test_proj(name, source, callable)
    target(name)
        set_kind("binary")
        add_files(source)
        add_includedirs("./")
        add_deps("kimix-core")
        _config_project({batch_size = 8})
        if callable then
            callable()
        end
    target_end()
end

-- unit/core tests
test_proj("test_kimix_core", "unit/core/test_kimix_core.cpp")

test_proj("test_stl_allocator", "unit/core/test_stl_allocator.cpp")
test_proj("test_stl_string", "unit/core/test_stl_string.cpp")
test_proj("test_stl_vector", "unit/core/test_stl_vector.cpp")
test_proj("test_stl_hash", "unit/core/test_stl_hash.cpp")
test_proj("test_basic_types", "unit/core/test_basic_types.cpp")
test_proj("test_pool", "unit/core/test_pool.cpp")
test_proj("test_first_fit", "unit/core/test_first_fit.cpp")
test_proj("test_string_scratch", "unit/core/test_string_scratch.cpp")
test_proj("test_binary_file_stream", "unit/core/test_binary_file_stream.cpp")
test_proj("test_clock", "unit/core/test_clock.cpp")
test_proj("test_format", "unit/core/test_format.cpp")
test_proj("test_logging", "unit/core/test_logging.cpp", function()
    add_deps("spdlog")
end)
test_proj("test_fiber", "unit/core/test_fiber.cpp")

-- unit/ext
test_proj("test_reproc", "unit/ext/test_reproc.cpp", function()
    add_deps("reproc")
end)
test_proj("test_spdlog", "unit/ext/test_spdlog.cpp", function()
    add_deps("spdlog")
end)
test_proj("test_yyjson", "unit/ext/test_yyjson.cpp", function()
    add_deps("kimix-yyjson")
    add_deps("mimalloc")
end)
test_proj("test_xxhash", "unit/ext/test_xxhash.cpp", function()
    add_deps("kimix-xxhash")
end)
test_proj("test_pybind11", "unit/ext/test_pybind11.cpp", function()
    add_deps("kimix-pybind11")
end)

-- unit/native (kimix runtime scaffold)
test_proj("test_native_module", "unit/native/test_module.cpp", function()
    add_deps("runtime")
end)

-- unit/native (kimix runtime text/stream kernels — plans 001/002/003)
test_proj("test_native_token_count", "unit/native/test_token_count.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_sanitize", "unit/native/test_sanitize.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_ansi", "unit/native/test_ansi.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_line_processor", "unit/native/test_line_processor.cpp", function()
    add_deps("runtime")
end)

-- unit/native (kimix runtime index kernels — plan 004)
test_proj("test_native_ngram_tokenizer", "unit/native/test_ngram_tokenizer.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_inverted_index", "unit/native/test_inverted_index.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_history_index", "unit/native/test_history_index.cpp", function()
    add_deps("runtime")
end)

-- unit/native (kimix runtime search kernels — plan 005)
test_proj("test_native_bm25", "unit/native/test_bm25.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_distance", "unit/native/test_distance.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_fuzzy", "unit/native/test_fuzzy.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_hash_kernels", "unit/native/test_hash_kernels.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_rerank", "unit/native/test_rerank.cpp", function()
    add_deps("runtime")
end)

-- unit/native (kimix runtime codec kernels - plans 007/008/009/010)
test_proj("test_native_wire_envelope", "unit/native/test_wire_envelope.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_merge_buffer", "unit/native/test_merge_buffer.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_frame_writer", "unit/native/test_frame_writer.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_recv_buffer", "unit/native/test_recv_buffer.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_sse", "unit/native/test_sse.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_event_bus", "unit/native/test_event_bus.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_id_gen", "unit/native/test_id_gen.cpp", function()
    add_deps("runtime")
end)
test_proj("test_native_incremental_lexer", "unit/native/test_incremental_lexer.cpp", function()
    add_deps("runtime")
end)

  -- unit/native (kimix runtime parse kernels - plans 011/012)
  test_proj("test_native_comment_scanner", "unit/native/test_comment_scanner.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_shell_scanner", "unit/native/test_shell_scanner.cpp", function()
      add_deps("runtime")
      -- the deep-nesting abort test exercises 1024 levels of scanner
      -- recursion (the reference's _MAX_NESTING_DEPTH); give it a big stack
      add_ldflags("/STACK:16777216")
  end)

  -- unit/native (kimix runtime tools kernels - plan 013)
  test_proj("test_native_line_hash", "unit/native/test_line_hash.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_find_str", "unit/native/test_find_str.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_grep_scan", "unit/native/test_grep_scan.cpp", function()
      add_deps("runtime")
  end)

  -- unit/native (kimix runtime soul kernels - plans 014/015/016)
  test_proj("test_native_payload_builder", "unit/native/test_payload_builder.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_normalize_tool_call_ids", "unit/native/test_normalize_tool_call_ids.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_prune_scanner", "unit/native/test_prune_scanner.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_reminder_stripper", "unit/native/test_reminder_stripper.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_prompt_builder", "unit/native/test_prompt_builder.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_json_store", "unit/native/test_json_store.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_schema_ops", "unit/native/test_schema_ops.cpp", function()
      add_deps("runtime")
  end)
  test_proj("test_native_export_builder", "unit/native/test_export_builder.cpp", function()
      add_deps("runtime")
  end)
