// Test for the shared built-in tool kernels (builtin_tools/tool_types.h +
// utf8_util.h). This test covers:
// - truncate_line: no-op short lines, code-point counting for non-ASCII, the
//   "… [+K chars]" marker, and the marker-doesn't-fit fallback
// - fold_lines: pass-through, head+tail split with the omission marker,
//   over-budget head clamp
// - dedup_lines: run collapsing with the "(N repeats)" suffix, min_repeats
//   floor, saved count accounting
// - join_with_byte_limit: byte budget cut (the line that crosses the budget is
//   KEPT - see the Python reference note in the block below)
// - utf8_util: code point counts, prefix slicing on boundaries, strict
//   validation with CPython DecoderError wording
// - GOLDEN REPLAY against the reference implementation (the vectors in
//   tool_types_goldens.inc, generated by scripts/gen_tool_types_goldens.py by
//   running kimi-agent's kimi_cli.tools.file.output_utils / grep_local /
//   CPython itself):
//   * 19k CPython `bytes.decode("utf-8")` error vectors (reason + start offset)
//     plus 715 valid-text vectors (code point count, per-code-point byte
//     offsets, decoded code points)
//   * output_utils.truncate_line / fold_lines / dedup_lines
//   * grep_local._join_with_byte_limit (cross-checked against glob.py's
//     identical inline loop by the generator)
//   * output_utils.parse_rtk_rg_output (the grep kernel is reachable from this
//     test because the shared helper has no Python binding)
#include "ut/ut.hpp"

#include "builtin_tools/grep_tool.h"
#include "builtin_tools/tool_types.h"
#include "builtin_tools/utf8_util.h"

#include <string>
#include <vector>

using namespace boost::ut;
using namespace boost::ut::literals;
using namespace kimix::builtin_tools;

namespace {

kimix::vector<kimix::string> to_vec(std::vector<std::string> in) {
    kimix::vector<kimix::string> out;
    out.reserve(in.size());
    for (auto &s : in) {
        out.emplace_back(s.data(), s.size());
    }
    return out;
}

std::vector<std::string> from_vec(kimix::span<const kimix::string> in) {
    std::vector<std::string> out;
    out.reserve(in.size());
    for (const auto &s : in) {
        out.emplace_back(s.data(), s.size());
    }
    return out;
}

// ── golden readers (see the encoding notes in the generated .inc) ───────────

// Decode a line-list field: lines joined with '\x1f' plus a trailing '\x1f'.
kimix::vector<kimix::string> tt_lines(kimix::string_view enc) {
    kimix::vector<kimix::string> out;
    size_t start = 0;
    for (size_t i = 0; i < enc.size(); i++) {
        if (enc[i] != '\x1f') {
            continue;
        }
        out.emplace_back(enc.substr(start, i - start));
        start = i + 1;
    }
    return out;
}

// Re-encode a line list the same way (for readable mismatch messages).
std::string tt_enc(kimix::span<const kimix::string> lines) {
    std::string out;
    for (const kimix::string &l : lines) {
        out.append(l.data(), l.size());
        out.push_back('\x1f');
    }
    return out;
}

// Split a "1,2,3" field into numbers.
std::vector<size_t> tt_uints(kimix::string_view csv) {
    std::vector<size_t> out;
    size_t i = 0;
    while (i < csv.size()) {
        size_t value = 0;
        while (i < csv.size() && csv[i] >= '0' && csv[i] <= '9') {
            value = value * 10u + static_cast<size_t>(csv[i] - '0');
            i++;
        }
        out.push_back(value);
        while (i < csv.size() && csv[i] != ',') {
            i++;
        }
        if (i < csv.size()) {
            i++;
        }
    }
    return out;
}

std::string tt_str(kimix::string_view sv) { return std::string(sv.data(), sv.size()); }

bool tt_eq(kimix::string_view a, kimix::string_view b) {
    return a.size() == b.size() && std::string_view(a.data(), a.size()) ==
                                       std::string_view(b.data(), b.size());
}

// The JSON escaping used by the generated `folded_json` field.
std::string tt_json_str(kimix::string_view s) {
    static const char *k_hex = "0123456789abcdef";
    std::string out;
    for (char ch : s) {
        const unsigned char b = static_cast<unsigned char>(ch);
        if (b == '"') {
            out += "\\\"";
        } else if (b == '\\') {
            out += "\\\\";
        } else if (b < 0x20) {
            out += "\\u00";
            out.push_back(k_hex[(b >> 4) & 0x0F]);
            out.push_back(k_hex[b & 0x0F]);
        } else {
            out.push_back(ch);
        }
    }
    return out;
}

std::string tt_folded_json(const grep::rtk_meta &meta) {
    std::string out = "[";
    for (size_t i = 0; i < meta.folded_files.size(); i++) {
        if (i != 0u) {
            out += ",";
        }
        const grep::rtk_folded_file &f = meta.folded_files[i];
        out += "{\"path\":\"" + tt_json_str(f.path) + "\",\"count\":" +
               std::to_string(f.count);
        out += ",\"log\":";
        out += f.has_log ? "\"" + tt_json_str(f.log) + "\"" : std::string("null");
        out += ",\"start_line\":";
        out += f.start_line.has_value() ? std::to_string(*f.start_line)
                                        : std::string("null");
        out += "}";
    }
    out += "]";
    return out;
}

// Only the utf8 / line-stream half of the golden file (the ToolParams vectors
// belong to test_tool.cpp).
#define KIMIX_TT_GOLDEN_NO_JSON_VECTORS 1
#include "tool_types_goldens.inc"

} // namespace

int main(int argc, char *argv[]) {
    boost::ut::detail::cfg::parse_arg_with_fallback(
        argc, const_cast<const char **>(argv));

    "utf8_helpers"_test = [] {
        expect(eq(utf8_code_point_count("hello"), size_t(5)));
        // "héllo→" = 6 code points, 9 bytes
        expect(eq(utf8_code_point_count("h\xC3\xA9llo\xE2\x86\x92"), size_t(6)));
        expect(eq(utf8_byte_offset_of_code_point("h\xC3\xA9llo", 2), size_t(3)));
        expect(eq(utf8_byte_offset_of_code_point("abc", 99), size_t(3)));
        // floor boundary never splits a sequence
        expect(eq(utf8_floor_boundary("\xE2\x86\x92x", 1), size_t(0)));
        expect(eq(utf8_floor_boundary("\xE2\x86\x92x", 2), size_t(0)));
        expect(eq(utf8_floor_boundary("\xE2\x86\x92x", 3), size_t(3)));
        expect(is_ascii("abc")) << "ascii fast path";
        expect(!is_ascii("\xC3\xA9")) << "non-ascii";

        // strict validation
        size_t off = 12345;
        kimix::string reason;
        expect(utf8_strict_error("valid \xE2\x86\x92 utf-8", off, reason))
            << "valid text accepted";
        expect(!utf8_strict_error("\x80", off, reason)) << "lone continuation";
        expect(eq(off, size_t(0))) << "python reports the lead index";
        expect(eq(reason, kimix::string("invalid start byte")));
        expect(!utf8_strict_error("\xC3", off, reason)) << "truncated sequence";
        expect(eq(reason, kimix::string("unexpected end of data")));
        expect(!utf8_strict_error("\xED\xA0\x80", off, reason)) << "surrogate";
        expect(eq(reason, kimix::string("invalid continuation byte")))
            << "CPython wording for an over-range first continuation";
        expect(!utf8_strict_error("ab\xE0\x80\x80", off, reason));
        expect(eq(off, size_t(2))) << "offset points at the lead byte";
        expect(!utf8_strict_error("\xC0\x80", off, reason)) << "overlong";
        expect(eq(reason, kimix::string("invalid start byte")));
        expect(!utf8_strict_error("\xF5\x80\x80\x80", off, reason)) << "above U+10FFFF";
        expect(eq(reason, kimix::string("invalid start byte")));
        expect(utf8_strict_error("", off, reason)) << "empty is valid";

        // Truncated sequence whose *available* continuation bytes are already
        // invalid: CPython reports "invalid continuation byte", not "unexpected
        // end of data" (it only reports the latter when every available
        // continuation byte was legal).  Regression vectors:
        //   b"\xe0\x00"     -> start 0, invalid continuation byte
        //   b"\xed\xa0"     -> start 0, invalid continuation byte (CESU surrogate)
        //   b"\xf0\x90\x41" -> start 0, invalid continuation byte
        // NB: these carry embedded NULs, so the length must be explicit - a
        // bare const char* literal would be truncated by strlen (that is the
        // trap the golden vectors avoid with tt_cstr / sizeof(lit) - 1).
        expect(!utf8_strict_error(tt_cstr("\xE0\x00"), off, reason));
        expect(eq(off, size_t(0)));
        expect(eq(reason, kimix::string("invalid continuation byte")));
        expect(!utf8_strict_error(tt_cstr("\xED\xA0"), off, reason));
        expect(eq(reason, kimix::string("invalid continuation byte")));
        expect(!utf8_strict_error("\xF0\x90\x41", off, reason));
        expect(eq(reason, kimix::string("invalid continuation byte")));
        expect(!utf8_strict_error(tt_cstr("\xE0\xA0"), off, reason))
            << "a legal prefix stays 'unexpected end of data'";
        expect(eq(reason, kimix::string("unexpected end of data")));
    };

    "utf8_invalid_input_policy"_test = [] {
        // CPython has no code-point count for malformed bytes, so this is the
        // native policy, locked here so a future change is deliberate:
        // decode_code_point() rejects an invalid lead, a truncated sequence, a
        // non-continuation byte and a surrogate (> U+10FFFF too) and advances
        // ONE byte each time; it deliberately does not re-check the overlong
        // ranges: the E0/F0 lead bounds already pin the shortest form for every
        // sequence whose continuation bytes are 0x80.., EXCEPT that
        // b"\xe0\x80\x80" (overlong NUL) is accepted as one code point.
        // None of this is reachable with valid UTF-8 input, which is what every
        // caller passes - the goldens above cover that path.
        expect(eq(utf8_code_point_count("\xE0\x80\x80"), size_t(1)))
            << "overlong NUL: one code point";
        expect(eq(utf8_code_point_count("\xE1\x80"), size_t(2)))
            << "truncated lead + stray byte";
        expect(eq(utf8_code_point_count("\xED\xA0\x80"), size_t(3)))
            << "a CESU surrogate is rejected";
        expect(eq(utf8_code_point_count("\xF4\x90\x80\x80"), size_t(4)))
            << "above U+10FFFF is rejected";
        // The sibling implementation in src/runtime/common/utf8.cpp chooses the
        // opposite policy (overlong rejected, surrogate accepted) - the two are
        // never mixed, and neither is fed invalid bytes by its callers.
        size_t off = 0;
        kimix::string reason;
        expect(!utf8_strict_error("\xE0\x80\x80", off, reason))
            << "strict validation still rejects the overlong form";
    };

    "truncate_line_basic"_test = [] {
        kimix::string out;
        truncate_line("short", 10, out);
        expect(eq(out, kimix::string("short"))) << "under budget unchanged";
        truncate_line("short", 5, out);
        expect(eq(out, kimix::string("short"))) << "exactly at budget unchanged";

        kimix::string long_line(60, 'a');
        truncate_line(long_line, 20, out);
        // 20 code points total: 9 'a' + "… [+40 chars]" (13 cp)
        expect(eq(utf8_code_point_count(out), size_t(20))) << "fits the budget";
        expect(out.starts_with("aaaaaaa")) << "head preserved (20 - 13 marker cp)";
        expect(out.ends_with(" chars]")) << "marker appended";
        expect(out.find("[+40 chars]") != kimix::string::npos)
            << "removed count reported";
    };

    "truncate_line_edge_cases"_test = [] {
        kimix::string out;
        // marker too large to fit: raw cut, no marker
        truncate_line(kimix::string(30, 'x'), 5, out);
        expect(eq(utf8_code_point_count(out), size_t(5)));
        expect(out.find("chars]") == kimix::string::npos) << "no marker when it would not fit";

        // non-ASCII: counting is in code points, slicing on a byte boundary
        kimix::string u8;
        for (int i = 0; i < 10; i++) {
            u8 += "\xE2\x86\x92"; // U+2192, 3 bytes
        }
        truncate_line(u8, 6, out);
        expect(eq(utf8_code_point_count(out), size_t(6))) << "6 code points out";
        expect(eq(out.size(), size_t(18))) << "12-cp marker does not fit in 6, raw cut";
        expect(utf8_validate(out)) << "never splits a sequence";
    };

    "fold_lines_head_tail"_test = [] {
        auto lines = to_vec({"1", "2", "3", "4", "5", "6", "7", "8", "9", "10"});
        kimix::vector<kimix::string> out;
        size_t omitted = 999;
        fold_lines(lines, 4, 2, 2, out, omitted);
        expect(eq(out.size(), size_t(5))) << "head 2 + marker + tail 2";
        expect(eq(out[0], kimix::string("1")));
      expect(eq(out[1], kimix::string("2")));
      expect(eq(out[2], kimix::string("\xE2\x80\xA6 (6 lines omitted) \xE2\x80\xA6")));
      expect(eq(out[3], kimix::string("9")));
      expect(eq(out[4], kimix::string("10")));
        expect(eq(omitted, size_t(6)));

        // under budget: unchanged, zero omitted
        fold_lines(lines, 100, 50, 50, out, omitted);
        expect(eq(out.size(), size_t(10)));
        expect(eq(omitted, size_t(0)));

        // max_lines == 0 means unlimited
        fold_lines(lines, 0, 0, 0, out, omitted);
        expect(eq(out.size(), size_t(10))) << "0 == unlimited";

        // over-budget head clamps the tail to zero
        fold_lines(lines, 4, 4, 4, out, omitted);
        expect(eq(out.size(), size_t(5))) << "head 4 + marker, tail clamped to 0";
        expect(eq(out[3], kimix::string("4"))) << "caller head is kept";
        expect(eq(omitted, size_t(6)));
    };

    "dedup_lines_runs"_test = [] {
        auto lines =
            to_vec({"a", "b", "b", "b", "b", "c", "d", "d", "e"});
        kimix::vector<kimix::string> out;
        size_t saved = 999;
        dedup_lines(lines, 3, out, saved);
        expect(eq(out.size(), size_t(6))) << "b-run collapsed, d-run kept";
        expect(eq(out[0], kimix::string("a")));
        expect(eq(out[1], kimix::string("b  (3 repeats)")));
        expect(eq(saved, size_t(3))) << "4 b lines save 3";
        expect(eq(out[2], kimix::string("c")));
        expect(eq(out[3], kimix::string("d"))) << "run below min_repeats untouched";
        expect(eq(out[5], kimix::string("e")));

        // min_repeats floors at 2
        dedup_lines(lines, 1, out, saved);
        expect(eq(out[1], kimix::string("b  (3 repeats)")));
        expect(eq(out[3], kimix::string("d  (1 repeats)")))
            << "matches Python: 2-line run collapses at min_repeats=2";

        // single line / empty input pass through
        auto one = to_vec({"solo"});
        dedup_lines(one, 3, out, saved);
        expect(eq(out.size(), size_t(1)));
        expect(eq(saved, size_t(0)));
    };

    // join_with_byte_limit is a port of grep_local._join_with_byte_limit
    // (grep_local.py 618-632; glob.py 631-637 runs the same loop inline):
    // the line that *reaches* the cap is KEPT and collection stops there, and
    // `truncated` is set even when that line happened to be the last one.
    // (The previous native body stopped *before* the crossing line, which no
    // Python caller does; the golden vector
    //   {["aaaa","bbbb","cccc","dddd"], max_bytes=10} -> "aaaa\nbbbb\ncccc"
    // pins the difference.)
    "join_with_byte_limit"_test = [] {
        auto lines = to_vec({"aaaa", "bbbb", "cccc", "dddd"});
        kimix::string out;
        bool truncated = false;
        size_t omitted = 0;
        join_with_byte_limit(lines, 1024, out, truncated, omitted);
        expect(eq(out, kimix::string("aaaa\nbbbb\ncccc\ndddd")));
        expect(!truncated) << "inside budget";
        expect(eq(omitted, size_t(0)));

        join_with_byte_limit(lines, 10, out, truncated, omitted);
        expect(eq(out, kimix::string("aaaa\nbbbb\ncccc")))
            << "the crossing line is kept, like Python";
        expect(truncated) << "budget reached";
        expect(eq(omitted, size_t(1))) << "one line left over";

        join_with_byte_limit(lines, 9, out, truncated, omitted);
        expect(eq(out, kimix::string("aaaa\nbbbb"))) << "exactly at the cap -> stop";

        // empty input
        kimix::vector<kimix::string> none;
        join_with_byte_limit(none, 10, out, truncated, omitted);
        expect(out.empty()) << "nothing to join";
        expect(!truncated);
        expect(eq(omitted, size_t(0)));
    };

    "named_value_and_status_defaults"_test = [] {
        tool_error e;
        expect(!e.failed()) << "default status is ok";
        e.status = tool_status::external_library;
        expect(e.failed());
        expect(e.message.empty());

        byte_range r{4, 10};
        expect(eq(r.size(), uint64_t(6)));

        line_range lr;
        expect(!lr.end_line.has_value()) << "open ended by default";
        expect(lr == line_range{1, {}}) << "value equality";
        expect(named_value{"k", "v"}.name == "k");
    };

    // ------------------------------------------------------------------
    // Golden replay (reverse-engineered from kimi-agent / CPython)
    // ------------------------------------------------------------------

    "utf8_decode_error_golden"_test = [] {
        size_t failures = 0;
        for (const tt_utf8_error_golden &g : k_tt_utf8_error_golden) {
            const kimix::string_view data(g.data);
            size_t off = size_t(-1);
            kimix::string reason;
            const bool ok = utf8_strict_error(data, off, reason);
            if (ok != g.ok || (!g.ok && (off != g.offset || !tt_eq(reason, g.reason)))) {
                failures++;
                if (failures <= 8) {
                    expect(false) << "utf8 mismatch for bytes " << tt_str(data)
                                  << ": native ok=" << ok << " off=" << off
                                  << " reason=" << tt_str(reason)
                                  << " | cpython ok=" << g.ok << " off=" << g.offset
                                  << " reason=" << tt_str(g.reason);
                }
            }
        }
        expect(eq(failures, size_t(0)))
            << "CPython bytes.decode('utf-8') parity over "
            << sizeof(k_tt_utf8_error_golden) / sizeof(k_tt_utf8_error_golden[0])
            << " vectors";
        expect(sizeof(k_tt_utf8_error_golden) / sizeof(k_tt_utf8_error_golden[0]) > 19000u)
            << "the generated corpus must stay large (a shrinking corpus would "
               "silently turn this test into a smoke test)";
    };

    "utf8_valid_text_golden"_test = [] {
        size_t failures = 0;
        for (const tt_utf8_valid_golden &g : k_tt_utf8_valid_golden) {
            const kimix::string_view text(g.text);
            bool bad = utf8_code_point_count(text) != g.code_points;
            bad = bad || is_ascii(text) != (text.size() == g.code_points);
            const std::vector<size_t> want_offsets = tt_uints(kimix::string_view(g.offsets_csv));
            for (size_t k = 0; k < want_offsets.size(); k++) {
                if (utf8_byte_offset_of_code_point(text, k) != want_offsets[k]) {
                    bad = true;
                }
            }
            // decode_code_point must yield exactly the reference code points.
            const std::vector<size_t> want_cps = tt_uints(kimix::string_view(g.cps_csv));
            std::vector<size_t> got_cps;
            const char *it = text.data();
            const char *end = text.data() + text.size();
            while (it < end) {
                got_cps.push_back(decode_code_point(it, end));
            }
            if (got_cps != want_cps) {
                bad = true;
            }
            // every code point boundary must be a valid floor boundary, and a
            // probe anywhere inside a sequence must land on its start - the
            // reference is the boundary set derived from CPython's own slicing.
            for (size_t off : want_offsets) {
                if (utf8_floor_boundary(text, off) != off) {
                    bad = true;
                }
            }
            for (size_t probe = 0; probe <= text.size(); probe++) {
                size_t want_floor = 0;
                for (size_t off : want_offsets) {
                    if (off <= probe) {
                        want_floor = off;
                    }
                }
                if (utf8_floor_boundary(text, probe) != want_floor) {
                    bad = true;
                }
            }
            if (bad) {
                failures++;
                if (failures <= 8) {
                    expect(false) << "valid-utf8 mismatch for " << tt_str(text);
                }
            }
        }
        expect(eq(failures, size_t(0)))
            << "len(str)/ord()/byte-offset parity over "
            << sizeof(k_tt_utf8_valid_golden) / sizeof(k_tt_utf8_valid_golden[0])
            << " vectors";
        expect(sizeof(k_tt_utf8_valid_golden) / sizeof(k_tt_utf8_valid_golden[0]) > 700u);
    };

    "truncate_line_golden"_test = [] {
        size_t failures = 0;
        for (const tt_truncate_golden &g : k_tt_truncate_golden) {
            kimix::string out;
            truncate_line(kimix::string_view(g.text), g.max_len, out);
            if (!tt_eq(out, g.want)) {
                failures++;
                if (failures <= 8) {
                    expect(false) << "truncate_line(" << tt_str(g.text) << ", " << g.max_len
                                  << ") = " << tt_str(out) << " want " << tt_str(g.want);
                }
            }
        }
        expect(eq(failures, size_t(0))) << "output_utils.truncate_line parity";
        expect(sizeof(k_tt_truncate_golden) / sizeof(k_tt_truncate_golden[0]) >= 55u);
    };

    "fold_lines_golden"_test = [] {
        size_t failures = 0;
        for (const tt_fold_golden &g : k_tt_fold_golden) {
            const kimix::vector<kimix::string> lines = tt_lines(g.lines);
            kimix::vector<kimix::string> out;
            size_t omitted = 0;
            fold_lines(lines, g.max_lines, g.head, g.tail, out, omitted);
            if (tt_enc(out) != tt_str(g.want) || omitted != g.omitted) {
                failures++;
                if (failures <= 8) {
                    expect(false) << "fold_lines(" << tt_str(g.lines) << ", " << g.max_lines
                                  << ", " << g.head << ", " << g.tail << ") = "
                                  << tt_enc(out) << " [" << omitted << "] want "
                                  << tt_str(g.want) << " [" << g.omitted << "]";
                }
            }
        }
        expect(eq(failures, size_t(0))) << "output_utils.fold_lines parity";
        expect(sizeof(k_tt_fold_golden) / sizeof(k_tt_fold_golden[0]) >= 690u);
    };

    "dedup_lines_golden"_test = [] {
        size_t failures = 0;
        for (const tt_dedup_golden &g : k_tt_dedup_golden) {
            const kimix::vector<kimix::string> lines = tt_lines(g.lines);
            kimix::vector<kimix::string> out;
            size_t saved = 0;
            dedup_lines(lines, g.min_repeats, out, saved);
            if (tt_enc(out) != tt_str(g.want) || saved != g.saved) {
                failures++;
                if (failures <= 8) {
                    expect(false) << "dedup_lines(" << tt_str(g.lines) << ", " << g.min_repeats
                                  << ") = " << tt_enc(out) << " [" << saved << "] want "
                                  << tt_str(g.want) << " [" << g.saved << "]";
                }
            }
        }
        expect(eq(failures, size_t(0))) << "output_utils.dedup_lines parity";
        expect(sizeof(k_tt_dedup_golden) / sizeof(k_tt_dedup_golden[0]) >= 100u);
    };

    "join_with_byte_limit_golden"_test = [] {
        size_t failures = 0;
        for (const tt_join_golden &g : k_tt_join_golden) {
            const kimix::vector<kimix::string> lines = tt_lines(g.lines);
            kimix::string out;
            bool truncated = false;
            size_t omitted = 0;
            join_with_byte_limit(lines, g.max_bytes, out, truncated, omitted);
            if (!tt_eq(out, g.want) || truncated != g.truncated || omitted != g.omitted) {
                failures++;
                if (failures <= 8) {
                    expect(false) << "join_with_byte_limit(" << tt_str(g.lines) << ", "
                                  << g.max_bytes << ") = " << tt_str(out) << " ["
                                  << truncated << ", " << omitted << "] want " << tt_str(g.want)
                                  << " [" << g.truncated << ", " << g.omitted << "]";
                }
            }
        }
        expect(eq(failures, size_t(0)))
            << "grep_local._join_with_byte_limit parity ("
            << sizeof(k_tt_join_golden) / sizeof(k_tt_join_golden[0]) << " vectors)";
        expect(sizeof(k_tt_join_golden) / sizeof(k_tt_join_golden[0]) >= 216u);
    };

    "parse_rtk_rg_output_golden"_test = [] {
        size_t failures = 0;
        for (const tt_rtk_golden &g : k_tt_rtk_golden) {
            const kimix::vector<kimix::string> lines = tt_lines(g.lines);
            kimix::vector<kimix::string> cleaned;
            grep::rtk_meta meta;
            const tool_status status = grep::parse_rtk_rg_output(lines, cleaned, meta);
            const char *status_name =
                (status == tool_status::ok) ? "ok"
                : (status == tool_status::unsupported) ? "unsupported" : "other";
            bool bad = !tt_eq(status_name, g.status);
            if (status == tool_status::ok) {
                bad = bad || tt_enc(cleaned) != tt_str(g.cleaned);
                bad = bad || meta.total_matches.has_value() != g.has_total_matches ||
                      (g.has_total_matches && *meta.total_matches != g.total_matches);
                bad = bad || meta.total_files.has_value() != g.has_total_files ||
                      (g.has_total_files && *meta.total_files != g.total_files);
                bad = bad || tt_folded_json(meta) != tt_str(g.folded_json);
                bad = bad || meta.skipped_files.has_value() != g.has_skipped_files ||
                      (g.has_skipped_files && *meta.skipped_files != g.skipped_files);
                bad = bad || meta.has_skipped_log != g.has_skipped_log ||
                      (g.has_skipped_log && !tt_eq(meta.skipped_log, g.skipped_log));
            }
            if (bad) {
                failures++;
                if (failures <= 8) {
                    expect(false) << "parse_rtk_rg_output(" << tt_str(g.lines)
                                  << ") status=" << status_name << " cleaned=" << tt_enc(cleaned)
                                  << " folded=" << tt_folded_json(meta)
                                  << " | want status=" << tt_str(g.status)
                                  << " cleaned=" << tt_str(g.cleaned)
                                  << " folded=" << tt_str(g.folded_json);
                }
            }
        }
        expect(eq(failures, size_t(0))) << "output_utils.parse_rtk_rg_output parity";
        expect(sizeof(k_tt_rtk_golden) / sizeof(k_tt_rtk_golden[0]) >= 33u);
    };
}
