// Test for builtin_tools/plan_tool.h (namespace kimix::builtin_tools::plan).
//
// Two layers:
//
// 1. Kernel unit tests with hand-written expectations (parameters, the render
//    engines, the char window, the edit chain, the message builders, the Tool
//    wrappers).
// 2. Golden replay (tests/unit/builtin_tools/plan_goldens.inc), regenerated by
//    `python scripts/gen_plan_goldens.py` from the REAL Python implementation
//    in the kimi-agent checkout (src/kimix/tools/note/__init__.py), driven
//    through `CallableTool2.call` exactly like the agent toolset:
//      * kPlanMeta            - LLM-facing description + pydantic parameter
//                               schema (compared structurally)
//      * kPlanParamGoldens    - which argument sets pydantic lets through
//      * kForwardGoldens / kTailGoldens - ReadPlan._read_forward/_read_tail
//                               (byte-exact output + message, plus the
//                               output byte/line counts for the corpora whose
//                               rendered output is too large to embed)
//      * kPlanWindowGoldens   - `output[char_offset:max_char]`
//      * kPlanToolGoldens     - end-to-end replay over real files: status,
//                               message, output, brief, the on-disk bytes and
//                               the ReadPlan render bookkeeping
//      * kPlanOsErrorGoldens  - OS-level failures (CPython's errno text is
//                               platform specific; the platform-independent
//                               parts are pinned)
//      * kPlanGateGoldens     - `_enable_plan` == False raises SkipThisTool
//
// All test logic lives in main() scope; no file-scope static registrations.
#include "ut/ut.hpp"

#include <core/kimix_core.h>

#include "builtin_tools/plan_tool.h"
#include "builtin_tools/read_tool.h"
#include "builtin_tools/tool_registry.h"

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

using namespace boost::ut;
using namespace boost::ut::literals;
using namespace kimix::builtin_tools;
using namespace kimix::builtin_tools::plan;

namespace {

kimix::string kix(std::string_view sv) {
    return kimix::string(sv.data(), sv.size());
}

// Split text into the universal-newline line list read::split_lines produces.
kimix::vector<kimix::string> lines_of(std::string_view text) {
    return read::split_lines(kix(text));
}

// Every expectation that compares a produced string with a literal does so as
// `expect(sv_of(x) == std::string("..."))`.
//
// NOT `expect(x == kix("..."))`: Boost.UT's expression handling is not
// dependable when an operand is a `kimix::string` (custom allocator) temporary.
// The committed version of this file asserted the false "Did you mean" message
// one space short (`kix("...\n candidate")` while the port and the reference
// produce two spaces plus a two-space suggestion) and the committed suite
// reported the assertion as PASSING (45 tests / 177 asserts, 0 failures), while
// the identical statement fails as soon as a single printf precedes it and
// fails reliably once the operands are std::string. std::string comparisons are
// reflected correctly by ut (a failure prints both operands), so all 51
// string expectations were converted to that form.
std::string sv_of(const kimix::string &s) {
    return std::string(s.data(), s.size());
}

// Golden vectors generated from the Python reference implementation
// (C:/dev/kimi-agent/src/kimix/tools/note/__init__.py) by
// scripts/gen_plan_goldens.py.
#include "plan_goldens.inc"

// ---------------------------------------------------------------------------
// golden replay helpers
// ---------------------------------------------------------------------------

// Expand a `text` golden field: a value starting with \002 is the recipe
// "\002R<us>COUNT<us>UNIT" (UNIT repeated COUNT times); otherwise the literal
// bytes are `len` long (a bare const char* would stop at an embedded NUL).
std::string expand_text(const char *spec, long long len) {
    std::string s(spec);
    if (s.size() < 2 || static_cast<unsigned char>(s[0]) != 0x02) {
        return std::string(spec, static_cast<size_t>(len));
    }
    expect(s[1] == 'R') << "unknown text recipe";
    const size_t first = s.find('\x1f', 2);
    const size_t second = s.find('\x1f', first + 1);
    expect(first != std::string::npos && second != std::string::npos)
        << "malformed text recipe";
    const long long count = std::atoll(s.substr(first + 1, second - first - 1).c_str());
    const std::string unit = s.substr(second + 1);
    std::string out;
    out.reserve(unit.size() * static_cast<size_t>(count));
    for (long long i = 0; i < count; ++i) {
        out += unit;
    }
    return out;
}

std::string replace_all(std::string text, const std::string &from,
                        const std::string &to) {
    size_t pos = 0;
    while (!from.empty() && (pos = text.find(from, pos)) != std::string::npos) {
        text.replace(pos, from.size(), to);
        pos += to.size();
    }
    return text;
}

// Rendered lines: newline count plus a trailing partial line (the count the
// generator records -- deliberately NOT Python str.splitlines(), which also
// breaks on \x0b / \x0c / U+0085).
long long line_count(const std::string &text) {
    if (text.empty()) {
        return 0;
    }
    long long n = 0;
    for (const char c : text) {
        if (c == '\n') {
            ++n;
        }
    }
    return text.back() == '\n' ? n : n + 1;
}

// CPython writes plan files through text-mode file objects, which translates
// every LF to CRLF on Windows; the port writes the UTF-8 bytes verbatim (see
// reports/plan.md). Identity elsewhere.
std::string translate_lf(const std::string &text) {
#ifdef _WIN32
    return replace_all(text, "\n", "\r\n");
#else
    return text;
#endif
}

bool read_bytes(const std::filesystem::path &p, std::string &out) {
    std::error_code ec;
    if (!std::filesystem::exists(p, ec) || !std::filesystem::is_regular_file(p, ec)) {
        return false;
    }
    std::ifstream in(p, std::ios::binary);
    if (!in) {
        return false;
    }
    out.assign(std::istreambuf_iterator<char>(in), std::istreambuf_iterator<char>());
    return true;
}

bool write_bytes(const std::filesystem::path &p, const std::string &data) {
    std::error_code ec;
    std::filesystem::create_directories(p.parent_path(), ec);
    std::ofstream out(p, std::ios::binary | std::ios::trunc);
    if (!out) {
        return false;
    }
    if (!data.empty()) {
        out.write(data.data(), static_cast<std::streamsize>(data.size()));
    }
    return static_cast<bool>(out);
}

// Structural JSON equality (key order insensitive), used to compare the
// registered tool schema with the pydantic one.
bool json_equal(const ValueElement &a, const ValueElement &b) {
    if (a.is_null() || b.is_null()) {
        return a.is_null() && b.is_null();
    }
    if (a.is_object() || b.is_object()) {
        if (!a.is_object() || !b.is_object()) {
            return false;
        }
        const ToolParams *oa = a.as_object();
        const ToolParams *ob = b.as_object();
        if (!oa || !ob || oa->values.size() != ob->values.size()) {
            return false;
        }
        for (const auto &entry : oa->values) {
            const ValueElement *rhs = ob->get_exact(entry.first);
            if (rhs == nullptr || !json_equal(entry.second, *rhs)) {
                return false;
            }
        }
        return true;
    }
    if (a.is_array() || b.is_array()) {
        if (!a.is_array() || !b.is_array() || a.as_array().size() != b.as_array().size()) {
            return false;
        }
        for (size_t i = 0; i < a.as_array().size(); ++i) {
            if (!json_equal(a.as_array()[i], b.as_array()[i])) {
                return false;
            }
        }
        return true;
    }
    if (a.is_string() || b.is_string()) {
        return a.is_string() && b.is_string() && a.as_string() == b.as_string();
    }
    if (a.is_bool() || b.is_bool()) {
        return a.is_bool() && b.is_bool() && a.as_bool() == b.as_bool();
    }
    const double na = a.is_real() ? a.as_real()
                                  : (a.is_int() ? static_cast<double>(a.as_int())
                                                : static_cast<double>(a.as_uint()));
    const double nb = b.is_real() ? b.as_real()
                                  : (b.is_int() ? static_cast<double>(b.as_int())
                                                : static_cast<double>(b.as_uint()));
    return na == nb;
}

bool parse_json(const std::string &text, ToolParams &out) {
    return out.deserialize(kimix::span<char const>(text.data(), text.size()), nullptr);
}

// The C++ result envelope of one tool invocation.
struct decoded_result {
    std::string status;
    std::string message;
    std::string output;
    std::string brief;
    int64_t start_line = -2;
    int64_t total_lines = -2;
    int max_lines_reached = -1;
    int max_bytes_reached = -1;
    std::string truncated;
};

decoded_result decode_result(const kimix::vector<char> &raw) {
    decoded_result out;
    ToolParams parsed;
    const std::string text(raw.data(), raw.size());
    if (!parse_json(text, parsed)) {
        expect(false) << "result is not valid JSON: " << text;
        return out;
    }
    const auto str_of = [&parsed](const char *key) -> std::string {
        const ValueElement *el = parsed.get_exact(key);
        return (el != nullptr && el->is_string()) ? sv_of(el->as_string())
                                                  : std::string();
    };
    out.status = str_of("status");
    out.message = str_of("message");
    out.output = str_of("output");
    out.brief = str_of("brief");
    if (const ValueElement *el = parsed.get_exact("start_line");
        el != nullptr && el->is_int()) {
        out.start_line = el->as_int();
    }
    if (const ValueElement *el = parsed.get_exact("total_lines");
        el != nullptr && el->is_int()) {
        out.total_lines = el->as_int();
    }
    if (const ValueElement *el = parsed.get_exact("max_lines_reached");
        el != nullptr && el->is_bool()) {
        out.max_lines_reached = el->as_bool() ? 1 : 0;
    }
    if (const ValueElement *el = parsed.get_exact("max_bytes_reached");
        el != nullptr && el->is_bool()) {
        out.max_bytes_reached = el->as_bool() ? 1 : 0;
    }
    if (const ValueElement *el = parsed.get_exact("truncated_line_numbers");
        el != nullptr && el->is_array()) {
        for (const ValueElement &item : el->as_array()) {
            if (!out.truncated.empty()) {
                out.truncated += ' ';
            }
            out.truncated += std::to_string(item.is_int() ? item.as_int() : -1);
        }
    }
    return out;
}

kimix::unique_ptr<Tool> create_tool(const char *name, Session *session) {
    const ToolMeta *meta = ToolRegistry::instance().find(name);
    if (meta == nullptr) {
        return nullptr;
    }
    return meta->factory(session);
}

// The platform separator conversion applied to a golden relative path.
std::filesystem::path native_path(const std::string &root,
                                  const std::string &rel) {
    std::filesystem::path p(root);
    std::string cur;
    for (size_t i = 0; i <= rel.size(); ++i) {
        const char c = (i == rel.size()) ? '/' : rel[i];
        if (c == '/') {
            if (!cur.empty()) {
                p /= cur;
                cur.clear();
            }
        } else {
            cur += c;
        }
    }
    return p;
}

} // namespace

int main(int argc, char *argv[]) {
    boost::ut::detail::cfg::parse_arg_with_fallback(
        argc, const_cast<const char **>(argv));

    // -----------------------------------------------------------------------
    // parse_write_params
    // -----------------------------------------------------------------------
    "write_params_defaults"_test = [] {
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("# Plan"));
        write_plan_params out;
        const tool_error err = parse_write_params(&params, out);
        expect(!err.failed());
        expect(sv_of(out.content) == std::string("# Plan"));
        expect(sv_of(out.mode) == std::string("overwrite"));
    };

    "write_params_text_alias"_test = [] {
        ToolParams params;
        params.values["text"] = ValueElement::make_string(kix("aliased"));
        write_plan_params out;
        expect(!parse_write_params(&params, out).failed());
        expect(sv_of(out.content) == std::string("aliased"));
    };

    "write_params_alias_wins_over_field_name"_test = [] {
        // pydantic (populate_by_name) resolves the declared alias first, so a
        // call that carries BOTH spellings uses `text` (the schema name).
        // Reference evidence: Python WritePlanParams.model_validate(
        //   {"content": "canonical", "text": "alias"}).content == "alias"
        // (pinned end to end by the "write_aliases_both" golden).
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("canonical"));
        params.values["text"] = ValueElement::make_string(kix("alias"));
        write_plan_params out;
        expect(!parse_write_params(&params, out).failed());
        expect(sv_of(out.content) == std::string("alias"));
    };

    "write_params_append_mode"_test = [] {
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("x"));
        params.values["mode"] = ValueElement::make_string(kix("append"));
        write_plan_params out;
        expect(!parse_write_params(&params, out).failed());
        expect(sv_of(out.mode) == std::string("append"));
    };

    "write_params_bad_mode"_test = [] {
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("x"));
        params.values["mode"] = ValueElement::make_string(kix("sideways"));
        write_plan_params out;
        const tool_error err = parse_write_params(&params, out);
        expect(err.failed());
        expect(err.status == tool_status::invalid_input);
        expect(sv_of(err.message).find("'overwrite' or 'append'") !=
               std::string::npos);
    };

    "write_params_missing_content"_test = [] {
        ToolParams params;
        write_plan_params out;
        const tool_error err = parse_write_params(&params, out);
        expect(err.failed());
        expect(sv_of(err.message) == std::string("missing required field: content"));
    };

    "write_params_explicit_null_mode_is_rejected"_test = [] {
        // pydantic: Literal["overwrite","append"] does not accept null, so
        // {"mode": null} never reaches the tool body (goldens: write_mode_null).
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("x"));
        params.values["mode"] = ValueElement::make_null();
        write_plan_params out;
        const tool_error err = parse_write_params(&params, out);
        expect(err.failed());
        expect(err.status == tool_status::invalid_input);
    };

    // -----------------------------------------------------------------------
    // parse_read_params
    // -----------------------------------------------------------------------
    "read_params_defaults"_test = [] {
        read_plan_params out;
        expect(!parse_read_params(nullptr, out).failed());
        expect(out.line_offset == 1_i);
        expect(out.n_lines == k_max_lines);
        expect(out.max_char == 65536_i);
        expect(out.char_offset == 0_i);
    };

    "read_params_explicit_null_is_rejected"_test = [] {
        // pydantic rejects a null for a typed field with a default; the port
        // must not silently fall back to the default (goldens:
        // read_line_offset_null).
        for (const char *name : {"line_offset", "n_lines", "max_char",
                                 "char_offset"}) {
            ToolParams params;
            params.values[kimix::string_view(name)] = ValueElement::make_null();
            read_plan_params out;
            const tool_error err = parse_read_params(&params, out);
            expect(err.failed()) << name << " accepted a JSON null";
            expect(err.status == tool_status::invalid_input) << name;
        }
    };

    "read_params_zero_line_offset"_test = [] {
        ToolParams params;
        params.values["line_offset"] = ValueElement::make_int(0);
        read_plan_params out;
        const tool_error err = parse_read_params(&params, out);
        expect(err.failed());
        expect(sv_of(err.message) == std::string("line_offset cannot be 0; use 1 for the first line or -1 "
                   "for the last line"));
    };

    "read_params_too_negative"_test = [] {
        ToolParams params;
        params.values["line_offset"] = ValueElement::make_int(-1001);
        read_plan_params out;
        const tool_error err = parse_read_params(&params, out);
        expect(err.failed());
        expect(sv_of(err.message).find(
                   "line_offset cannot be less than -1000.") == 0);
        expect(sv_of(err.message).find(
                   "Use a positive line_offset with the total line count to "
                   "read from a specific position.") != std::string::npos);
    };

    "read_params_boundary_negative_ok"_test = [] {
        ToolParams params;
        params.values["line_offset"] = ValueElement::make_int(-1000);
        read_plan_params out;
        expect(!parse_read_params(&params, out).failed());
        expect(out.line_offset == -1000_i);
    };

    "read_params_n_lines_ge_1"_test = [] {
        ToolParams params;
        params.values["n_lines"] = ValueElement::make_int(0);
        read_plan_params out;
        const tool_error err = parse_read_params(&params, out);
        expect(err.failed());
        expect(sv_of(err.message) == std::string("n_lines must be greater than or equal to 1"));
    };

    // -----------------------------------------------------------------------
    // render_forward
    // -----------------------------------------------------------------------
    "render_forward_numbers_and_reports_total"_test = [] {
        const kimix::vector<kimix::string> lines = lines_of("a\nb\nc\n");
        const plan_render r =
            render_forward(kimix::span<const kimix::string>(lines), 1, 1000);
        expect(sv_of(r.output) == std::string("     1\ta\n     2\tb\n     3\tc\n"));
        expect(sv_of(r.message) == std::string("3 lines read from plan starting from line 1. Total lines "
                   "in file: 3."));
        expect(r.start_line == 1_i);
        expect(r.total_lines == 3_i);
        expect(!r.max_lines_reached);
        expect(!r.max_bytes_reached);
        expect(r.truncated_line_numbers.empty());
    };

    "render_forward_offset_skips_leading_lines"_test = [] {
        const kimix::vector<kimix::string> lines = lines_of("a\nb\nc\n");
        const plan_render r =
            render_forward(kimix::span<const kimix::string>(lines), 2, 1000);
        expect(sv_of(r.output) == std::string("     2\tb\n     3\tc\n"));
        expect(sv_of(r.message) == std::string("2 lines read from plan starting from line 2. Total lines "
                   "in file: 3."));
        expect(r.start_line == 2_i);
    };

    "render_forward_line_budget_hides_total"_test = [] {
        const kimix::vector<kimix::string> lines = lines_of("a\nb\nc\n");
        const plan_render r =
            render_forward(kimix::span<const kimix::string>(lines), 1, 2);
        expect(sv_of(r.output) == std::string("     1\ta\n     2\tb\n"));
        // target_lines (2) < MAX_LINES so max_lines_reached stays false, and
        // the file was NOT fully scanned so no "Total lines in file".
        expect(!r.max_lines_reached);
        expect(sv_of(r.message).find("Total lines in file") ==
               std::string::npos);
        expect(sv_of(r.message) == std::string("2 lines read from plan starting from line 1."));
    };

    "render_forward_max_lines_reached_at_cap"_test = [] {
        // n_lines >= MAX_LINES and at least MAX_LINES rendered lines.
        kimix::string text;
        for (int i = 0; i < 1001; ++i) {
            text += "line\n";
        }
        const kimix::vector<kimix::string> lines = lines_of(sv_of(text));
        const plan_render r =
            render_forward(kimix::span<const kimix::string>(lines), 1, 1000);
        expect(r.max_lines_reached);
        expect(sv_of(r.message).find("Max 1000 lines reached.") !=
               std::string::npos);
        expect(sv_of(r.message).find("1000 lines read from plan starting from "
                                     "line 1.") == 0);
    };

    "render_forward_empty_window"_test = [] {
        const kimix::vector<kimix::string> lines = lines_of("a\nb\n");
        const plan_render r =
            render_forward(kimix::span<const kimix::string>(lines), 9, 1000);
        expect(r.output.empty());
        expect(sv_of(r.message).find("No lines read from plan.") == 0);
        expect(r.start_line == 9_i);
    };

    "render_forward_truncation_marker"_test = [] {
        kimix::string long_line(2100, 'x');
        const kimix::string text = long_line + "\nshort\n";
        const kimix::vector<kimix::string> lines = lines_of(sv_of(text));
        const plan_render r =
            render_forward(kimix::span<const kimix::string>(lines), 1, 1000);
        expect(r.truncated_line_numbers.size() == 1u);
        expect(r.truncated_line_numbers[0] == 1_i);
        expect(sv_of(r.message).find("Lines [1] were truncated.") !=
               std::string::npos);
        // The truncated body keeps the trailing newline and ends with "...".
        expect(sv_of(r.output).find("...\n") != std::string::npos);
    };

    // -----------------------------------------------------------------------
    // render_tail
    // -----------------------------------------------------------------------
    "render_tail_keeps_last_n_lines"_test = [] {
        const kimix::vector<kimix::string> lines = lines_of("a\nb\nc\n");
        const plan_render r =
            render_tail(kimix::span<const kimix::string>(lines), -2, 1000);
        expect(sv_of(r.output) == std::string("     2\tb\n     3\tc\n"));
        expect(sv_of(r.message) == std::string("2 lines read from plan starting from line 2. Total lines "
                   "in file: 3."));
        expect(r.start_line == 2_i);
        expect(r.total_lines == 3_i);
    };

    "render_tail_line_limit_caps_from_window_head"_test = [] {
        const kimix::vector<kimix::string> lines = lines_of("a\nb\nc\nd\n");
        // tail window = last 3 lines (b,c,d), then n_lines=2 keeps (b,c).
        const plan_render r =
            render_tail(kimix::span<const kimix::string>(lines), -3, 2);
        expect(sv_of(r.output) == std::string("     2\tb\n     3\tc\n"));
        expect(r.start_line == 2_i);
    };

    "render_tail_empty_file"_test = [] {
        const kimix::vector<kimix::string> lines = lines_of("");
        const plan_render r =
            render_tail(kimix::span<const kimix::string>(lines), -5, 1000);
        expect(r.output.empty());
        expect(sv_of(r.message).find("No lines read from plan.") == 0);
        expect(sv_of(r.message).find("Total lines in file: 0.") !=
               std::string::npos);
        expect(r.start_line == 1_i); // total_lines + 1
    };

    "render_tail_byte_budget_keeps_newest"_test = [] {
        // 60 lines of 1900 chars each - below MAX_LINE_LENGTH so no per-line
        // truncation happens - total 60 * 1901 = 114060 bytes > MAX_BYTES.
        // The reverse scan keeps the newest lines that fit: 53 * 1901 = 100753
        // <= 102400 < 54 * 1901 = 102654, so lines 8..60 survive.
        kimix::string text;
        for (int i = 0; i < 60; ++i) {
            text += kimix::string(1900, 'x');
            text += "\n";
        }
        const kimix::vector<kimix::string> lines = lines_of(sv_of(text));
        const plan_render r =
            render_tail(kimix::span<const kimix::string>(lines), -60, 1000);
        expect(r.max_bytes_reached);
        expect(sv_of(r.message).find("Max 102400 bytes reached.") !=
               std::string::npos);
        expect(r.truncated_line_numbers.empty());
        // The newest line (60) survives, the oldest (1) does not, and the
        // window restarts at the first surviving line.
        expect(sv_of(r.output).find("    60\t") != std::string::npos);
        expect(sv_of(r.output).find("     1\t") == std::string::npos);
        expect(r.start_line == 8_i);
        expect(sv_of(r.message).find(
                   "53 lines read from plan starting from line 8.") == 0);
        expect(sv_of(r.message).find("Total lines in file: 60.") !=
               std::string::npos);
    };

    // -----------------------------------------------------------------------
    // apply_char_window
    // -----------------------------------------------------------------------
    "char_window_uses_max_char_as_slice_end"_test = [] {
        // Python: "abcdef"[2:4] == "cd" (NOT 4 characters starting at 2).
        expect(sv_of(apply_char_window("abcdef", 2, 4)) == std::string("cd"));
        expect(sv_of(apply_char_window("abcdef", 0, 3)) == std::string("abc"));
        expect(sv_of(apply_char_window("abcdef", 4, 2)) == std::string(""));
        expect(sv_of(apply_char_window("abcdef", 10, 20)) == std::string(""));
        expect(sv_of(apply_char_window("abcdef", 0, 100)) == std::string("abcdef"));
    };

    "char_window_counts_code_points"_test = [] {
        // "héllo" is 5 code points / 6 bytes.
        expect(sv_of(apply_char_window("h\xc3\xa9llo", 0, 2)) == std::string("h\xc3\xa9"));
        expect(sv_of(apply_char_window("h\xc3\xa9llo", 1, 3)) == std::string("\xc3\xa9l"));
    };

    "format_line_list_python_repr"_test = [] {
        const kimix::vector<int64_t> single = {3};
        expect(sv_of(format_line_list(kimix::span<const int64_t>(single))) == std::string("[3]"));
        const kimix::vector<int64_t> many = {3, 7, 11};
        expect(sv_of(format_line_list(kimix::span<const int64_t>(many))) == std::string("[3, 7, 11]"));
        expect(sv_of(format_line_list(kimix::span<const int64_t>())) == std::string("[]"));
    };

    // -----------------------------------------------------------------------
    // apply_plan_edit
    // -----------------------------------------------------------------------
    "plan_edit_noop_on_empty_old"_test = [] {
        plan_edit_item item;
        item.old_text = "";
        item.new_text = "x";
        const plan_edit_result r = apply_plan_edit("content", item);
        expect(sv_of(r.content) == std::string("content"));
        expect(r.replacements == 0u);
        expect(!r.suggestion.has_value());
    };

    "plan_edit_noop_when_identical"_test = [] {
        plan_edit_item item;
        item.old_text = "same";
        item.new_text = "same";
        const plan_edit_result r = apply_plan_edit("same text", item);
        expect(r.replacements == 0u);
        expect(sv_of(r.content) == std::string("same text"));
    };

    "plan_edit_single_replacement"_test = [] {
        plan_edit_item item;
        item.old_text = "hello";
        item.new_text = "goodbye";
        const plan_edit_result r = apply_plan_edit("hello hello", item);
        expect(r.replacements == 1u);
        expect(sv_of(r.content) == std::string("goodbye hello"));
    };

    "plan_edit_replace_all_counts"_test = [] {
        plan_edit_item item;
        item.old_text = "a";
        item.new_text = "b";
        item.replace_all = true;
        const plan_edit_result r = apply_plan_edit("a a a\n", item);
        expect(r.replacements == 3u);
        expect(sv_of(r.content) == std::string("b b b\n"));
    };

    "plan_edit_replace_all_no_hit_keeps_content"_test = [] {
        plan_edit_item item;
        item.old_text = "zzz";
        item.new_text = "b";
        item.replace_all = true;
        const plan_edit_result r = apply_plan_edit("a a a\n", item);
        expect(r.replacements == 0u);
        expect(sv_of(r.content) == std::string("a a a\n"));
    };

    "plan_edit_normalizes_crlf"_test = [] {
        plan_edit_item item;
        item.old_text = "line1\nline2";
        item.new_text = "replaced";
        const plan_edit_result r = apply_plan_edit("line1\r\nline2\r\n", item);
        expect(r.replacements == 1u);
        expect(sv_of(r.content) == std::string("replaced\n"));
    };

    "plan_edit_strip_match"_test = [] {
        plan_edit_item item;
        item.old_text = "indented";
        item.new_text = "flush";
        // Not a literal hit (leading whitespace differs) but the stripped
        // form is found inside the line.
        const plan_edit_result r = apply_plan_edit(" indented text\n", item);
        expect(r.replacements == 1u);
        expect(sv_of(r.content).find("flush") != std::string::npos);
    };

    "plan_edit_fuzzy_success_has_no_suggestion"_test = [] {
        plan_edit_item item;
        // "hellp world" vs the "hello world" line is ~91% similar (> 75%
        // cutoff) and is NOT a literal hit, so this exercises the fuzzy branch.
        item.old_text = "hello world";
        item.new_text = "HI";
        const plan_edit_result r = apply_plan_edit("hellp world\n", item);
        expect(r.replacements == 1u);
        expect(sv_of(r.content) == std::string("HI\n"));
        // This is where EditPlan differs from the file edit tool: a
        // successful fuzzy match reports NO suggestion.
        expect(!r.suggestion.has_value());
    };

    "plan_edits_aggregate_counts_and_last_suggestion"_test = [] {
        plan_edit_item first;
        first.old_text = "alpha";
        first.new_text = "ALPHA";
        plan_edit_item second;
        second.old_text = "beta";
        second.new_text = "BETA";
        const kimix::vector<plan_edit_item> edits = {first, second};
        const edit_plan_result r = apply_plan_edits(
            "alpha and beta\n", kimix::span<const plan_edit_item>(edits));
        expect(r.total_replacements == 2u);
        expect(r.changed);
        expect(sv_of(r.content) == std::string("ALPHA and BETA\n"));
        expect(!r.last_suggestion.has_value());
    };

    "plan_edits_no_change_reports_suggestion"_test = [] {
        plan_edit_item item;
        item.old_text = "completely unrelated needle text";
        item.new_text = "x";
        const kimix::vector<plan_edit_item> edits = {item};
        const edit_plan_result r = apply_plan_edits(
            "alpha\nbeta\ngamma\n",
            kimix::span<const plan_edit_item>(edits));
        expect(!r.changed);
        expect(r.total_replacements == 0u);
    };

    // -----------------------------------------------------------------------
    // Message builders
    // -----------------------------------------------------------------------
    "message_builders_are_verbatim"_test = [] {
        expect(sv_of(no_plan_path_message("WritePlan")) == std::string("WritePlan tool invalid: no plan_writing_path set."));
        expect(sv_of(no_plan_path_message("ReadPlan")) == std::string("ReadPlan tool invalid: no plan_writing_path set."));
        expect(sv_of(no_plan_path_message("EditPlan")) == std::string("EditPlan tool invalid: no plan_writing_path set."));
        expect(sv_of(plan_missing_message("p.md")) == std::string("Plan file `p.md` does not exist."));
        expect(sv_of(plan_not_a_file_message("dir")) == std::string("`dir` is not a file."));
        expect(sv_of(plan_written_message("overwrite", "p.md")) == std::string("Plan written to p.md"));
        expect(sv_of(plan_written_message("append", "p.md")) == std::string("Plan appended to p.md"));
        expect(sv_of(no_replacements_message("")) == std::string("No replacements were made. The old string was not found "
                   "in the plan file."));
        // The suggestion is concatenated after the two-space indent
        // (`msg += f"\n\nDid you mean:\n  {last_suggestion}"`), so a suggestion
        // that already starts with whitespace keeps it.
        expect(sv_of(no_replacements_message("candidate")) == std::string("No replacements were made. The old string was not found "
                   "in the plan file.\n\nDid you mean:\n  candidate"));
        expect(sv_of(no_replacements_message("  candidate")) == std::string("No replacements were made. The old string was not found "
                   "in the plan file.\n\nDid you mean:\n    candidate"));
        expect(sv_of(plan_edited_message(2, 5)) == std::string("Plan file successfully edited. Applied 2 edit(s) with 5 "
                   "total replacement(s)."));
        expect(sv_of(plan_failure_message("read plan", "boom")) == std::string("Failed to read plan. Error: boom"));
    };

    // -----------------------------------------------------------------------
    // Tool wrappers (hand-written expectations)
    // -----------------------------------------------------------------------
    "write_plan_tool_requires_plan_path"_test = [] {
        Session session;
        session.plan_enabled = true;
        WritePlan tool(&session);
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("# Plan"));
        tool(&params);
        const kimix::string json(tool.serialized_result().data(),
                                 tool.serialized_result().size());
        expect(sv_of(json).find(
                   "WritePlan tool invalid: no plan_writing_path set.") !=
               std::string::npos);
    };

    "write_plan_tool_disabled_session"_test = [] {
        Session session; // plan_enabled defaults to false
        WritePlan tool(&session);
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("x"));
        tool(&params);
        const kimix::string json(tool.serialized_result().data(),
                                 tool.serialized_result().size());
        expect(sv_of(json).find("unsupported") != std::string::npos);
    };

    "write_plan_tool_overwrite_and_append"_test = [] {
        Session session;
        session.plan_enabled = true;
        WritePlan tool(&session);
        tool.plan_path_override = "plan.md";
        tool.has_injected_content = true;
        tool.injected_content = "old";
        ToolParams params;
        params.values["content"] = ValueElement::make_string(kix("new"));
        tool(&params);
        expect(sv_of(tool.injected_content) == std::string("new"));
        kimix::string json(tool.serialized_result().data(),
                           tool.serialized_result().size());
        expect(sv_of(json).find("Plan written to plan.md") != std::string::npos);

        params.values["mode"] = ValueElement::make_string(kix("append"));
        params.values["content"] = ValueElement::make_string(kix("!"));
        tool(&params);
        expect(sv_of(tool.injected_content) == std::string("new!"));
        json.assign(tool.serialized_result().data(),
                    tool.serialized_result().size());
        expect(sv_of(json).find("Plan appended to plan.md") !=
               std::string::npos);
    };

    "read_plan_tool_renders_injected_content"_test = [] {
        Session session;
        session.plan_enabled = true;
        ReadPlan tool(&session);
        tool.plan_path_override = "plan.md";
        tool.has_injected_content = true;
        tool.injected_content = "a\nb\nc\n";
        tool(nullptr); // every parameter has a default
        const kimix::string json(tool.serialized_result().data(),
                                 tool.serialized_result().size());
        expect(sv_of(json).find("\"status\":\"ok\"") != std::string::npos);
        expect(sv_of(json).find("3 lines read from plan starting from line 1") !=
               std::string::npos);
        expect(sv_of(json).find("Total lines in file: 3.") != std::string::npos);
    };

    "read_plan_tool_tail_mode"_test = [] {
        Session session;
        session.plan_enabled = true;
        ReadPlan tool(&session);
        tool.plan_path_override = "plan.md";
        tool.has_injected_content = true;
        tool.injected_content = "a\nb\nc\n";
        ToolParams params;
        params.values["line_offset"] = ValueElement::make_int(-1);
        tool(&params);
        const kimix::string json(tool.serialized_result().data(),
                                 tool.serialized_result().size());
        expect(sv_of(json).find("1 lines read from plan starting from line 3") !=
               std::string::npos);
    };

    "edit_plan_tool_no_replacement"_test = [] {
        Session session;
        session.plan_enabled = true;
        EditPlan tool(&session);
        tool.plan_path_override = "plan.md";
        tool.has_injected_content = true;
        tool.injected_content = "alpha\nbeta\n";
        ToolParams edit;
        ToolParams item;
        item.values["old"] =
            ValueElement::make_string(kix("totally absent needle phrase"));
        item.values["new"] = ValueElement::make_string(kix("x"));
        edit.values["edit"] = ValueElement::make_object(
            kimix::shared_ptr<ToolParams>(new ToolParams(std::move(item))));
        tool(&edit);
        const kimix::string json(tool.serialized_result().data(),
                                 tool.serialized_result().size());
        expect(sv_of(json).find("No replacements were made.") !=
               std::string::npos);
        expect(sv_of(json).find("no_change") != std::string::npos);
        expect(sv_of(tool.injected_content) == std::string("alpha\nbeta\n"));
    };

    "edit_plan_tool_edits_array_and_message"_test = [] {
        Session session;
        session.plan_enabled = true;
        EditPlan tool(&session);
        tool.plan_path_override = "plan.md";
        tool.has_injected_content = true;
        tool.injected_content = "one two three\n";

        ToolParams first;
        first.values["old_string"] = ValueElement::make_string(kix("one"));
        first.values["new_string"] = ValueElement::make_string(kix("ONE"));
        ToolParams second;
        second.values["old"] = ValueElement::make_string(kix("two"));
        second.values["new"] = ValueElement::make_string(kix("TWO"));
        second.values["replace_all"] = ValueElement::make_bool(true);
        ValueElement::Array arr;
        arr.push_back(ValueElement::make_object(
            kimix::shared_ptr<ToolParams>(new ToolParams(std::move(first)))));
        arr.push_back(ValueElement::make_object(
            kimix::shared_ptr<ToolParams>(new ToolParams(std::move(second)))));
        ToolParams params;
        params.values["edits"] = ValueElement::make_array(std::move(arr));
        tool(&params);
        expect(sv_of(tool.injected_content) == std::string("ONE TWO three\n"));
        const kimix::string json(tool.serialized_result().data(),
                                 tool.serialized_result().size());
        expect(sv_of(json).find(
                   "Plan file successfully edited. Applied 2 edit(s) with 2 "
                   "total replacement(s).") != std::string::npos);
    };

    "edit_plan_tool_requires_edit"_test = [] {
        Session session;
        session.plan_enabled = true;
        EditPlan tool(&session);
        tool.plan_path_override = "plan.md";
        tool.has_injected_content = true;
        ToolParams params;
        tool(&params);
        const kimix::string json(tool.serialized_result().data(),
                                 tool.serialized_result().size());
        expect(sv_of(json).find("missing required field: edit") !=
               std::string::npos);
    };

    // -----------------------------------------------------------------------
    // Golden replay: LLM-facing tool metadata
    // -----------------------------------------------------------------------
    "tool_meta_matches_the_reference"_test = [] {
        for (const plan_meta_golden &g : kPlanMeta) {
            const ToolMeta *meta = ToolRegistry::instance().find(g.tool);
            expect(meta != nullptr) << "not registered: " << g.tool;
            if (meta == nullptr) {
                continue;
            }
            expect(sv_of(meta->description) == std::string(g.description))
                << "description mismatch: " << g.tool;
            ToolParams want;
            ToolParams got;
            expect(parse_json(g.params_json, want)) << g.tool;
            expect(parse_json(sv_of(meta->parameters_json), got)) << g.tool;
            expect(json_equal(ValueElement::make_object(
                                  kimix::shared_ptr<ToolParams>(
                                      new ToolParams(std::move(want)))),
                              ValueElement::make_object(
                                  kimix::shared_ptr<ToolParams>(
                                      new ToolParams(std::move(got))))))
                << "parameter schema mismatch: " << g.tool;
        }
    };

    // -----------------------------------------------------------------------
    // Golden replay: parameter validation matrix
    // -----------------------------------------------------------------------
    "param_matrix_matches_the_reference"_test = [] {
        for (const plan_param_golden &g : kPlanParamGoldens) {
            ToolParams params;
            expect(parse_json(g.params_json, params))
                << "golden params are not JSON: " << g.name;
            bool accepted = false;
            const std::string tool(g.tool);
            if (tool == "WritePlan") {
                write_plan_params out;
                accepted = !parse_write_params(&params, out).failed();
            } else if (tool == "ReadPlan") {
                read_plan_params out;
                accepted = !parse_read_params(&params, out).failed();
            } else {
                edit_plan_params out;
                accepted = !parse_edit_params(&params, out).failed();
            }
            if (g.deviation[0] != '\0') {
                expect(g.accepted == 1) << g.name;
                expect(!accepted) << "documented deviation accepted: " << g.name
                                  << " (" << g.deviation << ")";
                continue;
            }
            expect(accepted == (g.accepted == 1))
                << "accept/reject mismatch for " << g.name;
        }
    };

    // -----------------------------------------------------------------------
    // Golden replay: ReadPlan render engines
    // -----------------------------------------------------------------------
    "forward_render_goldens"_test = [] {
        for (const plan_render_golden &g : kForwardGoldens) {
            const std::string text = expand_text(g.text, g.text_len);
            expect(static_cast<long long>(text.size()) == g.text_len)
                << "corpus recipe drift: " << g.name;
            const kimix::vector<kimix::string> lines = lines_of(text);
            const plan_render r = render_forward(
                kimix::span<const kimix::string>(lines), g.line_offset,
                g.n_lines);
            const std::string rendered = sv_of(r.output);
            if (g.assert_output) {
                expect(rendered == std::string(g.output, g.output_len))
                    << "forward output mismatch: " << g.name;
            } else {
                expect(static_cast<long long>(rendered.size()) == g.output_len)
                    << "forward output size mismatch: " << g.name;
            }
            expect(line_count(rendered) == g.output_lines)
                << "forward line count mismatch: " << g.name;
            expect(sv_of(r.message) == std::string(g.message))
                << "forward message mismatch: " << g.name;
        }
    };

    "tail_render_goldens"_test = [] {
        for (const plan_render_golden &g : kTailGoldens) {
            const std::string text = expand_text(g.text, g.text_len);
            expect(static_cast<long long>(text.size()) == g.text_len)
                << "corpus recipe drift: " << g.name;
            const kimix::vector<kimix::string> lines = lines_of(text);
            const plan_render r = render_tail(
                kimix::span<const kimix::string>(lines), g.line_offset,
                g.n_lines);
            const std::string rendered = sv_of(r.output);
            if (g.assert_output) {
                expect(rendered == std::string(g.output, g.output_len))
                    << "tail output mismatch: " << g.name;
            } else {
                expect(static_cast<long long>(rendered.size()) == g.output_len)
                    << "tail output size mismatch: " << g.name;
            }
            expect(line_count(rendered) == g.output_lines)
                << "tail line count mismatch: " << g.name;
            expect(sv_of(r.message) == std::string(g.message))
                << "tail message mismatch: " << g.name;
        }
    };

    // -----------------------------------------------------------------------
    // Golden replay: char window (reference render + slice)
    // -----------------------------------------------------------------------
    "char_window_goldens"_test = [] {
        for (const plan_window_golden &g : kPlanWindowGoldens) {
            const kimix::vector<kimix::string> lines = lines_of(g.text);
            const plan_render r = render_forward(
                kimix::span<const kimix::string>(lines), 1, 1000);
            const kimix::string windowed =
                apply_char_window(r.output, g.char_offset, g.max_char);
            expect(sv_of(windowed) == std::string(g.output))
                << "window mismatch: " << g.name;
            expect(sv_of(r.message) == std::string(g.message))
                << "window message mismatch: " << g.name;
        }
    };

    // -----------------------------------------------------------------------
    // Golden replay: end-to-end tool calls on real files
    // -----------------------------------------------------------------------
    "tool_replay_goldens"_test = [] {
        std::error_code ec;
        const std::filesystem::path root =
            std::filesystem::temp_directory_path(ec) / "kimix_plan_goldens";
        std::filesystem::remove_all(root, ec);
        std::filesystem::create_directories(root, ec);
        const std::string root_str = root.string();

        for (const plan_tool_golden &g : kPlanToolGoldens) {
            Session session;
            session.plan_enabled = true;
            session.native_io = true;
            std::filesystem::path target;
            if (g.rel_path[0] != '\0') {
            target = native_path(root_str, g.rel_path);
            session.plan_path = kix(target.string());
            if (g.kind == 3) {
                // The target's *parent* must be a regular file.
                expect(write_bytes(target.parent_path(), "i am a file\n"))
                    << g.name;
            } else {
                std::filesystem::create_directories(target.parent_path(), ec);
                if (g.kind == 1) {
                    expect(write_bytes(
                               target,
                               std::string(g.initial,
                                           static_cast<size_t>(g.initial_len))))
                        << g.name;
                } else if (g.kind == 2) {
                    std::filesystem::create_directories(target, ec);
                }
            }
            }
            kimix::unique_ptr<Tool> tool = create_tool(g.tool, &session);
            expect(tool != nullptr) << "no such tool: " << g.tool;
            if (tool == nullptr) {
                continue;
            }
            ToolParams params;
            expect(parse_json(g.params_json, params)) << g.name;
            (*tool)(&params);
            kimix::vector<char> raw;
            tool->result_json(raw);
            const decoded_result got = decode_result(raw);
            expect(got.status == std::string(g.status))
                << "status mismatch for " << g.name << ": " << got.status;
            expect((got.status == "ok") == (g.is_error == 0))
                << "is_error mismatch for " << g.name;
            expect(got.message ==
                   replace_all(g.message, "@PLAN@", root_str))
                << "message mismatch for " << g.name << ": " << got.message;
            expect(got.output ==
                   replace_all(std::string(g.output,
                                           static_cast<size_t>(g.output_len)),
                               "@PLAN@", root_str))
                << "output mismatch for " << g.name;
            expect(got.brief == g.brief) << "brief mismatch for " << g.name;
            if (g.rel_path[0] == '\0') {
                continue;
            }
            // Render bookkeeping (ReadPlan only; -1 == not reported).
            if (std::string(g.tool) == "ReadPlan") {
                if (g.start_line >= 0) {
                    expect(got.start_line == g.start_line) << g.name;
                }
                if (g.total_lines >= 0) {
                    expect(got.total_lines == g.total_lines) << g.name;
                }
                if (g.max_lines_reached >= 0) {
                    expect(got.max_lines_reached == g.max_lines_reached) << g.name;
                }
                if (g.max_bytes_reached >= 0) {
                    expect(got.max_bytes_reached == g.max_bytes_reached) << g.name;
                }
                expect(got.truncated == std::string(g.truncated)) << g.name;
            }
            // On-disk result: the port writes the reference's text verbatim
            // (LF), so `initial`/`write_logical` are byte-exact expectations.
            std::error_code fec;
            const bool exists = std::filesystem::is_regular_file(target, fec);
            if (g.kind == 2) {
                expect(std::filesystem::is_directory(target, fec)) << g.name;
                continue;
            }
            expect(exists == (g.exists_after == 1))
                << "existence mismatch for " << g.name;
            if (!exists) {
                continue;
            }
            std::string bytes;
            expect(read_bytes(target, bytes)) << g.name;
            const std::string initial(g.initial,
                                      static_cast<size_t>(g.initial_len));
            const std::string logical(g.write_logical,
                                      static_cast<size_t>(g.write_logical_len));
            const std::string cpython(g.python_bytes,
                                      static_cast<size_t>(g.python_bytes_len));
            std::string expected(g.initial, static_cast<size_t>(g.initial_len));
            if (g.wrote) {
                if (!g.append) {
                    expected.clear();
                }
                expected += logical;
            }
            expect(bytes == expected)
                << "file content mismatch for " << g.name << ": " << bytes;
            // The documented CPython deviation: the reference writes through a
            // text-mode file object, so every LF of the written text became
            // CRLF on Windows (the bytes it left on disk are recorded in the
            // golden); the port writes the UTF-8 bytes verbatim (asserted
            // above). This pins the translation as the ONLY difference.
            std::string py_expected;
            if (!g.wrote) {
                py_expected = initial;
            } else {
                const std::string base = (g.kind == 1 && g.append) ? initial
                                                                  : std::string();
                py_expected = base + translate_lf(logical);
            }
            expect(cpython == py_expected)
                << "CPython text-mode bytes mismatch for " << g.name;
        }
    };

    // -----------------------------------------------------------------------
    // Golden replay: OS-level failures
    // -----------------------------------------------------------------------
    "os_error_goldens"_test = [] {
        std::error_code ec;
        const std::filesystem::path root =
            std::filesystem::temp_directory_path(ec) / "kimix_plan_os_goldens";
        std::filesystem::remove_all(root, ec);
        std::filesystem::create_directories(root, ec);
        const std::string root_str = root.string();

        for (const plan_os_error_golden &g : kPlanOsErrorGoldens) {
            Session session;
            session.plan_enabled = true;
            session.native_io = true;
            const std::filesystem::path target =
                native_path(root_str, g.rel_path);
            session.plan_path = kix(target.string());
            if (g.kind == 3) {
                // The target's *parent* must be a regular file.
                expect(write_bytes(target.parent_path(), "i am a file\n"))
                    << g.name;
            } else {
                std::filesystem::create_directories(target.parent_path(), ec);
                if (g.kind == 2) {
                    std::filesystem::create_directories(target, ec);
                }
            }
            kimix::unique_ptr<Tool> tool = create_tool(g.tool, &session);
            expect(tool != nullptr);
            if (tool == nullptr) {
                continue;
            }
            ToolParams params;
            expect(parse_json(g.params_json, params)) << g.name;
            (*tool)(&params);
            kimix::vector<char> raw;
            tool->result_json(raw);
            const decoded_result got = decode_result(raw);
            // CPython reports the raw OSError text ("[Errno 13] Permission
            // denied: '<path>'"), which is platform specific and cannot be
            // reproduced byte-exactly. The platform-independent parts are
            // pinned, plus the prefix the reference's own wrapper produces (the
            // reference's WritePlan `except` block reports str(exc) verbatim).
            expect((got.status == "ok") == (g.is_error == 0)) << g.name;
            expect(got.output == std::string(g.output)) << g.name;
            expect(got.brief == std::string(g.brief)) << g.name;
            const std::string prefix(g.message_prefix);
            expect(!got.message.empty()) << g.name;
            expect(got.message.compare(0, prefix.size(), prefix) == 0)
                << g.name << ": " << got.message;
            expect(got.message.find("Failed to write plan. Error:") ==
                   std::string::npos)
                << "WritePlan must report str(exc) verbatim, not an invented "
                   "wrapper: " << got.message;
        }
    };

    // -----------------------------------------------------------------------
    // Golden replay: the _enable_plan gate
    // -----------------------------------------------------------------------
    "gate_goldens_match_skip_this_tool"_test = [] {
        // Python raises SkipThisTool from the constructor, so a disabled plan
        // tool is never offered to the model. The C++ mirror keeps the tool in
        // the process-wide registry (it is registered statically) and refuses
        // every invocation with tool_status::unsupported instead.
        expect(ToolRegistry::instance().find("WritePlan") != nullptr);
        expect(ToolRegistry::instance().find("ReadPlan") != nullptr);
        expect(ToolRegistry::instance().find("EditPlan") != nullptr);
        for (const plan_gate_golden &g : kPlanGateGoldens) {
            expect(g.python_skips == 1) << g.tool;
            Session session; // plan_enabled == false
            session.native_io = true;
            session.plan_path = kix("plan.md");
            kimix::unique_ptr<Tool> tool = create_tool(g.tool, &session);
            expect(tool != nullptr) << g.tool;
            if (tool == nullptr) {
                continue;
            }
            (*tool)(nullptr);
            kimix::vector<char> raw;
            tool->result_json(raw);
            const decoded_result got = decode_result(raw);
            expect(got.status == "unsupported")
                << g.tool << " is not gated: " << got.status;
            expect(got.brief == "invalid tool.") << g.tool;
        }
    };
}
