// Test for builtin_tools/agent_tool.h (namespace kimix::builtin_tools::agents).
//
// Covers:
// - agent_registry store semantics: put/get/close, insertion-ordered
//   list_active, MAX_SESSIONS=10 LRU eviction, the live-session map
// - the pending-message queue: 50-per-target cap, drain-once, count
// - format_pending_messages / queued_message_output / prefix_sender verbatim
// - resolve_prompt (@path indirection, base_dir -> CWD fallback, missing file)
// - prompt_saved_message / offload_long_prompt / inject_response
// - build_context_block (files, read errors, structured data)
// - format_history_markdown (role icons + labels) / format_history_summary /
//   turn_to_value
// - list_active_json (orjson OPT_INDENT_2 shape and key order)
// - resolve_send_target: sub-agent -> parent, explicit id, unregistered id,
//   most-recently-active default, no active children
// - parameter parsing for all four tools (aliases + validation)
// - Subagent / SendMessageTool / ListAgents / InterruptAgent Tool wrappers with an
//   injected runner: foreground success, failure with the saved-prompt hint,
//   awaiting-response state, close_session vs continued, background start +
//   join + interrupt, the recursion guard and the unsupported-without-runner
//   path
// - the Python-derived golden replay (agent_goldens.inc, generated by
//   scripts/gen_agent_goldens.py): 120 steps over 43 cases that compare the
//   serialized result tree *and* the whole registry state (list_active JSON,
//   store entries, live sessions, pending queues, saved prompts, the effective
//   prompt handed to the runner) after every step of the
//   spawn -> list -> send -> resume -> interrupt -> list state machine
//
// All test logic lives in main() scope; no file-scope static registrations.
#include "ut/ut.hpp"

#include <core/kimix_core.h>

#include "builtin_tools/agent_tool.h"

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstring>
#include <string>
#include <thread>
#include <utility>
#include <vector>

using namespace boost::ut;
using namespace boost::ut::literals;
using namespace kimix::builtin_tools;
using namespace kimix::builtin_tools::agents;

namespace {

kimix::string kix(std::string_view sv) {
    return kimix::string(sv.data(), sv.size());
}

std::string sv_of(const kimix::string &s) {
    return std::string(s.data(), s.size());
}

std::string json_of(const kimix::vector<char> &buf) {
    return std::string(buf.data(), buf.size());
}

bool has(const kimix::vector<char> &buf, std::string_view needle) {
    return json_of(buf).find(std::string(needle)) != std::string::npos;
}

// A deterministic clock so created_at / last_accessed are predictable.
struct fake_clock {
    kimix::shared_ptr<double> value =
        kimix::shared_ptr<double>(new double(1000.0));
    kimix::function<double()> fn() {
        kimix::shared_ptr<double> v = value;
        return [v]() { return *v; };
    }
    void advance(double seconds) { *value += seconds; }
};

// An in-memory file table standing in for the file-system hooks.
struct fake_files {
    kimix::shared_ptr<std::vector<std::pair<std::string, std::string>>> table =
        kimix::shared_ptr<std::vector<std::pair<std::string, std::string>>>(
            new std::vector<std::pair<std::string, std::string>>());
    kimix::shared_ptr<std::vector<std::string>> saved =
        kimix::shared_ptr<std::vector<std::string>>(
            new std::vector<std::string>());

    void add(std::string path, std::string content) {
        table->emplace_back(std::move(path), std::move(content));
    }
    read_file_fn reader() {
        auto t = table;
        return [t](kimix::string_view path, kimix::string &out) {
            const std::string want(path.data(), path.size());
            for (const auto &entry : *t) {
                if (entry.first == want) {
                    out = kix(entry.second);
                    return true;
                }
            }
            return false;
        };
    }
    save_prompt_fn saver() {
        auto t = table;
        auto s = saved;
        return [t, s](kimix::string_view text, kimix::string_view ext) {
            const std::string name =
                ".kimix_cache/prompt_" + std::to_string(s->size()) +
                std::string(ext.data(), ext.size());
            s->push_back(name);
            t->emplace_back(name, std::string(text.data(), text.size()));
            return kix(name);
        };
    }
};

agent_entry make_entry(std::string_view id, double created, double accessed,
                       std::string_view state = "completed") {
    agent_entry e;
    e.session_id = kix(id);
    e.created_at = created;
    e.last_accessed = accessed;
    e.state = kix(state);
    e.is_active = true;
    return e;
}

// A scripted runner that records every request it receives.
struct fake_runner {
    kimix::shared_ptr<std::vector<subagent_request>> calls =
        kimix::shared_ptr<std::vector<subagent_request>>(
            new std::vector<subagent_request>());
    kimix::shared_ptr<subagent_run_result> result =
        kimix::shared_ptr<subagent_run_result>(new subagent_run_result());

    subagent_runner fn() {
        auto c = calls;
        auto r = result;
        return [c, r](const subagent_request &req) {
            c->push_back(req);
            return *r;
        };
    }
};

} // namespace

// ===========================================================================
// Python-derived golden replay (scripts/gen_agent_goldens.py)
// ===========================================================================
// tests/unit/builtin_tools/agent_goldens.inc is generated by
// scripts/gen_agent_goldens.py, which drives the *real* kimi-agent sub-agent
// tools (C:/dev/kimi-agent/src/kimix/tools/agent/__init__.py + store.py)
// against a stub runtime/session and records, after every step, the tool result
// plus the whole registry state (store entries, live sessions, pending queues,
// prompts saved to the shared temp folder and the effective prompt handed to
// the sub-agent runner).  The replay below drives the C++ port over the same
// arguments and compares every column.  One row is one tool call; a row with
// step == 0 starts a fresh case (fresh Session + agent_registry).
#include "agent_goldens.inc"

namespace {

using kimix::builtin_tools::ToolParams;
using kimix::builtin_tools::ValueElement;
using kimix::builtin_tools::Session;
using kimix::builtin_tools::agents::agent_entry;
using kimix::builtin_tools::agents::agent_registry;
using kimix::builtin_tools::agents::subagent_request;
using kimix::builtin_tools::agents::subagent_run_result;

namespace agl {

//: One comparison outcome: either "equal" or the first difference found.
struct diff {
    bool ok = true;
    std::string why;

    static diff good() { return diff{}; }
    static diff bad(std::string why) { return diff{false, std::move(why)}; }
};

// Parse a JSON fragment of any type (ToolParams only accepts object roots, so
// arrays/scalars are wrapped like the todo goldens' decoder).
inline bool parse_value(const char *json, ValueElement &out) {
    kimix::string wrapped("{\"v\":");
    wrapped += json;
    wrapped += "}";
    ToolParams tp;
    kimix::string err;
    if (!tp.try_deserialize(
            kimix::span<char const>(wrapped.data(), wrapped.size()), err)) {
        return false;
    }
    const ValueElement *el = tp.get_exact("v");
    if (el == nullptr) {
        return false;
    }
    out = *el;
    return true;
}

inline bool parse_object(const char *json, ToolParams &out) {
    const char *text = (json != nullptr && json[0] != '\0') ? json : "{}";
    kimix::string err;
    return out.try_deserialize(
        kimix::span<char const>(text, std::strlen(text)), err);
}

inline bool is_str(const ValueElement *el) {
    return el != nullptr && el->is_string();
}

inline std::string text_of(const ValueElement *el) {
    if (!is_str(el)) {
        return {};
    }
    const kimix::string &s = el->as_string();
    return std::string(s.data(), s.size());
}

// Shorten a string for a Boost.UT failure message.
inline std::string clip(const std::string &text, size_t limit = 160) {
    if (text.size() <= limit) {
        return text;
    }
    return text.substr(0, limit) + "...";
}

inline bool as_double(const ValueElement *el, double &out) {
    if (el == nullptr) {
        return false;
    }
    if (el->is_real()) {
        out = el->as_real();
        return true;
    }
    if (el->is_int()) {
        out = static_cast<double>(el->as_int());
        return true;
    }
    if (el->is_uint()) {
        out = static_cast<double>(el->as_uint());
        return true;
    }
    return false;
}

inline bool as_int(const ValueElement *el, int64_t &out) {
    if (el == nullptr) {
        return false;
    }
    if (el->is_int()) {
        out = el->as_int();
        return true;
    }
    if (el->is_uint()) {
        out = static_cast<int64_t>(el->as_uint());
        return true;
    }
    return false;
}

// Expand the <NEWn> tokens the generator used for tool-allocated session ids.
inline std::string expand(std::string text,
                          const std::vector<std::string> &fresh) {
    for (size_t i = 0; i < fresh.size(); ++i) {
        const std::string token = "<NEW" + std::to_string(i) + ">";
        for (size_t at = text.find(token); at != std::string::npos;
             at = text.find(token, at)) {
            text.replace(at, token.size(), fresh[i]);
        }
    }
    return text;
}

// The inverse: mask this run's own tool-allocated ids so a string can be
// compared with a golden that used tokens.
inline std::string mask(std::string text,
                        const std::vector<std::string> &fresh) {
    for (size_t i = 0; i < fresh.size(); ++i) {
        if (fresh[i].empty()) {
            continue;
        }
        for (size_t at = text.find(fresh[i]); at != std::string::npos;
             at = text.find(fresh[i], at)) {
            text.replace(at, fresh[i].size(),
                         "<NEW" + std::to_string(i) + ">");
        }
    }
    return text;
}

// Load a golden runner payload into the runner result the port expects.
inline bool load_runner(const char *json, subagent_run_result &out) {
    ToolParams p;
    if (!parse_object(json, p)) {
        return false;
    }
    const ValueElement *ok = p.get_exact("ok");
    out.ok = (ok != nullptr && ok->is_bool()) ? ok->as_bool() : false;
    out.output = kimix::string(text_of(p.get_exact("output")));
    out.error = kimix::string(text_of(p.get_exact("error")));
    const ValueElement *q = p.get_exact("pending_question");
    if (is_str(q)) {
        out.pending_question = q->as_string();
    }
    const ValueElement *turns = p.get_exact("turns");
    if (turns != nullptr && turns->is_array()) {
        for (const ValueElement &t : turns->as_array()) {
            const ToolParams *obj = t.as_object();
            if (obj == nullptr) {
                return false;
            }
            kimix::builtin_tools::agents::conversation_turn turn;
            turn.role = kimix::string(text_of(obj->get_exact("role")));
            turn.content = kimix::string(text_of(obj->get_exact("content")));
            as_double(obj->get_exact("timestamp"), turn.timestamp);
            turn.type = kimix::string(text_of(obj->get_exact("type")));
            out.turns.push_back(std::move(turn));
        }
    }
    return true;
}

// The multi-line message the agent tools render into their output strings.
inline std::string json_text(const ValueElement *el) {
    if (el == nullptr || el->is_null()) {
        return "<none>";
    }
    if (el->is_string()) {
        return std::string(el->as_string().data(), el->as_string().size());
    }
    return "<not-a-string>";
}

// Compare one conversation turn of extras.conversation_history (json format).
inline diff compare_turn(const ToolParams *got, const ToolParams *want,
                         const std::string &where,
                         const std::vector<std::string> &fresh) {
    if (got == nullptr || want == nullptr) {
        return diff::bad(where + ": turn is not an object");
    }
    if (text_of(got->get_exact("role")) != text_of(want->get_exact("role"))) {
        return diff::bad(where + ": role " +
                         text_of(got->get_exact("role")) + " != " +
                         text_of(want->get_exact("role")));
    }
    if (mask(text_of(got->get_exact("content")), fresh) !=
        text_of(want->get_exact("content"))) {
        return diff::bad(where + ": content \"" +
                         text_of(got->get_exact("content")) + "\" != \"" +
                         text_of(want->get_exact("content")) + "\"");
    }
    double gt = 0.0;
    double wt = 1.0;
    if (!as_double(got->get_exact("timestamp"), gt) ||
        !as_double(want->get_exact("timestamp"), wt) || gt != wt) {
        return diff::bad(where + ": timestamp mismatch");
    }
    const ValueElement *gm = got->get_exact("metadata");
    const ValueElement *wm = want->get_exact("metadata");
    const bool g_null = (gm == nullptr || gm->is_null());
    const bool w_null = (wm == nullptr || wm->is_null());
    if (g_null != w_null) {
        return diff::bad(where + ": metadata presence mismatch");
    }
    if (!g_null) {
        const ToolParams *go = gm->as_object();
        const ToolParams *wo = wm->as_object();
        if (go == nullptr || wo == nullptr ||
            text_of(go->get_exact("type")) != text_of(wo->get_exact("type"))) {
            return diff::bad(where + ": metadata.type mismatch");
        }
    }
    return diff::good();
}

// Compare the extras object (the generator stores the Python result's extras,
// or {} when the Python result carried extras=None).
inline diff compare_extras(const ToolParams *got, const ValueElement &want_el,
                           const std::vector<std::string> &fresh) {
    const ToolParams *want = want_el.as_object();
    if (want == nullptr) {
        return diff::bad("golden extras is not an object");
    }
    // Exact key set: a missing or extra key is a mismatch.
    std::vector<std::string> gk;
    std::vector<std::string> wk;
    for (const auto &kv : got->values) {
        gk.emplace_back(kv.first.data(), kv.first.size());
    }
    for (const auto &kv : want->values) {
        wk.emplace_back(kv.first.data(), kv.first.size());
    }
    std::sort(gk.begin(), gk.end());
    std::sort(wk.begin(), wk.end());
    if (gk != wk) {
        std::string gjoin;
        std::string wjoin;
        for (const std::string &k : gk) {
            gjoin += k + " ";
        }
        for (const std::string &k : wk) {
            wjoin += k + " ";
        }
        return diff::bad("extras keys [" + gjoin + "] != golden [" + wjoin + "]");
    }
    for (const std::string &key : wk) {
        const ValueElement *g = got->get_exact(key);
        const ValueElement *w = want->get_exact(key);
        if (key == "turn_count") {
            int64_t a = 0;
            int64_t b = 1;
            if (!as_int(g, a) || !as_int(w, b) || a != b) {
                return diff::bad("extras.turn_count mismatch");
            }
        } else if (key == "conversation_history") {
            if (g == nullptr || w == nullptr) {
                return diff::bad("extras.conversation_history missing");
            }
            if (w->is_string() || g->is_string()) {
                if (mask(text_of(g), fresh) != text_of(w)) {
                    return diff::bad("extras.conversation_history text \"" +
                                     mask(text_of(g), fresh) + "\" != \"" +
                                     text_of(w) + "\"");
                }
            } else if (w->is_array() && g->is_array()) {
                const ValueElement::Array &ga = g->as_array();
                const ValueElement::Array &wa = w->as_array();
                if (ga.size() != wa.size()) {
                    return diff::bad("extras.conversation_history size " +
                          std::to_string(ga.size()) + " != " +
                          std::to_string(wa.size()));
                }
                for (size_t i = 0; i < wa.size(); ++i) {
                  const diff d = compare_turn(
                      ga[i].as_object(), wa[i].as_object(),
                      "conversation_history[" + std::to_string(i) + "]",
                      fresh);
                    if (!d.ok) {
                        return d;
                    }
                }
            } else {
                return diff::bad("extras.conversation_history type mismatch");
            }
        } else if (mask(text_of(g), fresh) != text_of(w)) {
            return diff::bad("extras." + key + " \"" +
                             mask(text_of(g), fresh) + "\" != golden \"" +
                             text_of(w) + "\"");
        }
    }
    return diff::good();
}

} // namespace agl

} // namespace

int main(int argc, char *argv[]) {
    boost::ut::detail::cfg::parse_arg_with_fallback(
        argc, const_cast<const char **>(argv));

    // -----------------------------------------------------------------------
    // Registry store semantics
    // -----------------------------------------------------------------------
    "registry_put_get_close"_test = [] {
        agent_registry reg;
        expect(reg.get("missing") == nullptr);
        reg.put(make_entry("a", 1.0, 2.0));
        const agent_entry *found = reg.get("a");
        expect(found != nullptr);
        expect(found->session_id == kix("a"));
        expect(found->created_at == 1.0);
        expect(reg.size() == 1u);
        expect(reg.close("a"));
        expect(reg.get("a") == nullptr);
        expect(!reg.close("a"));
        expect(reg.size() == 0u);
    };

    "registry_put_updates_in_place"_test = [] {
        agent_registry reg;
        reg.put(make_entry("a", 1.0, 2.0));
        agent_entry updated = make_entry("a", 1.0, 9.0, "awaiting_response");
        updated.total_turns = 4;
        reg.put(updated);
        expect(reg.size() == 1u);
        const agent_entry *found = reg.get("a");
        expect(found->last_accessed == 9.0);
        expect(found->state == kix("awaiting_response"));
        expect(found->total_turns == 4_i);
    };

    "registry_list_active_keeps_insertion_order"_test = [] {
        agent_registry reg;
        reg.put(make_entry("first", 1.0, 5.0));
        reg.put(make_entry("second", 2.0, 6.0));
        reg.put(make_entry("third", 3.0, 4.0));
        const kimix::vector<agent_list_item> items = reg.list_active();
        expect(items.size() == 3u);
        expect(items[0].session_id == kix("first"));
        expect(items[1].session_id == kix("second"));
        expect(items[2].session_id == kix("third"));
    };

    "registry_list_active_skips_inactive"_test = [] {
        agent_registry reg;
        agent_entry inactive = make_entry("gone", 1.0, 1.0);
        inactive.is_active = false;
        reg.put(inactive);
        reg.put(make_entry("here", 1.0, 1.0));
        const kimix::vector<agent_list_item> items = reg.list_active();
        expect(items.size() == 1u);
        expect(items[0].session_id == kix("here"));
    };

    "registry_evicts_lru_at_max_sessions"_test = [] {
        agent_registry reg;
        // MAX_SESSIONS is 10: eviction runs while size() >= 10, so inserting
        // the 10th entry is allowed and the 11th triggers one eviction.
        for (int i = 0; i < 10; ++i) {
            reg.put(make_entry(kimix::format("s{}", i), 1.0,
                               100.0 + static_cast<double>(i)));
        }
        expect(reg.size() == 10u);
        const kimix::vector<kimix::string> evicted = reg.evict_lru_if_needed();
        expect(evicted.size() == 1u);
        // s0 has the smallest last_accessed.
        expect(evicted[0] == kix("s0"));
        expect(reg.size() == 9u);
        expect(reg.get("s0") == nullptr);
        expect(reg.get("s9") != nullptr);
    };

    "registry_eviction_is_a_noop_below_the_cap"_test = [] {
        agent_registry reg;
        reg.put(make_entry("only", 1.0, 1.0));
        expect(reg.evict_lru_if_needed().empty());
        expect(reg.size() == 1u);
    };

    "registry_live_session_map"_test = [] {
        agent_registry reg;
        expect(!reg.has_session("x"));
        reg.register_session("x");
        expect(reg.has_session("x"));
        reg.register_session(""); // ignored
        expect(!reg.has_session(""));
        reg.unregister_session("x");
        expect(!reg.has_session("x"));
    };

    // -----------------------------------------------------------------------
    // Pending message queue
    // -----------------------------------------------------------------------
    "pending_queue_drains_once"_test = [] {
        agent_registry reg;
        reg.queue_pending_message("t1", "first");
        reg.queue_pending_message("t1", "second");
        expect(reg.pending_message_count("t1") == 2u);
        const kimix::vector<kimix::string> drained =
            reg.drain_pending_messages("t1");
        expect(drained.size() == 2u);
        expect(drained[0] == kix("first"));
        expect(drained[1] == kix("second"));
        expect(reg.pending_message_count("t1") == 0u);
        expect(reg.drain_pending_messages("t1").empty());
    };

    "pending_queue_caps_at_fifty"_test = [] {
        agent_registry reg;
        for (int i = 0; i < 60; ++i) {
            reg.queue_pending_message("t", kimix::format("m{}", i));
        }
        expect(reg.pending_message_count("t") == k_max_pending_messages);
        const kimix::vector<kimix::string> drained =
            reg.drain_pending_messages("t");
        expect(drained.size() == 50u);
        // The FIRST fifty are kept (later ones are dropped).
        if (!drained.empty()) {
            expect(drained.at(0) == kix("m0"));
            expect(drained.at(drained.size() - 1) == kix("m49"));
        }
    };

    "pending_queue_is_per_target"_test = [] {
        agent_registry reg;
        reg.queue_pending_message("a", "for-a");
        reg.queue_pending_message("b", "for-b");
        expect(reg.pending_message_count("a") == 1u);
        expect(reg.pending_message_count("b") == 1u);
        expect(reg.drain_pending_messages("a")[0] == kix("for-a"));
    };

    "format_pending_messages_block"_test = [] {
        expect(format_pending_messages(
                   kimix::span<const kimix::string>())
                   .empty());
        const kimix::vector<kimix::string> msgs = {kix("do X"), kix("then Y")};
        const std::string out = sv_of(format_pending_messages(
            kimix::span<const kimix::string>(msgs)));
        const std::string expected =
            "<pending-messages>\n"
            "You have the following queued message(s) from the parent agent "
            "(sent while you were idle or not running):\n"
            "1. do X\n"
            "2. then Y\n"
            "</pending-messages>";
        expect(out == expected) << "got:\n" << out;
    };

    "queued_message_output_wording"_test = [] {
        const std::string out = sv_of(queued_message_output("abc", "not running"));
        expect(out.find("Agent 'abc' is not running (not running).") == 0);
        expect(out.find("Message queued; it will be listed in the target's "
                        "next prompt only if you resume the session with "
                        "subagent(session_id='abc', ...).") !=
               std::string::npos);
        expect(out.find("Otherwise it stays queued (no delivery).") !=
               std::string::npos);
    };

    "prefix_sender_wording"_test = [] {
        expect(prefix_sender("", "hello") == kix("hello"));
        expect(prefix_sender("parent-1", "hello") ==
               kix("Message from agent 'parent-1':\nhello"));
    };

    // -----------------------------------------------------------------------
    // resolve_prompt
    // -----------------------------------------------------------------------
    "resolve_prompt_inline"_test = [] {
        fake_files files;
        kimix::string out;
        kimix::string error;
        expect(resolve_prompt("plain task", "/work", files.reader(), out,
                              error));
        expect(out == kix("plain task"));
        expect(error.empty());
    };

    "resolve_prompt_at_path_relative_to_base_dir"_test = [] {
        fake_files files;
        files.add("/work/task.md", "task body");
        kimix::string out;
        kimix::string error;
        expect(resolve_prompt("@task.md", "/work", files.reader(), out, error));
        expect(out == kix("task body"));
    };

    "resolve_prompt_falls_back_to_cwd_relative"_test = [] {
        fake_files files;
        // Not present under base_dir, but present relative to the process CWD.
        files.add("task.md", "cwd body");
        kimix::string out;
        kimix::string error;
        expect(resolve_prompt("@task.md", "/work", files.reader(), out, error));
        expect(out == kix("cwd body"));
    };

    "resolve_prompt_missing_file"_test = [] {
        fake_files files;
        kimix::string out;
        kimix::string error;
        expect(!resolve_prompt("@nope.md", "/work", files.reader(), out, error));
        expect(error == kix("prompt file not found: nope.md"));
    };

    "resolve_prompt_absolute_path"_test = [] {
        fake_files files;
        files.add("/abs/task.md", "abs body");
        kimix::string out;
        kimix::string error;
        expect(resolve_prompt("@/abs/task.md", "/work", files.reader(), out,
                              error));
        expect(out == kix("abs body"));
    };

    "prompt_saved_message_wording"_test = [] {
        expect(prompt_saved_message("", "p.md").empty());
        expect(prompt_saved_message("task", "").empty());
        expect(prompt_saved_message("task", ".kimix_cache/tmp_1/0.md") ==
               kix("[prompt saved to .kimix_cache/tmp_1/0.md] Retry with "
                   "subagent(prompt=@.kimix_cache/tmp_1/0.md) to reuse this "
                   "prompt."));
    };

    "offload_long_prompt_threshold"_test = [] {
        const kimix::string short_prompt(100, 'a');
        expect(offload_long_prompt(short_prompt, "p.md") == short_prompt);
        const kimix::string long_prompt(k_prompt_offload_bytes + 1, 'a');
        expect(offload_long_prompt(long_prompt, "p.md") ==
               kix("Please read the task from `p.md` and execute it."));
        // Exactly at the limit is NOT offloaded.
        const kimix::string exact(k_prompt_offload_bytes, 'a');
        expect(offload_long_prompt(exact, "p.md") == exact);
    };

    "inject_response_wording"_test = [] {
        expect(inject_response("do the task", "which mode?", "fast") ==
               kix("The parent agent responded to your question (which "
                   "mode?):\n\nfast\n\nNow, regarding your original task: do "
                   "the task"));
    };

    // -----------------------------------------------------------------------
    // build_context_block
    // -----------------------------------------------------------------------
    "context_block_files_and_data"_test = [] {
        fake_files files;
        files.add("/work/a.txt", "AAA");
        const kimix::vector<kimix::string> ctx_files = {kix("a.txt"),
                                                        kix("missing.txt")};
        const std::string out = sv_of(build_context_block(
            kimix::span<const kimix::string>(ctx_files), "{\"k\": 1}",
            files.reader(), "/work"));
        expect(out.find("<context>\n") == 0);
        expect(out.find("<file path='a.txt'>\nAAA\n</file>") !=
               std::string::npos);
        expect(out.find("<file path='missing.txt' error='") !=
               std::string::npos);
        expect(out.find("<data>\n{\"k\": 1}\n</data>") != std::string::npos);
        // "\n</context>" is eleven characters.
        expect(out.size() >= 11u && out.compare(out.size() - 11, 11,
                                                "\n</context>") == 0)
            << out;
    };

    "context_block_empty_when_no_inputs"_test = [] {
        fake_files files;
        expect(build_context_block(kimix::span<const kimix::string>(), "",
                                   files.reader(), "/work")
                   .empty());
    };

    // -----------------------------------------------------------------------
    // History formatting
    // -----------------------------------------------------------------------
    "format_history_markdown"_test = [] {
        conversation_turn user;
        user.role = "user";
        user.content = "hi";
        user.type = "text";
        conversation_turn assistant;
        assistant.role = "assistant";
        assistant.content = "hello";
        assistant.type = "text";
        conversation_turn tool;
        tool.role = "tool";
        tool.content = "result";
        tool.type = "tool_result";
        const kimix::vector<conversation_turn> turns = {user, assistant, tool};
        const std::string out = sv_of(format_history_markdown(
            kimix::span<const conversation_turn>(turns)));
        // The label is metadata["type"] when present (Python:
        // `turn.metadata.get("type", turn.role)`), so a "text" turn is
        // labelled "text", not by its role.
        expect(out.find("### Turn 1: \xF0\x9F\x91\xA4 text") !=
               std::string::npos)
            << out;
        expect(out.find("### Turn 2: \xF0\x9F\xA4\x96 text") !=
               std::string::npos)
            << out;
        expect(out.find("### Turn 3: \xF0\x9F\x94\xA7 tool_result") !=
               std::string::npos)
            << out;
        expect(out.find("\nhi\n") != std::string::npos);
        // Without metadata the label falls back to the role.
        conversation_turn bare;
        bare.role = "system";
        bare.content = "note";
        const kimix::vector<conversation_turn> bare_turns = {bare};
        const std::string bare_out = sv_of(format_history_markdown(
            kimix::span<const conversation_turn>(bare_turns)));
        expect(bare_out.find("### Turn 1: \xE2\x9A\x99\xEF\xB8\x8F system") !=
               std::string::npos)
            << bare_out;
        // An unknown role renders "?".
        conversation_turn odd;
        odd.role = "mystery";
        const kimix::vector<conversation_turn> odd_turns = {odd};
        expect(sv_of(format_history_markdown(
                   kimix::span<const conversation_turn>(odd_turns)))
                   .find("### Turn 1: ? mystery") != std::string::npos);
    };

    "format_history_summary_counts"_test = [] {
        conversation_turn call;
        call.role = "assistant";
        call.type = "tool_call";
        conversation_turn res;
        res.role = "tool";
        res.type = "tool_result";
        conversation_turn text;
        text.role = "assistant";
        text.type = "text";
        text.content = "abcde"; // 5 code points
        conversation_turn think;
        think.role = "assistant";
        think.type = "think";
        think.content = "ignored";
        const kimix::vector<conversation_turn> turns = {call, res, text, think};
        expect(format_history_summary(
                   kimix::span<const conversation_turn>(turns)) ==
               kix("Sub-agent made 1 tool call(s) with 1 result(s), and "
                   "produced 1 text response(s) (5 total characters)."));
    };

    "turn_to_value_shape"_test = [] {
        conversation_turn turn;
        turn.role = "assistant";
        turn.content = "body";
        turn.timestamp = 12.5;
        turn.type = "text";
        const ValueElement value = turn_to_value(turn);
        expect(value.is_object());
        const ToolParams *obj = value.as_object();
        expect(obj != nullptr);
        expect(obj->get("role")->as_string() == kix("assistant"));
        expect(obj->get("content")->as_string() == kix("body"));
        expect(obj->get("timestamp")->as_real() == 12.5);
        const ToolParams *meta = obj->get("metadata")->as_object();
        expect(meta != nullptr);
        expect(meta->get("type")->as_string() == kix("text"));
    };

    // -----------------------------------------------------------------------
    // list_active_json
    // -----------------------------------------------------------------------
    "list_active_json_empty"_test = [] {
        expect(list_active_json(kimix::span<const agent_list_item>()) ==
               kix("[]"));
    };

    "list_active_json_shape"_test = [] {
        const kimix::vector<agent_list_item> items = {
            {kix("id-1"), 100.5, 200.25, 3, kix("running"), true}};
        const std::string out = sv_of(list_active_json(
            kimix::span<const agent_list_item>(items)));
        // orjson OPT_INDENT_2: two-space indent, insertion key order.
        expect(out.find("[\n  {\n") == 0) << out;
        expect(out.find("\"session_id\": \"id-1\"") != std::string::npos);
        expect(out.find("\"created_at\": 100.5") != std::string::npos);
        expect(out.find("\"last_accessed\": 200.25") != std::string::npos);
        expect(out.find("\"total_turns\": 3") != std::string::npos);
        expect(out.find("\"state\": \"running\"") != std::string::npos);
        expect(out.find("\"is_active\": true") != std::string::npos);
        // The document closes with "\n  }\n]" (six characters).
        expect(out.size() >= 6u &&
               out.compare(out.size() - 6, 6, "\n  }\n]") == 0)
            << out;
        // Key order matters for byte parity with orjson.
        expect(out.find("session_id") < out.find("created_at"));
        expect(out.find("created_at") < out.find("last_accessed"));
        expect(out.find("last_accessed") < out.find("total_turns"));
        expect(out.find("total_turns") < out.find("state"));
        expect(out.find("state") < out.find("is_active"));
    };

    "list_active_json_escapes"_test = [] {
        const kimix::vector<agent_list_item> items = {
            {kix("q\"uote"), 1.0, 2.0, 0, kix("a&b<c>"), true}};
        const std::string out = sv_of(list_active_json(
            kimix::span<const agent_list_item>(items)));
        expect(out.find("q\\\"uote") != std::string::npos);
        expect(out.find("a&b<c>") != std::string::npos);
    };

    // -----------------------------------------------------------------------
    // resolve_send_target
    // -----------------------------------------------------------------------
    "send_target_sub_agent_messages_parent"_test = [] {
        agent_registry reg;
        reg.register_session("parent-1");
        const send_target t = resolve_send_target(reg, true, "parent-1", "child");
        expect(t.target_id.has_value());
        expect(*t.target_id == kix("parent-1")); // `id` is ignored
        expect(t.has_live_session);
        expect(t.reason.empty());
    };

    "send_target_sub_agent_without_parent"_test = [] {
        agent_registry reg;
        const send_target t = resolve_send_target(reg, true, "", "child");
        expect(!t.target_id.has_value());
        expect(t.reason ==
               kix("sub-agent has no recorded parent_session_id"));
    };

    "send_target_sub_agent_parent_unregistered"_test = [] {
        agent_registry reg;
        const send_target t =
            resolve_send_target(reg, true, "gone-parent", "child");
        expect(t.target_id.has_value());
        expect(*t.target_id == kix("gone-parent"));
        expect(!t.has_live_session);
        expect(t.reason == kix("parent agent 'gone-parent' is not registered"));
    };

    "send_target_explicit_id"_test = [] {
        agent_registry reg;
        reg.register_session("child-1");
        const send_target t = resolve_send_target(reg, false, "", "child-1");
        expect(*t.target_id == kix("child-1"));
        expect(t.has_live_session);
    };

    "send_target_unregistered_id"_test = [] {
        agent_registry reg;
        const send_target t = resolve_send_target(reg, false, "", "ghost");
        expect(*t.target_id == kix("ghost"));
        expect(!t.has_live_session);
        expect(t.reason == kix("agent 'ghost' is not registered"));
    };

    "send_target_defaults_to_most_recently_active"_test = [] {
        agent_registry reg;
        reg.put(make_entry("old", 1.0, 10.0));
        reg.put(make_entry("newest", 1.0, 99.0));
        reg.put(make_entry("middle", 1.0, 50.0));
        reg.register_session("newest");
        const send_target t = resolve_send_target(reg, false, "", "");
        expect(*t.target_id == kix("newest"));
        expect(t.has_live_session);
    };

    "send_target_no_active_children"_test = [] {
        agent_registry reg;
        const send_target t = resolve_send_target(reg, false, "", "");
        expect(!t.target_id.has_value());
        expect(t.reason == kix("no active sub-agents to message"));
    };

    "is_resumable_requires_an_active_entry"_test = [] {
        agent_registry reg;
        expect(!is_resumable(reg, "a"));
        expect(!is_resumable(reg, ""));
        reg.put(make_entry("a", 1.0, 1.0));
        expect(is_resumable(reg, "a"));
        agent_entry inactive = make_entry("b", 1.0, 1.0);
        inactive.is_active = false;
        reg.put(inactive);
        expect(!is_resumable(reg, "b"));
    };

    // -----------------------------------------------------------------------
    // Parameter parsing
    // -----------------------------------------------------------------------
    "subagent_params_defaults"_test = [] {
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("do it"));
        subagent_params out;
        expect(!parse_subagent_params(&params, out).failed());
        expect(out.prompt == kix("do it"));
        expect(out.run_in_background);
        expect(out.close_session);
        expect(!out.return_history);
        expect(out.history_format == kix("json"));
        expect(!out.inherit_context);
        expect(!out.session_id.has_value());
    };

    "subagent_params_task_alias"_test = [] {
        ToolParams params;
        params.values["task"] = ValueElement::make_string(kix("aliased"));
        subagent_params out;
        expect(!parse_subagent_params(&params, out).failed());
        expect(out.prompt == kix("aliased"));
    };

    "subagent_params_requires_prompt"_test = [] {
        ToolParams params;
        subagent_params out;
        const tool_error err = parse_subagent_params(&params, out);
        expect(err.failed());
        expect(err.message == kix("missing required field: prompt"));
    };

    "subagent_params_session_alias_and_flags"_test = [] {
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("p"));
        params.values["session"] = ValueElement::make_string(kix("s-1"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        params.values["close_session"] = ValueElement::make_bool(false);
        params.values["return_history"] = ValueElement::make_bool(true);
        params.values["history_format"] =
            ValueElement::make_string(kix("summary"));
        params.values["inherit_context"] = ValueElement::make_bool(true);
        subagent_params out;
        expect(!parse_subagent_params(&params, out).failed());
        expect(*out.session_id == kix("s-1"));
        expect(!out.run_in_background);
        expect(!out.close_session);
        expect(out.return_history);
        expect(out.history_format == kix("summary"));
        expect(out.inherit_context);
    };

    "subagent_params_bad_history_format"_test = [] {
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("p"));
        params.values["history_format"] =
            ValueElement::make_string(kix("yaml"));
        subagent_params out;
        const tool_error err = parse_subagent_params(&params, out);
        expect(err.failed());
        expect(sv_of(err.message).find("'json', 'markdown' or 'summary'") !=
               std::string::npos);
    };

    "subagent_params_context_files_and_data"_test = [] {
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("p"));
        ValueElement::Array files;
        files.push_back(ValueElement::make_string(kix("a.txt")));
        files.push_back(ValueElement::make_string(kix("b.txt")));
        params.values["context_files"] =
            ValueElement::make_array(std::move(files));
        kimix::shared_ptr<ToolParams> data(new ToolParams());
        data->values["k"] = ValueElement::make_int(7);
        params.values["context_data"] =
            ValueElement::make_object(std::move(data));
        subagent_params out;
        expect(!parse_subagent_params(&params, out).failed());
        expect(out.context_files.size() == 2u);
        expect(out.context_files[1] == kix("b.txt"));
        expect(out.context_data_json.has_value());
        expect(sv_of(*out.context_data_json).find("\"k\": 7") !=
               std::string::npos);
    };

    "subagent_params_context_files_must_be_strings"_test = [] {
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("p"));
        ValueElement::Array files;
        files.push_back(ValueElement::make_int(1));
        params.values["context_files"] =
            ValueElement::make_array(std::move(files));
        subagent_params out;
        const tool_error err = parse_subagent_params(&params, out);
        expect(err.failed());
        expect(err.message == kix("context_files must be a list of strings"));
    };

    "send_message_params"_test = [] {
        ToolParams params;
        params.values["question"] = ValueElement::make_string(kix("hi"));
        params.values["id"] = ValueElement::make_string(kix("sub-1"));
        send_message_params out;
        expect(!parse_send_message_params(&params, out).failed());
        expect(out.message == kix("hi"));
        expect(*out.subagent_id == kix("sub-1"));
    };

    "send_message_params_requires_message"_test = [] {
        ToolParams params;
        send_message_params out;
        const tool_error err = parse_send_message_params(&params, out);
        expect(err.failed());
        expect(err.message == kix("missing required field: message"));
    };

    "list_agents_params_default_scope"_test = [] {
        list_agents_params out;
        expect(!parse_list_agents_params(nullptr, out).failed());
        expect(out.scope == kix("children"));
        ToolParams params;
        params.values["scope"] = ValueElement::make_string(kix("descendants"));
        expect(!parse_list_agents_params(&params, out).failed());
        expect(out.scope == kix("descendants"));
    };

    "interrupt_params_aliases"_test = [] {
        ToolParams by_session;
        by_session.values["session"] = ValueElement::make_string(kix("a"));
        interrupt_agent_params out;
        expect(!parse_interrupt_params(&by_session, out).failed());
        expect(out.agent_id == kix("a"));
        ToolParams by_session_id;
        by_session_id.values["session_id"] =
            ValueElement::make_string(kix("b"));
        expect(!parse_interrupt_params(&by_session_id, out).failed());
        expect(out.agent_id == kix("b"));
        ToolParams none;
        const tool_error err = parse_interrupt_params(&none, out);
        expect(err.failed());
    };

    // -----------------------------------------------------------------------
    // Subagent Tool wrapper
    // -----------------------------------------------------------------------
    "subagent_requires_a_runner"_test = [] {
        Session session;
        session.session_id = "parent";
        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("task"));
        tool(&params);
        expect(has(tool.serialized_result(), "unsupported"));
        expect(has(tool.serialized_result(),
                   "native subagent requires an injected runner"));
    };

    "subagent_recursion_guard"_test = [] {
        Session session;
        session.is_sub_agent = true;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_runner runner;
        session.agents->runner = runner.fn();
        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("task"));
        tool(&params);
        expect(has(tool.serialized_result(),
                   "Recursive sub-agent call detected"));
        expect(has(tool.serialized_result(), "sub-agent recursively"));
        expect(runner.calls->empty());
    };

    "subagent_foreground_success"_test = [] {
        Session session;
        session.session_id = "parent";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_clock clock;
        session.agents->now = clock.fn();
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "the answer";
        conversation_turn turn;
        turn.role = "assistant";
        turn.content = "the answer";
        turn.type = "text";
        runner.result->turns = {turn};
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("compute 6*7"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        params.values["description"] =
            ValueElement::make_string(kix("quick math"));
        tool(&params);

        expect(runner.calls->size() == 1u);
        expect(runner.calls->at(0).prompt == kix("compute 6*7"));
        expect(!runner.calls->at(0).resume);
        expect(runner.calls->at(0).close_session);
        expect(!runner.calls->at(0).background);
        expect(has(tool.serialized_result(), "Session ID: "));
        expect(has(tool.serialized_result(), "the answer"));
        expect(has(tool.serialized_result(), "Sub-agent task completed"));
        expect(has(tool.serialized_result(), "\"status\":\"closed\""));
        expect(has(tool.serialized_result(), "\"turn_count\":1"));
        // close_session defaults to true -> the entry leaves the store.
        expect(session.agents->size() == 0u);
    };

    "subagent_keeps_the_session_when_close_session_is_false"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_clock clock;
        session.agents->now = clock.fn();
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "done";
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("task"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        params.values["close_session"] = ValueElement::make_bool(false);
        tool(&params);

        expect(has(tool.serialized_result(), "\"status\":\"continued\""));
        expect(session.agents->size() == 1u);
        const kimix::vector<agent_list_item> items =
            session.agents->list_active();
        expect(items.size() == 1u);
        expect(items[0].state == kix("completed"));
    };

    "subagent_failure_saves_the_prompt"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_files files;
        session.agents->read_file = files.reader();
        session.agents->save_prompt = files.saver();
        fake_runner runner;
        runner.result->ok = false;
        runner.result->error = "provider exploded";
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("a task"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        tool(&params);

        const std::string json = json_of(tool.serialized_result());
        expect(json.find("provider exploded") != std::string::npos);
        expect(json.find("[prompt saved to ") != std::string::npos);
        expect(json.find("Retry with subagent(prompt=@") != std::string::npos);
        expect(json.find("sub-agent task failed") != std::string::npos);
        expect(json.find("(no text output)") != std::string::npos);
        expect(files.saved->size() == 1u);
        // The failed session is closed and dropped.
        expect(session.agents->size() == 0u);
    };

    "subagent_awaiting_response"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_clock clock;
        session.agents->now = clock.fn();
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "which mode should I use?";
        runner.result->pending_question = kimix::string("which mode?");
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("task"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        params.values["return_history"] = ValueElement::make_bool(true);
        params.values["history_format"] =
            ValueElement::make_string(kix("summary"));
        tool(&params);

        expect(has(tool.serialized_result(),
                   "Sub-agent is awaiting a response"));
        expect(has(tool.serialized_result(),
                   "\"status\":\"awaiting_response\""));
        expect(has(tool.serialized_result(), "\"question\":\"which mode?\""));
        expect(session.agents->size() == 1u);
        const kimix::vector<agent_list_item> items =
            session.agents->list_active();
        expect(items[0].state == kix("awaiting_response"));
    };

    "subagent_resolves_at_path_prompts"_test = [] {
        Session session;
        session.work_dir = "/work";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_files files;
        files.add("/work/task.md", "the real task");
        session.agents->read_file = files.reader();
        session.agents->save_prompt = files.saver();
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "ok";
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("@task.md"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        tool(&params);
        expect(runner.calls->at(0).prompt == kix("the real task"));
    };

    "subagent_missing_prompt_file"_test = [] {
        Session session;
        session.work_dir = "/work";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_files files;
        session.agents->read_file = files.reader();
        session.agents->save_prompt = files.saver();
        fake_runner runner;
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("@gone.md"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        tool(&params);
        expect(has(tool.serialized_result(),
                   "prompt file not found: gone.md"));
        // Python parity (agent_goldens.inc, "context_and_prompt_files"
        // step 2): Agent.__call__ returns str(exc) unchanged - the prompt is
        // only saved to the shared temp folder when the *run* fails, not when
        // @prompt cannot be resolved.
        expect(!has(tool.serialized_result(), "\"prompt_file\""));
        expect(!has(tool.serialized_result(), "prompt saved to"));
        expect(runner.calls->empty());
    };

    "subagent_builds_the_context_block"_test = [] {
        Session session;
        session.work_dir = "/work";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_files files;
        files.add("/work/ctx.txt", "CONTEXT");
        session.agents->read_file = files.reader();
        session.agents->save_prompt = files.saver();
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "ok";
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("the task"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        ValueElement::Array ctx;
        ctx.push_back(ValueElement::make_string(kix("ctx.txt")));
        params.values["context_files"] =
            ValueElement::make_array(std::move(ctx));
        tool(&params);
        const std::string prompt = sv_of(runner.calls->at(0).prompt);
        expect(prompt.find("<context>") == 0) << prompt;
        expect(prompt.find("<file path='ctx.txt'>") != std::string::npos);
        expect(prompt.find("CONTEXT") != std::string::npos);
        expect(prompt.size() > 12u &&
               prompt.compare(prompt.size() - 8, 8, "the task") == 0)
            << prompt;
    };

    "subagent_drains_queued_messages_into_the_prompt"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "ok";
        session.agents->runner = runner.fn();
        // A message queued for a session id we are about to resume.
        session.agents->put(make_entry("resume-me", 1.0, 1.0));
        session.agents->register_session("resume-me");
        session.agents->queue_pending_message("resume-me", "queued note");

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("next task"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        params.values["session"] =
            ValueElement::make_string(kix("resume-me"));
        tool(&params);
        expect(runner.calls->at(0).resume);
        expect(runner.calls->at(0).session_id == kix("resume-me"));
        const std::string prompt = sv_of(runner.calls->at(0).prompt);
        expect(prompt.find("next task") == 0);
        expect(prompt.find("<pending-messages>") != std::string::npos);
        expect(prompt.find("1. queued note") != std::string::npos);
        expect(session.agents->pending_message_count("resume-me") == 0u);
    };

    "subagent_injects_the_deprecated_response"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "ok";
        session.agents->runner = runner.fn();
        agent_entry entry = make_entry("q-1", 1.0, 1.0, "awaiting_response");
        entry.pending_question = kimix::string("which mode?");
        session.agents->put(entry);
        session.agents->register_session("q-1");

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("the task"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        params.values["session"] = ValueElement::make_string(kix("q-1"));
        params.values["response"] = ValueElement::make_string(kix("fast"));
        tool(&params);
        const std::string prompt = sv_of(runner.calls->at(0).prompt);
        expect(prompt.find(
                   "The parent agent responded to your question (which "
                   "mode?):") == 0)
            << prompt;
        expect(prompt.find("Now, regarding your original task: the task") !=
               std::string::npos);
    };

    "subagent_offloads_a_huge_prompt"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_files files;
        session.agents->read_file = files.reader();
        session.agents->save_prompt = files.saver();
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "ok";
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(
            kimix::string(k_prompt_offload_bytes + 10, 'z'));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        tool(&params);
        const std::string prompt = sv_of(runner.calls->at(0).prompt);
        expect(prompt.find("Please read the task from `") == 0) << prompt;
        expect(prompt.find("` and execute it.") != std::string::npos);
        expect(files.saved->size() == 1u);
    };

    "subagent_background_returns_immediately_and_joins"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_clock clock;
        session.agents->now = clock.fn();
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "background result";
        session.agents->runner = runner.fn();

        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("bg task"));
        // run_in_background defaults to true.
        tool(&params);

        expect(has(tool.serialized_result(), "Session ID: "));
        expect(has(tool.serialized_result(), "Sub-agent task started"));
        expect(has(tool.serialized_result(), "\"status\":\"running\""));
        expect(session.agents->size() == 1u);
        const kimix::vector<agent_list_item> items =
            session.agents->list_active();
        expect(items.size() == 1u);
        expect(items[0].state == kix("running"));
        // The worker settles and the result becomes available.
        subagent_run_result settled;
        expect(session.agents->join_run(items[0].session_id, settled));
        expect(settled.ok);
        expect(settled.output == kix("background result"));
        expect(runner.calls->size() == 1u);
        expect(runner.calls->at(0).background);
    };

    "subagent_background_can_be_interrupted"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        // A runner that blocks until it is cancelled, proving the cancel flag
        // reaches the worker.
        auto gate = kimix::shared_ptr<std::atomic<int>>(new std::atomic<int>(0));
        session.agents->runner =
            [gate](const subagent_request &req) {
                subagent_run_result out;
                while (req.cancel != nullptr && !req.cancel->load() &&
                       gate->load() == 0) {
                    std::this_thread::sleep_for(
                        std::chrono::milliseconds(2));
                }
                out.ok = false;
                out.cancelled = (req.cancel != nullptr && req.cancel->load());
                out.error = out.cancelled ? "cancelled" : "gate opened";
                return out;
            };
        Subagent tool(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("slow task"));
        tool(&params);
        const kimix::vector<agent_list_item> items =
            session.agents->list_active();
          expect(items.size() == 1u);
          expect(session.agents->is_running(items[0].session_id));
          expect(session.agents->request_cancel(items[0].session_id));
          subagent_run_result settled;
          expect(session.agents->join_run(items[0].session_id, settled));
          expect(settled.cancelled);
          expect(settled.error == kix("cancelled"));
      };
      "interrupt_agent_close_does_not_deadlock_steer_draining_runner"_test = [] {
          // Regression (found by new_tools_e2e turn D): a real sub-agent
          // runner polls the steer queue - a REGISTRY call - between steps.
          // The old close() joined the worker WHILE HOLDING the registry
          // lock, so interrupt_agent deadlocked against the worker's
          // drain_steer poll (and reset the agent_run before joining,
          // dangling req.cancel/finished).
          Session session;
          kimix::shared_ptr<agent_registry> reg(new agent_registry());
          session.agents = reg;
          reg->runner =
              [reg](const subagent_request &req) {
                  subagent_run_result out;
                  int64_t spins = 0;
                  while (req.cancel != nullptr && !req.cancel->load() &&
                         spins < 10000000) {
                      (void)reg->drain_steer(req.session_id);
                      std::this_thread::yield();
                      ++spins;
                  }
                  out.ok = false;
                  out.cancelled =
                      (req.cancel != nullptr && req.cancel->load());
                  out.error = out.cancelled ? kix("cancelled")
                                            : kix("spin bound reached");
                  return out;
              };
          Subagent start(&session);
          ToolParams params;
          params.values["prompt"] = ValueElement::make_string(kix("slow task"));
          start(&params); // background by default
          const kimix::vector<agent_list_item> items = reg->list_active();
          expect(items.size() == 1u);
          const kimix::string id = items[0].session_id;
          // Interrupt on a separate thread so a regression (deadlock) fails
          // the test instead of hanging the whole suite.
          std::atomic<bool> closed{false};
          std::thread closer([&] {
              InterruptAgent tool(&session);
              ToolParams ip;
              ip.values["agent_id"] = ValueElement::make_string(id);
              tool(&ip);
              closed.store(true);
          });
          const auto deadline =
              std::chrono::steady_clock::now() + std::chrono::seconds(10);
          while (!closed.load() &&
                 std::chrono::steady_clock::now() < deadline) {
              std::this_thread::sleep_for(std::chrono::milliseconds(5));
          }
          const bool finished_in_time = closed.load();
          if (!finished_in_time) {
              closer.detach(); // leave the deadlocked thread behind; fail
          }
          expect(finished_in_time);
          if (finished_in_time) {
              closer.join();
              // close() parks the settled result: the cancelled run stays
              // observable through run_finished/join_run after the session
              // bookkeeping is dropped.
              expect(reg->run_finished(id));
              subagent_run_result settled;
              expect(reg->join_run(id, settled));
              expect(settled.cancelled);
          }
      };

    "subagent_history_formats"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_runner runner;
        runner.result->ok = true;
        runner.result->output = "ok";
        conversation_turn call;
        call.role = "assistant";
        call.type = "tool_call";
        conversation_turn text;
        text.role = "assistant";
        text.type = "text";
        text.content = "final";
        runner.result->turns = {call, text};
        session.agents->runner = runner.fn();

        // markdown
        Subagent md(&session);
        ToolParams params;
        params.values["prompt"] = ValueElement::make_string(kix("t"));
        params.values["run_in_background"] = ValueElement::make_bool(false);
        params.values["return_history"] = ValueElement::make_bool(true);
        params.values["history_format"] =
            ValueElement::make_string(kix("markdown"));
        md(&params);
        expect(has(md.serialized_result(), "### Turn 1:"));

        // summary
        Subagent sum(&session);
        params.values["history_format"] =
            ValueElement::make_string(kix("summary"));
        sum(&params);
        expect(has(sum.serialized_result(),
                   "Sub-agent made 1 tool call(s) with 0 result(s), and "
                   "produced 1 text response(s) (5 total characters)."));

        // json (default): a real array of turn objects
        Subagent js(&session);
        params.values.erase("history_format");
        js(&params);
        expect(has(js.serialized_result(), "\"conversation_history\":["));
        expect(has(js.serialized_result(), "\"role\":\"assistant\""));
    };

    // -----------------------------------------------------------------------
    // SendMessage Tool wrapper
    // -----------------------------------------------------------------------
    "send_message_delivers_to_a_running_target"_test = [] {
        Session session;
        session.session_id = "parent";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        auto gate = kimix::shared_ptr<std::atomic<int>>(new std::atomic<int>(0));
        session.agents->runner = [gate](const subagent_request &req) {
            subagent_run_result out;
            while (req.cancel != nullptr && !req.cancel->load() &&
                   gate->load() == 0) {
                std::this_thread::sleep_for(std::chrono::milliseconds(2));
            }
            out.ok = true;
            out.output = "done";
            return out;
        };
        // Start a background sub-agent so there IS a running target.
        Subagent starter(&session);
        ToolParams start;
        start.values["prompt"] = ValueElement::make_string(kix("long task"));
        starter(&start);
        const kimix::vector<agent_list_item> items =
            session.agents->list_active();
        expect(items.size() == 1u);
        const kimix::string child_id = items[0].session_id;
        expect(session.agents->is_running(child_id));

        SendMessageTool tool(&session);
        ToolParams params;
        params.values["message"] = ValueElement::make_string(kix("more work"));
        params.values["subagent_id"] = ValueElement::make_string(child_id);
        tool(&params);
        expect(has(tool.serialized_result(),
                   "Message delivered to agent '"));
        expect(has(tool.serialized_result(), "Message sent"));
        const kimix::vector<kimix::string> steered =
            session.agents->drain_steer(child_id);
        expect(steered.size() == 1u);
        expect(steered[0] == kix("Message from agent 'parent':\nmore work"));
        session.agents->request_cancel(child_id);
        subagent_run_result settled;
        session.agents->join_run(child_id, settled);
    };

    "send_message_queues_for_an_idle_target"_test = [] {
        Session session;
        session.session_id = "parent";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        session.agents->put(make_entry("idle-1", 1.0, 1.0));
        session.agents->register_session("idle-1");

        SendMessageTool tool(&session);
        ToolParams params;
        params.values["message"] = ValueElement::make_string(kix("ping"));
        params.values["subagent_id"] =
            ValueElement::make_string(kix("idle-1"));
        tool(&params);
        expect(has(tool.serialized_result(), "Message queued"));
        expect(has(tool.serialized_result(), "Agent 'idle-1' is not running"));
        expect(session.agents->pending_message_count("idle-1") == 1u);
        const kimix::vector<kimix::string> queued =
            session.agents->drain_pending_messages("idle-1");
        expect(queued[0] == kix("Message from agent 'parent':\nping"));
    };

    "send_message_queues_for_a_closed_session"_test = [] {
        Session session;
        session.session_id = "parent";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        SendMessageTool tool(&session);
        ToolParams params;
        params.values["message"] = ValueElement::make_string(kix("ping"));
        params.values["subagent_id"] =
            ValueElement::make_string(kix("closed-1"));
        tool(&params);
        expect(has(tool.serialized_result(), "Message queued"));
        expect(has(tool.serialized_result(), "session closed or idle"));
        expect(session.agents->pending_message_count("closed-1") == 1u);
    };

    "send_message_rejects_self_messaging"_test = [] {
        Session session;
        session.session_id = "me";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        session.agents->register_session("me");
        SendMessageTool tool(&session);
        ToolParams params;
        params.values["message"] = ValueElement::make_string(kix("hi"));
        params.values["subagent_id"] = ValueElement::make_string(kix("me"));
        tool(&params);
        expect(has(tool.serialized_result(), "Cannot message yourself."));
        expect(has(tool.serialized_result(), "Self message rejected"));
    };

    "send_message_unresolvable_target"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        SendMessageTool tool(&session);
        ToolParams params;
        params.values["message"] = ValueElement::make_string(kix("hi"));
        tool(&params);
        expect(has(tool.serialized_result(),
                   "Cannot resolve target agent: no active sub-agents to "
                   "message"));
        expect(has(tool.serialized_result(), "Target agent not found"));
    };

    "send_message_sub_agent_targets_parent"_test = [] {
        Session session;
        session.session_id = "child";
        session.is_sub_agent = true;
        session.parent_session_id = "parent";
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        session.agents->register_session("parent");
        session.agents->put(make_entry("parent", 1.0, 1.0));
        SendMessageTool tool(&session);
        ToolParams params;
        params.values["message"] = ValueElement::make_string(kix("need input"));
        // No subagent_id: a sub-agent always targets its parent.
        tool(&params);
        // The parent is registered but not running -> queued.
        expect(has(tool.serialized_result(), "Message queued"));
        expect(session.agents->pending_message_count("parent") == 1u);
        const kimix::vector<kimix::string> queued =
            session.agents->drain_pending_messages("parent");
        expect(queued[0] == kix("Message from agent 'child':\nneed input"));
    };

    // -----------------------------------------------------------------------
    // ListAgents Tool wrapper
    // -----------------------------------------------------------------------
    "list_agents_tool_output"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        fake_clock clock;
        session.agents->now = clock.fn();
        agent_entry entry = make_entry("sub-1", 10.0, 20.0, "running");
        entry.total_turns = 3;
        session.agents->put(entry);

        ListAgents tool(&session);
        ToolParams params;
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("Listed active subagents") != std::string::npos);
        expect(json.find("\\\"session_id\\\": \\\"sub-1\\\"") !=
               std::string::npos)
            << json;
        expect(json.find("\\\"total_turns\\\": 3") != std::string::npos);
        expect(json.find("\\\"state\\\": \\\"running\\\"") !=
               std::string::npos);
        expect(json.find("\"scope\":\"children\"") != std::string::npos);
    };

    "list_agents_empty_store"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        ListAgents tool(&session);
        tool(nullptr);
        expect(has(tool.serialized_result(), "[]"));
    };

    // -----------------------------------------------------------------------
    // InterruptAgent Tool wrapper
    // -----------------------------------------------------------------------
    "interrupt_agent_unknown_session"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        InterruptAgent tool(&session);
        ToolParams params;
        params.values["agent_id"] = ValueElement::make_string(kix("ghost"));
        tool(&params);
        expect(has(tool.serialized_result(), "Session not found"));
    };

    "interrupt_agent_closes_and_removes"_test = [] {
        Session session;
        session.agents = kimix::shared_ptr<agent_registry>(new agent_registry());
        session.agents->put(make_entry("sub-9", 1.0, 1.0));
        session.agents->register_session("sub-9");
        session.agents->queue_pending_message("sub-9", "kept for later");

        InterruptAgent tool(&session);
        ToolParams params;
        params.values["agent_id"] = ValueElement::make_string(kix("sub-9"));
        tool(&params);
        expect(has(tool.serialized_result(), "Session sub-9 closed."));
        expect(has(tool.serialized_result(), "Session closed"));
        expect(session.agents->get("sub-9") == nullptr);
        expect(!session.agents->has_session("sub-9"));
        // Queued messages survive the close (they are listed on resume).
        expect(session.agents->pending_message_count("sub-9") == 1u);
    };

    // -----------------------------------------------------------------------
    // Session-scoped registry attachment
    // -----------------------------------------------------------------------
    "session_registry_is_lazily_created_and_shared"_test = [] {
        Session session;
        session.session_id = "owner";
        expect(session.agents == nullptr);
        agent_registry &first = session_registry(&session);
        expect(session.agents != nullptr);
        agent_registry &second = session_registry(&session);
      expect(&first == &second);
          expect(first.owner_session_id == kix("owner"));
      };

      // -----------------------------------------------------------------------
      // Python-derived golden replay (scripts/gen_agent_goldens.py)
      // -----------------------------------------------------------------------
      "agent_goldens_replay"_test = [] {
          kimix::unique_ptr<Session> holder;
          agent_registry *reg = nullptr;
          kimix::shared_ptr<double> clock(new double(1000.0));
          kimix::shared_ptr<std::vector<std::string>> saved(
              new std::vector<std::string>());
          kimix::shared_ptr<std::vector<kimix::string>> prompts(
              new std::vector<kimix::string>());
          kimix::shared_ptr<std::atomic<bool>> gate(
              new std::atomic<bool>(true));
          std::vector<std::string> fresh; // ids this run allocated, in order
          size_t checked_rows = 0;
          for (size_t row = 0; row < kAgentGoldenCount; ++row) {
              const agent_golden_step &g = kAgentGoldens[row];
              const std::string where = std::string(g.case_name) + " step " +
                                        std::to_string(g.step) + " (" +
                                        std::string(g.tool) + ")";
              auto chk = [&](bool ok, const std::string &what) {
                  expect(ok) << (where + ": " + what);
              };
              auto chkd = [&](const agl::diff &d, const std::string &what) {
                  expect(d.ok) << (where + ": " + what + " -> " + d.why);
              };
              ++checked_rows;

              if (g.step == 0) {
                  holder = kimix::unique_ptr<Session>(new Session());
                  Session &sess = *holder;
                  sess.session_id = kix(g.caller_id);
                  sess.is_sub_agent = g.is_sub_agent;
                  sess.parent_session_id = kix(g.parent_session_id);
                  reg = &session_registry(&sess);
                  reg->now = [clock]() { return *clock; };
                  saved->clear();
                  prompts->clear();
                  fresh.clear();
                  *gate = true;

                  // Injected file table: the reference reads the very same
                  // bytes from the real file system (CWD-relative).
                  ValueElement files_el;
                  const bool files_ok = agl::parse_value(g.files, files_el);
                  chk(files_ok, "files table parse");
                  kimix::shared_ptr<std::vector<std::pair<std::string, std::string>>>
                      table(new std::vector<std::pair<std::string, std::string>>());
                  if (files_ok && files_el.is_array()) {
                      for (const ValueElement &entry : files_el.as_array()) {
                          if (!entry.is_array() || entry.as_array().size() != 2u) {
                              chk(false, "files entry shape");
                              continue;
                          }
                          table->emplace_back(
                              agl::text_of(&entry.as_array()[0]),
                              agl::text_of(&entry.as_array()[1]));
                      }
                  }
                  reg->read_file = [table](kimix::string_view path,
                                           kimix::string &out) {
                      const std::string want(path.data(), path.size());
                      for (const auto &entry : *table) {
                          if (entry.first == want) {
                              out = kix(entry.second);
                              return true;
                          }
                      }
                      return false;
                  };
                  reg->save_prompt = [saved](kimix::string_view text,
                                             kimix::string_view ext) {
                      const std::string name =
                          ".kimix_cache/prompt_" +
                          std::to_string(saved->size()) +
                          std::string(ext.data(), ext.size());
                      saved->push_back(std::string(text.data(), text.size()));
                      return kix(name);
                  };

                  ValueElement live_el;
                  chk(agl::parse_value(g.pre_live, live_el), "pre_live parse");
                  if (live_el.is_array()) {
                      for (const ValueElement &id : live_el.as_array()) {
                          reg->register_session(id.as_string());
                      }
                  }
                  ValueElement entries_el;
                  chk(agl::parse_value(g.pre_entries, entries_el),
                      "pre_entries parse");
                  if (entries_el.is_array()) {
                      for (const ValueElement &el : entries_el.as_array()) {
                          const ToolParams *o = el.as_object();
                          if (o == nullptr) {
                              chk(false, "pre_entries entry shape");
                              continue;
                          }
                          agent_entry entry;
                          entry.session_id =
                              kimix::string(agl::text_of(o->get_exact("id")));
                          double v = 0.0;
                          if (agl::as_double(o->get_exact("created_at"), v)) {
                              entry.created_at = v;
                          }
                          if (agl::as_double(o->get_exact("last_accessed"), v)) {
                              entry.last_accessed = v;
                          }
                          int64_t turns = 0;
                          if (agl::as_int(o->get_exact("total_turns"), turns)) {
                              entry.total_turns = static_cast<int32_t>(turns);
                          }
                          entry.state =
                              kimix::string(agl::text_of(o->get_exact("state")));
                          const ValueElement *active = o->get_exact("is_active");
                          entry.is_active = (active == nullptr ||
                                             (active->is_bool() && active->as_bool()));
                          const ValueElement *pq =
                              o->get_exact("pending_question");
                          if (agl::is_str(pq)) {
                              entry.pending_question = pq->as_string();
                          }
                          reg->put(entry);
                      }
                  }
                  ValueElement pending_el;
                  chk(agl::parse_value(g.pre_pending, pending_el),
                      "pre_pending parse");
                  if (const ToolParams *pend = pending_el.as_object()) {
                      for (const auto &kv : pend->values) {
                          if (!kv.second.is_array()) {
                              continue;
                          }
                          for (const ValueElement &msg : kv.second.as_array()) {
                              reg->queue_pending_message(
                                  kimix::string_view(kv.first.data(),
                                                     kv.first.size()),
                                  msg.as_string());
                          }
                      }
                  }
                  if (g.pre_run[0] != '\0') {
                      *gate = false;
                      kimix::shared_ptr<std::atomic<bool>> g2 = gate;
                      reg->runner = [g2](const subagent_request &req) {
                          while (!g2->load() &&
                                 !(req.cancel != nullptr && req.cancel->load())) {
                              std::this_thread::sleep_for(
                                  std::chrono::milliseconds(1));
                          }
                          subagent_run_result out;
                          out.ok = true;
                          out.output = kix("(gated background run)");
                          out.cancelled =
                              (req.cancel != nullptr && req.cancel->load());
                          return out;
                      };
                      subagent_request req;
                      req.prompt = kix("(gated background run)");
                      chk(reg->start_background(kix(g.pre_run), req),
                          "gated background run started");
                  }
              }

              // ---- one step -------------------------------------------------
              *clock = g.now;
              saved->clear(); // the golden records per-step saves only
              subagent_run_result scripted;
              if (g.runner[0] != '\0') {
                  chk(agl::load_runner(g.runner, scripted),
                      "runner payload parse");
              }
              kimix::shared_ptr<subagent_run_result> scripted_ptr(
                  new subagent_run_result(std::move(scripted)));
              prompts->clear();
              reg->runner = [prompts, scripted_ptr](const subagent_request &req) {
                  prompts->push_back(req.prompt);
                  return *scripted_ptr;
              };

              const std::string args_text = agl::expand(g.args, fresh);
              ToolParams args;
              chk(agl::parse_object(args_text.c_str(), args), "args parse");
              Session &sess = *holder;
              kimix::vector<char> out_json;
              if (std::strcmp(g.tool, "subagent") == 0) {
                  Subagent tool(&sess);
                  tool(&args);
                  tool.result_json(out_json);
              } else if (std::strcmp(g.tool, "send_message") == 0) {
                  SendMessageTool tool(&sess);
                  tool(&args);
                  tool.result_json(out_json);
              } else if (std::strcmp(g.tool, "list_agents") == 0) {
                  ListAgents tool(&sess);
                  tool(&args);
                  tool.result_json(out_json);
              } else if (std::strcmp(g.tool, "interrupt_agent") == 0) {
                  InterruptAgent tool(&sess);
                  tool(&args);
                  tool.result_json(out_json);
              } else {
                  chk(false, "unknown tool in golden");
              }
              ToolParams result;
              {
                  const kimix::string text(out_json.data(), out_json.size());
                  kimix::string err;
                  chk(result.try_deserialize(
                          kimix::span<char const>(text.data(), text.size()), err),
                      "result parse: " + sv_of(err));
              }
              if (g.pre_run[0] != '\0') {
                  *gate = true; // release the gated worker before the next case
              }

              // A subagent step that named no session makes the tool allocate
              // one; the golden token <NEWn> stands for it.
              const bool is_subagent = std::strcmp(g.tool, "subagent") == 0;
              bool explicit_session = false;
              if (is_subagent) {
                  for (const char *key : {"session_id", "session"}) {
                      const ValueElement *el = args.get_exact(key);
                      if (agl::is_str(el) && !el->as_string().empty()) {
                          explicit_session = true;
                      }
                  }
              }
              if (is_subagent && !explicit_session) {
                  const ValueElement *ex = result.get_exact("extras");
                  const ToolParams *exo =
                      (ex != nullptr && ex->is_object()) ? ex->as_object()
                                                         : nullptr;
                  const ValueElement *sid =
                      (exo != nullptr) ? exo->get_exact("session_id")
                                       : nullptr;
                  if (agl::is_str(sid)) {
                      fresh.push_back(agl::text_of(sid));
                  }
              }

              // ---- result envelope -----------------------------------------
              const ValueElement *ok_el = result.get_exact("ok");
              chk(ok_el != nullptr && ok_el->is_bool() &&
                      ok_el->as_bool() == !g.is_error,
                  "ok (") ;
              chk(agl::text_of(result.get_exact("status")) == g.status,
                  "status " + agl::text_of(result.get_exact("status")) +
                      " != " + g.status);
              if (!g.validation_error) {
                  chk(agl::mask(agl::text_of(result.get_exact("output")),
                                fresh) == g.output_cpp,
                      "output \"" +
                          agl::clip(agl::mask(
                              agl::text_of(result.get_exact("output")), fresh)) +
                          "\" != \"" + agl::clip(g.output_cpp) + "\"");
                  chk(agl::mask(agl::text_of(result.get_exact("message")),
                                fresh) == g.message_cpp,
                      "message \"" +
                          agl::clip(agl::mask(
                              agl::text_of(result.get_exact("message")), fresh)) +
                          "\" != \"" + agl::clip(g.message_cpp) + "\"");
                  chk(agl::text_of(result.get_exact("brief")) == g.brief,
                      "brief \"" + agl::text_of(result.get_exact("brief")) +
                          "\" != \"" + g.brief + "\"");
              }
              const ValueElement *got_extras = result.get_exact("extras");
              chk((got_extras != nullptr && got_extras->is_object()) ==
                      g.has_extras,
                  "extras presence");
              if (g.has_extras) {
                  ValueElement want_extras;
                  chk(agl::parse_value(g.extras, want_extras),
                      "golden extras parse");
                  const ToolParams *got_obj =
                      (got_extras != nullptr && got_extras->is_object())
                          ? got_extras->as_object()
                          : nullptr;
                  if (got_obj != nullptr) {
                      chkd(agl::compare_extras(got_obj, want_extras, fresh),
                           "extras");
                  }
              }

              // ---- registry state ------------------------------------------
              ToolParams state;
              chk(agl::parse_object(g.state, state), "golden state parse");
              const kimix::vector<agent_list_item> items =
                  reg->list_active();
              const std::string got_list = agl::mask(
                  sv_of(list_active_json(
                      kimix::span<const agent_list_item>(items))),
                  fresh);
              chk(got_list == agl::text_of(state.get_exact("list")),
                  "state.list \"" + agl::clip(got_list) + "\" != \"" +
                      agl::clip(agl::text_of(state.get_exact("list"))) +
                      "\"");

              // live ids (the golden may carry a hand-transcribed override).
              std::vector<std::string> want_live;
              const char *live_json = (g.state_cpp_live[0] != '\0')
                                          ? g.state_cpp_live
                                          : nullptr;
              ValueElement live_override;
              const ValueElement *live_el =
                  state.get_exact("live");
              if (live_json != nullptr && agl::parse_value(live_json, live_override)) {
                  live_el = &live_override;
              }
              if (live_el != nullptr && live_el->is_array()) {
                  for (const ValueElement &v : live_el->as_array()) {
                      want_live.push_back(agl::expand(agl::text_of(&v), fresh));
                  }
              }
              std::vector<std::string> ids;
              auto add_id = [&ids](const std::string &id) {
                  if (!id.empty()) {
                      ids.push_back(id);
                  }
              };
              const ValueElement *entries_el = state.get_exact("entries");
              const ToolParams *want_entries =
                  (entries_el != nullptr) ? entries_el->as_object() : nullptr;
              if (want_entries != nullptr) {
                  for (const auto &kv : want_entries->values) {
                      add_id(agl::expand(
                          std::string(kv.first.data(), kv.first.size()), fresh));
                  }
              }
              for (const std::string &id : want_live) {
                  add_id(id);
              }
              std::vector<std::string> want_pending_ids;
              const char *pending_json = (g.state_cpp_pending[0] != '\0')
                                             ? g.state_cpp_pending
                                             : nullptr;
              ValueElement pending_override;
              const ValueElement *pending_el = state.get_exact("pending");
              if (pending_json != nullptr &&
                  agl::parse_value(pending_json, pending_override)) {
                  pending_el = &pending_override;
              }
              const ToolParams *want_pending =
                  (pending_el != nullptr) ? pending_el->as_object() : nullptr;
              if (want_pending != nullptr) {
                  for (const auto &kv : want_pending->values) {
                      add_id(agl::expand(
                          std::string(kv.first.data(), kv.first.size()), fresh));
                  }
              }
              for (const std::string &id : ids) {
                  const bool want =
                      std::find(want_live.begin(), want_live.end(), id) !=
                      want_live.end();
                  chk(reg->has_session(kix(id)) == want,
                      "live(" + id + ") " +
                          (reg->has_session(kix(id)) ? "true" : "false") +
                          " != " + (want ? "true" : "false"));
              }
              if (want_entries != nullptr) {
                  for (const auto &kv : want_entries->values) {
                      const std::string key(kv.first.data(), kv.first.size());
                      const std::string id = agl::expand(key, fresh);
                      const agent_entry *got = reg->get(id);
                      if (kv.second.is_null()) {
                          chk(got == nullptr, "entry " + key + " should be absent");
                          continue;
                      }
                      const ToolParams *want = kv.second.as_object();
                      if (want == nullptr) {
                          chk(false, "entry " + key + " golden is not an object");
                          continue;
                      }
                      if (got == nullptr) {
                          chk(false, "entry " + key + " is missing");
                          continue;
                      }
                      double created = 0.0;
                      double accessed = 0.0;
                      int64_t turns = -1;
                      agl::as_double(want->get_exact("created_at"), created);
                      agl::as_double(want->get_exact("last_accessed"), accessed);
                      agl::as_int(want->get_exact("total_turns"), turns);
                      chk(got->created_at == created,
                          "entry " + key + ".created_at");
                      chk(got->last_accessed == accessed,
                          "entry " + key + ".last_accessed");
                      chk(got->total_turns == static_cast<int32_t>(turns),
                          "entry " + key + ".total_turns");
                      chk(sv_of(got->state) ==
                              agl::text_of(want->get_exact("state")),
                          "entry " + key + ".state \"" + sv_of(got->state) +
                              "\" != \"" +
                              agl::text_of(want->get_exact("state")) + "\"");
                      const ValueElement *active = want->get_exact("is_active");
                      const bool want_active =
                          (active == nullptr) ||
                          (active->is_bool() && active->as_bool());
                      chk(got->is_active == want_active,
                          "entry " + key + ".is_active");
                      const ValueElement *pq = want->get_exact("pending_question");
                      const bool want_pq = agl::is_str(pq);
                      chk(got->pending_question.has_value() == want_pq,
                          "entry " + key + ".pending_question presence");
                      if (want_pq && got->pending_question.has_value()) {
                          chk(sv_of(*got->pending_question) == agl::text_of(pq),
                              "entry " + key + ".pending_question");
                      }
                  }
              }
              // The golden keys pending entries by the (possibly tokenised)
              // id; expand them once so the lookup matches `ids`.
              std::vector<std::pair<std::string, size_t>> want_counts;
              if (want_pending != nullptr) {
                  for (const auto &kv : want_pending->values) {
                      const size_t count = kv.second.is_array()
                                               ? kv.second.as_array().size()
                                               : 0u;
                      want_counts.emplace_back(
                          agl::expand(
                              std::string(kv.first.data(), kv.first.size()),
                              fresh),
                          count);
                  }
              }
              for (const std::string &id : ids) {
                  size_t want_count = 0;
                  for (const auto &entry : want_counts) {
                      if (entry.first == id) {
                          want_count = entry.second;
                      }
                  }
                  chk(reg->pending_message_count(id) == want_count,
                      "pending_message_count(" + id + ") " +
                          std::to_string(reg->pending_message_count(id)) +
                          " != " + std::to_string(want_count));
              }

              // prompts the sub-agent runner received (the host boundary).
              std::vector<std::string> want_prompts;
              const char *prompts_json = (g.state_cpp_prompts[0] != '\0')
                                             ? g.state_cpp_prompts
                                             : nullptr;
              ValueElement prompts_override;
              const ValueElement *prompts_el = state.get_exact("prompts");
              if (prompts_json != nullptr &&
                  agl::parse_value(prompts_json, prompts_override)) {
                  prompts_el = &prompts_override;
              }
              if (prompts_el != nullptr && prompts_el->is_array()) {
                  for (const ValueElement &v : prompts_el->as_array()) {
                      want_prompts.push_back(agl::text_of(&v));
                  }
              }
              chk(prompts->size() == want_prompts.size(),
                  "runner prompt count " + std::to_string(prompts->size()) +
                      " != " + std::to_string(want_prompts.size()));
              const size_t prompt_count =
                  prompts->size() < want_prompts.size() ? prompts->size()
                                                       : want_prompts.size();
              for (size_t i = 0; i < prompt_count; ++i) {
                  chk(agl::mask(sv_of((*prompts)[i]), fresh) == want_prompts[i],
                      "runner prompt[" + std::to_string(i) + "] \"" +
                          agl::clip(agl::mask(sv_of((*prompts)[i]), fresh)) +
                          "\" != \"" + agl::clip(want_prompts[i]) + "\"");
              }

              // prompts saved to the shared temp folder.
              std::vector<std::string> want_saved;
              const ValueElement *saved_el = state.get_exact("saved");
              if (saved_el != nullptr && saved_el->is_array()) {
                  for (const ValueElement &v : saved_el->as_array()) {
                      want_saved.push_back(agl::text_of(&v));
                  }
              }
              chk(saved->size() == want_saved.size(),
                  "saved prompt count " + std::to_string(saved->size()) +
                      " != " + std::to_string(want_saved.size()));
              const size_t saved_count = saved->size() < want_saved.size()
                                             ? saved->size()
                                             : want_saved.size();
              for (size_t i = 0; i < saved_count; ++i) {
                  chk((*saved)[i] == want_saved[i],
                      "saved prompt[" + std::to_string(i) + "] \"" +
                          agl::clip((*saved)[i]) + "\" != \"" +
                          agl::clip(want_saved[i]) + "\"");
              }
          }
          expect(checked_rows == kAgentGoldenCount) << "golden row count";
      };
  }
