// Test for builtin_tools/job_output_tool.h
// (namespace kimix::builtin_tools::job_output).
//
// Covers:
// - parse_params: defaults, job_id|task_id + wait|block + timeout|timeout_ms
//   aliases, the legacy timeout_ms -> max(1, ms // 1000) conversion, the
//   deprecated kill:true -> action='kill' normalization, action validation,
//   the [1, 7200] timeout bounds, and non-string rejection
// - task_kind / display_kind: split("_")[0] with the "unknown" vs "task" default
// - format_task_list: byte-exact markdown table + "No running tasks."
// - not_found_message: "No running task" vs the available-tasks list
// - format_elapsed_cell (list table, {:.1f}) vs format_duration /
//   format_elapsed_suffix / format_elapsed_tag / append_elapsed
//   (common.py, ELAPSED_REPORT_MINIMUM_SECONDS = 1.0, m/h forms, idempotence)
// - build_get_output_text: processed vs "(no output)", the still-running
//   prefix, the export branch, original/rtk suffixes, wait_matched line and
//   the completion banner ordering
// - record_finished_task / get_finished_task: bounded LRU history
// - JobOutput Tool wrapper with an injected TaskSource: list mode (explicit
//   action and the job_id-omitted default), get with/without wait, the
//   not-found path, the non-zero-exit failure path, kill, output_path export,
//   the finished-task history (a second read of a completed job is served from
//   it, not "not found") and the status_text field
// - golden replay: every case of tests/unit/builtin_tools/job_output_goldens.inc
//   (64 calls of the *real* kimi-agent TaskOutput, generated by
//   scripts/gen_job_output_goldens.py) must reproduce its output/message/brief/
//   error flag, its id removals and its leftover registry byte for byte
//
// The reference appends no "[status: ...]" text to any response (the tool
// description promises one, nothing implements it); the port reports the state
// through the machine-readable `status_text` field only.
//
// All test logic lives in main() scope; no file-scope static registrations.
#include "ut/ut.hpp"
#include <core/kimix_core.h>
#include "builtin_tools/job_output_tool.h"
#include "builtin_tools/process_runner.h"
#include <string>
#include <vector>

#include <string>
#include <vector>

// Python-derived golden vectors for the whole Tool wrapper (regenerate with
// scripts/gen_job_output_goldens.py); included at global scope like the other
// tools' goldens.
#include "job_output_goldens.inc"

using namespace boost::ut;
using namespace boost::ut::literals;
using namespace kimix::builtin_tools;
using namespace kimix::builtin_tools::job_output;

namespace {

kimix::string kix(std::string_view sv) {
    return kimix::string(sv.data(), sv.size());
}

std::string sv_of(const kimix::string &s) {
    return std::string(s.data(), s.size());
}

std::string json_of(const kimix::vector<char> &buf) {
    return std::string(buf.data(), buf.size());
}

bool has(const kimix::vector<char> &buf, std::string_view needle) {
    return json_of(buf).find(std::string(needle)) != std::string::npos;
}

// Value of `"key":"..."` in the compact tool JSON, unescaped.  Only a real key
// is accepted (the match must start the object or follow a comma), so a needle
// appearing inside another field's value cannot fool the extraction.
bool json_str_field(std::string_view json, std::string_view key,
                    std::string &out) {
    const std::string needle = "\"" + std::string(key) + "\":\"";
    size_t pos = 0;
    while ((pos = json.find(needle, pos)) != std::string_view::npos) {
        if (pos > 0 && json[pos - 1] != '{' && json[pos - 1] != ',') {
            pos += needle.size();
            continue;
        }
        out.clear();
        size_t i = pos + needle.size();
        while (i < json.size()) {
            const char c = json[i];
            if (c == '\\') {
                if (i + 1 >= json.size()) {
                    return false;
                }
                const char e = json[i + 1];
                switch (e) {
                case 'n': out.push_back('\n'); i += 2; break;
                case 't': out.push_back('\t'); i += 2; break;
                case 'r': out.push_back('\r'); i += 2; break;
                case 'b': out.push_back('\b'); i += 2; break;
                case 'f': out.push_back('\f'); i += 2; break;
                case '"': out.push_back('"'); i += 2; break;
                case '\\': out.push_back('\\'); i += 2; break;
                case '/': out.push_back('/'); i += 2; break;
                case 'u': {
                    if (i + 5 >= json.size()) {
                        return false;
                    }
                    unsigned cp = 0;
                    for (size_t k = 0; k < 4; ++k) {
                        const char h = json[i + 2 + k];
                        cp <<= 4;
                        if (h >= '0' && h <= '9') {
                            cp |= static_cast<unsigned>(h - '0');
                        } else if (h >= 'a' && h <= 'f') {
                            cp |= static_cast<unsigned>(h - 'a' + 10);
                        } else {
                            cp |= static_cast<unsigned>(h - 'A' + 10);
                        }
                    }
                    if (cp < 0x80u) {
                        out.push_back(static_cast<char>(cp));
                    } else if (cp < 0x800u) {
                        out.push_back(static_cast<char>(0xC0u | (cp >> 6)));
                        out.push_back(static_cast<char>(0x80u | (cp & 0x3Fu)));
                    } else {
                        out.push_back(static_cast<char>(0xE0u | (cp >> 12)));
                        out.push_back(
                            static_cast<char>(0x80u | ((cp >> 6) & 0x3Fu)));
                        out.push_back(static_cast<char>(0x80u | (cp & 0x3Fu)));
                    }
                    i += 6;
                    break;
                }
                default:
                    return false;
                }
                continue;
            }
            if (c == '"') {
                return true;
            }
            out.push_back(c);
            ++i;
        }
        return false;
    }
    return false;
}

bool json_bool_field(std::string_view json, std::string_view key, bool &out) {
    const std::string t = "\"" + std::string(key) + "\":true";
    const std::string f = "\"" + std::string(key) + "\":false";
    if (json.find(t) != std::string_view::npos) {
        out = true;
        return true;
    }
    if (json.find(f) != std::string_view::npos) {
        out = false;
        return true;
    }
    return false;
}

// Space separated ids, the golden table's encoding of a list.
std::string join_ids(const kimix::vector<kimix::string> &ids) {
    std::string out;
    for (size_t i = 0; i < ids.size(); ++i) {
        if (i != 0) {
            out += ' ';
        }
        out += sv_of(ids[i]);
    }
    return out;
}

// The display path the golden generator baked into its output_path cases
// (relative to the process CWD, so the vector stays machine independent).
constexpr const char *EXPORT_PATH_FOR_TESTS =
    ".kimix_cache/job_output_goldens_out.txt";

// A scripted task source: the tests drive it instead of spawning processes.
struct fake_source {
    kimix::vector<job_task> tasks;
    kimix::vector<kimix::string> removed;
    kimix::vector<kimix::string> killed;
    int wait_calls = 0;
    kimix::string last_wait_pattern;
    int64_t last_wait_timeout_ms = 0;
    bool wait_matched = false;

    TaskSource make() {
        // `this` outlives the tool call in every test below.
        TaskSource src;
        src.list = [this]() { return tasks; };
        src.read = [this](kimix::string_view id, job_task &out) {
            for (const job_task &t : tasks) {
                if (t.task_id == id) {
                    out = t;
                    return true;
                }
            }
            return false;
        };
        src.wait = [this](kimix::string_view id, kimix::string_view pattern,
                          int64_t timeout_ms, bool &matched, job_task &out) {
            ++wait_calls;
            last_wait_pattern = kimix::string(pattern);
            last_wait_timeout_ms = timeout_ms;
            matched = wait_matched;
            for (const job_task &t : tasks) {
                if (t.task_id == id) {
                    out = t;
                    return true;
                }
            }
            return false;
        };
        src.kill = [this](kimix::string_view id, job_task &out) {
            for (const job_task &t : tasks) {
                if (t.task_id == id) {
                    killed.emplace_back(id);
                    out = t;
                    out.exited = true;
                    return true;
                }
            }
            return false;
        };
        src.remove = [this](kimix::string_view id) { removed.emplace_back(id); };
        return src;
    }
};

job_task make_task(std::string_view id, bool exited, int64_t exit_code,
                   std::string_view output, double elapsed) {
    job_task t;
    t.task_id = kix(id);
    t.exists = true;
    t.exited = exited;
    if (exited) {
        t.exit_code = exit_code;
    }
    t.output = kix(output);
    t.elapsed_seconds = elapsed;
    t.has_elapsed = true;
    return t;
}

} // namespace

int main(int argc, char *argv[]) {
    boost::ut::detail::cfg::parse_arg_with_fallback(
        argc, const_cast<const char **>(argv));

    // -----------------------------------------------------------------------
    // parse_params
    // -----------------------------------------------------------------------
    "params_defaults"_test = [] {
        job_output_params out;
        expect(!parse_params(nullptr, out).failed());
        expect(!out.job_id.has_value());
        expect(out.action == kix("get"));
        expect(!out.wait);
        expect(out.timeout == 60_i);
        expect(!out.output_path.has_value());
        expect(!out.wait_for_pattern.has_value());
    };

    "params_task_id_alias"_test = [] {
        ToolParams params;
        params.values["task_id"] = ValueElement::make_string(kix("bash_1"));
        job_output_params out;
        expect(!parse_params(&params, out).failed());
        expect(out.job_id.has_value());
        expect(*out.job_id == kix("bash_1"));
    };

    "params_job_id_wins_over_alias"_test = [] {
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("a"));
        params.values["task_id"] = ValueElement::make_string(kix("b"));
        job_output_params out;
        expect(!parse_params(&params, out).failed());
        expect(*out.job_id == kix("a"));
    };

    "params_block_alias"_test = [] {
        ToolParams params;
        params.values["block"] = ValueElement::make_bool(true);
        job_output_params out;
        expect(!parse_params(&params, out).failed());
        expect(out.wait);
    };

    "params_legacy_timeout_ms"_test = [] {
        ToolParams params;
        params.values["timeout_ms"] = ValueElement::make_int(45000);
        job_output_params out;
        expect(!parse_params(&params, out).failed());
        expect(out.timeout == 45_i);
    };

    "params_legacy_timeout_ms_floors_at_one"_test = [] {
        ToolParams params;
        params.values["timeout_ms"] = ValueElement::make_int(250);
        job_output_params out;
        expect(!parse_params(&params, out).failed());
        expect(out.timeout == 1_i); // max(1, 250 // 1000)
    };

    "params_timeout_wins_over_timeout_ms"_test = [] {
        ToolParams params;
        params.values["timeout"] = ValueElement::make_int(7);
        params.values["timeout_ms"] = ValueElement::make_int(45000);
        job_output_params out;
        expect(!parse_params(&params, out).failed());
        expect(out.timeout == 7_i);
    };

    "params_timeout_bounds"_test = [] {
        ToolParams params;
        params.values["timeout"] = ValueElement::make_int(0);
        job_output_params out;
        const tool_error low = parse_params(&params, out);
        expect(low.failed());
        expect(sv_of(low.message).find("greater than or equal to 1") !=
               std::string::npos);
        params.values["timeout"] = ValueElement::make_int(7201);
        const tool_error high = parse_params(&params, out);
        expect(high.failed());
        expect(sv_of(high.message).find("less than or equal to 7200") !=
               std::string::npos);
        params.values["timeout"] = ValueElement::make_int(7200);
        expect(!parse_params(&params, out).failed());
        expect(out.timeout == 7200_i);
    };

    "params_kill_flag_normalizes_action"_test = [] {
        ToolParams params;
        params.values["kill"] = ValueElement::make_bool(true);
        params.values["job_id"] = ValueElement::make_string(kix("bash_1"));
        job_output_params out;
        expect(!parse_params(&params, out).failed());
        expect(out.action == kix("kill"));
    };

    "params_bad_action"_test = [] {
        ToolParams params;
        params.values["action"] = ValueElement::make_string(kix("destroy"));
        job_output_params out;
        const tool_error err = parse_params(&params, out);
        expect(err.failed());
        expect(sv_of(err.message).find("'get', 'list' or 'kill'") !=
               std::string::npos);
    };

    "params_bad_job_id_type"_test = [] {
        ToolParams params;
        params.values["job_id"] = ValueElement::make_int(3);
        job_output_params out;
        const tool_error err = parse_params(&params, out);
        expect(err.failed());
        expect(err.message == kix("job_id must be a string"));
    };

    // -----------------------------------------------------------------------
    // task_kind / elapsed formatting
    // -----------------------------------------------------------------------
    "task_kind_splits_on_underscore"_test = [] {
        expect(task_kind("bash_1") == kix("bash"));
        expect(task_kind("run_git") == kix("run"));
        expect(task_kind("python_2") == kix("python"));
        expect(task_kind("noue") == kix("unknown"));
        expect(task_kind("_leading") == kix(""));
        expect(task_kind("") == kix("unknown"));
    };

    "display_kind_defaults_to_task"_test = [] {
        // `job_id.split("_")[0] if job_id else "task"` -- note the different
        // default from the list table's task_kind().
        expect(display_kind("bash_1") == kix("bash"));
        expect(display_kind("noue") == kix("task"));
        expect(display_kind("") == kix("task"));
    };

    "elapsed_cell_formatting"_test = [] {
        expect(format_elapsed_cell(std::nullopt) == kix("-"));
        expect(format_elapsed_cell(0.0) == kix("-")); // falsy in Python
        expect(format_elapsed_cell(1.25) == kix("1.2s"));
        expect(format_elapsed_cell(1.35) == kix("1.4s"));
        expect(format_elapsed_cell(12.0) == kix("12.0s"));
        // The list table keeps the plain one-decimal form even past a minute
        // (only the tag/suffix use _format_elapsed_seconds).
        expect(format_elapsed_cell(95.0) == kix("95.0s"));
    };

    "format_duration_matches_python"_test = [] {
        // _format_elapsed_seconds: {:.2f}s < 60s, <m>m<ss>s < 3600s, <h>h<mm>m.
        expect(format_duration(0.0) == kix("0.00s"));
        expect(format_duration(0.5) == kix("0.50s"));
        expect(format_duration(59.999) == kix("60.00s")); // still < 60
        expect(format_duration(60.0) == kix("1m00s"));
        expect(format_duration(65.0) == kix("1m05s"));
        expect(format_duration(95.0) == kix("1m35s"));
        expect(format_duration(3599.0) == kix("59m59s"));
        expect(format_duration(3600.0) == kix("1h00m"));
        expect(format_duration(3725.0) == kix("1h02m"));
        // _coerce_seconds rejects negatives, NaN and Inf.
        expect(format_duration(-1.0).empty());
        expect(format_duration(std::nan("")).empty());
        expect(format_duration(std::numeric_limits<double>::infinity()).empty());
    };

    "elapsed_suffix_minimum_and_units"_test = [] {
        // _elapsed_suffix is gated by ELAPSED_REPORT_MINIMUM_SECONDS = 1.0.
        expect(format_elapsed_suffix(std::nullopt).empty());
        expect(format_elapsed_suffix(0.0).empty());
        expect(format_elapsed_suffix(0.999).empty());
        expect(format_elapsed_suffix(1.0) == kix(" (1.00s)"));
        expect(format_elapsed_suffix(3.14159) == kix(" (3.14s)"));
        expect(format_elapsed_suffix(95.0) == kix(" (1m35s)"));
        expect(format_elapsed_suffix(3725.0) == kix(" (1h02m)"));
        expect(kill_message_suffix(95.0) == kix(" (1m35s)"));
    };

    "append_elapsed_semantics"_test = [] {
        // Empty message -> the suffix without its leading space ("(3.50s)").
        expect(append_elapsed("", 3.5) == kix("(3.50s)"));
        expect(append_elapsed("", 95.0) == kix("(1m35s)"));
        expect(append_elapsed("", 0.5).empty());
        expect(append_elapsed("", std::nullopt).empty());
        expect(append_elapsed("boom", 3.5) == kix("boom (3.50s)"));
        expect(append_elapsed("boom", 0.5) == kix("boom"));
        // Idempotent (common.py _ELAPSED_SUFFIX_RE: "(\\d+(\\.\\d+)?(s|m\\d+s|
        // h\\d+m))" with optional whitespace, anchored at the end).
        expect(append_elapsed("boom (1.23s)", 3.5) == kix("boom (1.23s)"));
        expect(append_elapsed("boom (1m05s)", 3.5) == kix("boom (1m05s)"));
        expect(append_elapsed("boom (1h02m)", 3.5) == kix("boom (1h02m)"));
        expect(append_elapsed("(7s)", 3.5) == kix("(7s)"));
        expect(append_elapsed("(1h2m)", 3.5) == kix("(1h2m)"));
        expect(append_elapsed("(1m5s)", 3.5) == kix("(1m5s)"));
        // \s* before ")" and at the very end (Python's $ also matches before a
        // trailing newline, which \s*$ already consumes).
        expect(append_elapsed("x (1.23s)  ", 3.5) == kix("x (1.23s)  "));
        expect(append_elapsed("x(1.23s)\n", 3.5) == kix("x(1.23s)\n"));
        // Non-suffixes are NOT treated as one.
        expect(append_elapsed("boom ( 1.23 s )", 3.5) ==
               kix("boom ( 1.23 s ) (3.50s)"));
        expect(append_elapsed("boom (1.2.3s)", 3.5) == kix("boom (1.2.3s) (3.50s)"));
        expect(append_elapsed("boom (1.23s", 3.5) == kix("boom (1.23s (3.50s)"));
        expect(append_elapsed("boom (1.23s) tail", 3.5) ==
               kix("boom (1.23s) tail (3.50s)"));
        expect(append_elapsed("boom (s)", 3.5) == kix("boom (s) (3.50s)"));
        expect(append_elapsed("boom ()", 3.5) == kix("boom () (3.50s)"));
        expect(append_elapsed("boom (1m)", 3.5) == kix("boom (1m) (3.50s)"));
    };

    "completed_banner_formatting"_test = [] {
        expect(format_completed_banner(std::nullopt).empty());
        expect(format_completed_banner(0.5).empty()); // below the 1s minimum
        expect(format_completed_banner(1.005) ==
               kix("\n[Process completed in 1.00s]"));
        // 12.345 is not exactly representable; both CPython and std::format
        // round the exact binary value half-to-even to 12.35.
        expect(format_completed_banner(12.345) ==
               kix("\n[Process completed in 12.35s]"));
        expect(format_completed_banner(95.0) ==
               kix("\n[Process completed in 1m35s]"));
        expect(format_completed_banner(3725.0) ==
               kix("\n[Process completed in 1h02m]"));
    };

    "display_path_normalization"_test = [] {
        expect(normalize_display_path("C:\\tmp\\out.txt") ==
               kix("C:/tmp/out.txt"));
        expect(normalize_display_path("/tmp/out.txt") == kix("/tmp/out.txt"));
        expect(exported_message("C:\\a\\b.txt") ==
               kix("output exported to file `C:/a/b.txt`"));
    };

    "status_suffix_contract"_test = [] {
        expect(status_suffix("running") == kix("\n[status: running]"));
        expect(status_suffix("completed") == kix("\n[status: completed]"));
    };

    // -----------------------------------------------------------------------
    // format_task_list / not_found_message
    // -----------------------------------------------------------------------
    "task_list_empty_message"_test = [] {
        expect(format_task_list(kimix::span<const task_row>()) ==
               kix("No running tasks."));
    };

    "task_list_markdown_table"_test = [] {
        const kimix::vector<task_row> rows = {
            make_task_row("bash_1", true, 2.5),
            make_task_row("run_git", false, 0.0),
            make_task_row("nounderscore", true, std::nullopt),
        };
        const std::string table = sv_of(
            format_task_list(kimix::span<const task_row>(rows)));
        const std::string expected =
            "| Task ID | Kind | Status | Elapsed |\n"
            "|---------|------|--------|---------|\n"
            "| `bash_1` | bash | running | 2.5s |\n"
            "| `run_git` | run | completed | - |\n"
            "| `nounderscore` | unknown | running | - |";
        expect(table == expected) << "got:\n" << table;
    };

    "not_found_messages"_test = [] {
        expect(not_found_message("bash_9", kimix::span<const kimix::string>()) ==
               kix("No running task"));
        const kimix::vector<kimix::string> available = {kix("bash_1"),
                                                        kix("run_git")};
        expect(not_found_message(
                   "bash_9", kimix::span<const kimix::string>(available)) ==
               kix("Task 'bash_9' not found. Available tasks: [bash_1, "
                   "run_git]"));
    };

    // -----------------------------------------------------------------------
    // build_get_output_text
    // -----------------------------------------------------------------------
    "get_output_text_plain"_test = [] {
        get_output_fields f;
        f.processed = "hello";
        f.task_alive = true;
        f.job_id = "bash_1";
        expect(build_get_output_text(f) == kix("hello"));
    };

    "get_output_text_no_output_fallback"_test = [] {
        get_output_fields f;
        f.task_alive = false;
        f.job_id = "bash_1";
        expect(build_get_output_text(f) == kix("(no output)"));
    };

    "get_output_text_export_branch"_test = [] {
        get_output_fields f;
        f.processed = "hello";
        f.task_alive = true;
        f.output_path = kimix::string("C:\\out.txt");
        f.job_id = "bash_1";
        expect(build_get_output_text(f) ==
               kix("`bash_1` is still running, call `job_output` again, "
                   "output exported to file `C:/out.txt`"));
        // A finished task drops the still-running prefix.
        f.task_alive = false;
        expect(build_get_output_text(f) ==
               kix("output exported to file `C:/out.txt`"));
    };

    "get_output_text_suffix_ordering"_test = [] {
        get_output_fields f;
        f.processed = "body";
        f.task_alive = false;
        f.original_path = kimix::string("C:\\orig.txt");
        f.has_formatter = true;
        f.wait_matched = false;
        f.elapsed_seconds = 2.5;
        f.job_id = "bash_1";
        const std::string text = sv_of(build_get_output_text(f));
        const std::string expected =
            "body\n"
            "[original output exported to: C:/orig.txt]\n"
            "wait_matched: false\n"
            "[Process completed in 2.50s]";
        expect(text == expected) << "got:\n" << text;
        // Without a registered formatter the rtk wording is used.
        f.has_formatter = false;
        expect(sv_of(build_get_output_text(f)).find(
                   "[rtk output exported to: C:/orig.txt]") !=
               std::string::npos);
    };

    "get_output_text_wait_matched_true"_test = [] {
        get_output_fields f;
        f.processed = "x";
        f.task_alive = true;
        f.wait_matched = true;
        f.job_id = "t";
        expect(sv_of(build_get_output_text(f)).find("\nwait_matched: true") !=
               std::string::npos);
    };

    // -----------------------------------------------------------------------
    // JobOutput Tool wrapper (injected TaskSource)
    // -----------------------------------------------------------------------
    "tool_requires_native_io_without_source"_test = [] {
        Session session; // native_io false, no injected source
        JobOutput tool(&session);
        ToolParams params;
        params.values["action"] = ValueElement::make_string(kix("list"));
        tool(&params);
        expect(has(tool.serialized_result(), "unsupported"));
    };

    "tool_list_action"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_1", false, 0, "", 1.5),
                      make_task("run_git", true, 0, "done", 3.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["action"] = ValueElement::make_string(kix("list"));
        tool(&params);
        expect(has(tool.serialized_result(), "| Task ID | Kind | Status | Elapsed |"));
        expect(has(tool.serialized_result(), "`bash_1` | bash | running | 1.5s"));
        expect(has(tool.serialized_result(),
                   "`run_git` | run | completed | 3.0s"));
        expect(has(tool.serialized_result(), "2 background task(s)"));
    };

    "tool_list_is_the_default_without_job_id"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_1", false, 0, "", 0.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        tool(nullptr); // no params at all -> action=get, job_id absent
        expect(has(tool.serialized_result(), "| Task ID | Kind | Status |"));
        expect(has(tool.serialized_result(), "1 background task(s)"));
    };

    "tool_list_empty"_test = [] {
        Session session;
        fake_source fake;
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["action"] = ValueElement::make_string(kix("list"));
        tool(&params);
        expect(has(tool.serialized_result(), "No running tasks."));
        expect(has(tool.serialized_result(), "No background tasks"));
    };

    "tool_get_running_task"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_1", false, 0, "partial output", 1.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_1"));
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("partial output") != std::string::npos);
        // No "[status: ...]" suffix: the reference appends none (the status is
        // reported through the machine-readable status_text field only).
        expect(json.find("[status:") == std::string::npos);
        expect(json.find("\"status_text\":\"running\"") != std::string::npos);
        expect(json.find("\"kind\":\"bash\"") != std::string::npos);
        // ToolOk(..., display_block=...) discards the "Task output retrieved"
        // brief, so the reference's `result.brief` is empty here.
        expect(json.find("\"brief\":\"\"") != std::string::npos);
        expect(json.find("Task output retrieved") == std::string::npos);
        // A live job carries no sub-process duration in its message.
        expect(json.find("\"message\":\"\"") != std::string::npos);
        // A finished task is dropped from the registry; a running one is not.
        expect(fake.removed.empty());
    };

    "tool_get_completed_task_removes_id"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("run_git", true, 0, "all done", 2.5)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("run_git"));
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("all done") != std::string::npos);
        expect(json.find("[status:") == std::string::npos);
        expect(json.find("\"status_text\":\"completed\"") != std::string::npos);
        expect(json.find("[Process completed in 2.50s]") != std::string::npos);
        expect(json.find("\"message\":\"(2.50s)\"") != std::string::npos);
        expect(fake.removed.size() == 1u);
        expect(fake.removed[0] == kix("run_git"));
    };

    "tool_get_no_output_fallback"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_2", true, 0, "", 0.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_2"));
        tool(&params);
        expect(has(tool.serialized_result(), "(no output)"));
    };

    "tool_get_failed_task"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("run_make", true, 2, "boom", 7.25)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("run_make"));
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("\"ok\":false") != std::string::npos);
        expect(json.find("Task 'run_make' failed") != std::string::npos);
        // _append_elapsed(message, elapsed) -> "(7.25s)" (2 decimals below a
        // minute, not the list table's {:.1f}).
        expect(json.find("\"message\":\"(7.25s)\"") != std::string::npos)
            << "message was: " << json.c_str();
        expect(json.find("boom") != std::string::npos);
        expect(json.find("[status:") == std::string::npos);
        expect(json.find("\"status_text\":\"completed\"") != std::string::npos);
    };

    "tool_get_not_found_lists_available"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_1", false, 0, "", 0.0),
                      make_task("bash_2", false, 0, "", 0.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("nope"));
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("Task 'nope' not found. Available tasks: [bash_1, "
                         "bash_2]") != std::string::npos);
        expect(json.find("not_found") != std::string::npos);
    };

    "tool_get_not_found_no_tasks"_test = [] {
        Session session;
        fake_source fake;
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("nope"));
        tool(&params);
        expect(has(tool.serialized_result(), "No running task"));
    };

    "tool_get_strips_the_id"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_5", false, 0, "x", 0.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("  bash_5  "));
        tool(&params);
        expect(has(tool.serialized_result(), "\"status_text\":\"running\""));
        expect(!has(tool.serialized_result(), "not found"));
    };

    "tool_wait_passes_timeout_and_pattern"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_6", false, 0, "ready now", 0.0)};
        fake.wait_matched = true;
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_6"));
        params.values["wait"] = ValueElement::make_bool(true);
        params.values["timeout"] = ValueElement::make_int(12);
        params.values["wait_for_pattern"] =
            ValueElement::make_string(kix("ready"));
        tool(&params);
        expect(fake.wait_calls == 1);
        expect(fake.last_wait_pattern == kix("ready"));
        expect(fake.last_wait_timeout_ms == 12000_i);
        expect(has(tool.serialized_result(), "wait_matched: true"));
    };

    "tool_wait_without_pattern_waits_for_exit"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_7", true, 0, "final", 1.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_7"));
        params.values["block"] = ValueElement::make_bool(true);
        tool(&params);
        expect(fake.wait_calls == 1);
        expect(fake.last_wait_pattern.empty());
        // No pattern -> no wait_matched line at all.
        expect(!has(tool.serialized_result(), "wait_matched"));
    };

    "tool_invalid_wait_pattern"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_8", false, 0, "", 0.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_8"));
        params.values["wait_for_pattern"] =
            ValueElement::make_string(kix("([unclosed"));
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("Invalid wait_for_pattern: ") != std::string::npos);
        expect(json.find("Invalid pattern") != std::string::npos);
        // The pattern is validated even when wait is false, so no read.
        expect(fake.wait_calls == 0);
    };

    "tool_kill_success"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_9", false, 0, "killed output", 4.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_9"));
        params.values["action"] = ValueElement::make_string(kix("kill"));
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("Task 'bash_9' killed") != std::string::npos);
        expect(json.find("killed output") != std::string::npos);
        expect(fake.killed.size() == 1u);
        expect(fake.removed.size() == 1u);
    };

    "tool_kill_non_zero_exit"_test = [] {
        Session session;
        fake_source fake;
        job_task failed = make_task("run_x", false, 0, "err", 6.0);
        failed.exit_code = 3; // killed with a non-zero code
        fake.tasks = {failed};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("run_x"));
        params.values["kill"] = ValueElement::make_bool(true); // deprecated flag
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("killed (non-zero exit)") != std::string::npos);
        expect(json.find("\"message\":\"(6.00s)\"") != std::string::npos);
    };

    "tool_kill_missing_id"_test = [] {
        Session session;
        fake_source fake;
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["action"] = ValueElement::make_string(kix("kill"));
        tool(&params);
        expect(has(tool.serialized_result(),
                   "task_id is required for action='kill'."));
        expect(has(tool.serialized_result(), "Missing task_id"));
    };

    "tool_kill_not_found"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_1", false, 0, "", 0.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("ghost"));
        params.values["action"] = ValueElement::make_string(kix("kill"));
        tool(&params);
        expect(has(tool.serialized_result(),
                   "Task 'ghost' not found. Available tasks: [bash_1]"));
    };

    "tool_output_path_export"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_10", false, 0, "exported body", 0.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        const kimix::string out_path =
            kimix::to_string(kimix::filesystem::temp_directory_path() /
                             kimix::filesystem::path("jo_test_export.txt"));
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_10"));
        params.values["output_path"] = ValueElement::make_string(out_path);
        tool(&params);
        const std::string json = json_of(tool.serialized_result());
        expect(json.find("output exported to file `") != std::string::npos);
        expect(json.find("is still running, call `job_output` again") !=
               std::string::npos);
        // The raw output landed in the file.
        std::FILE *f = std::fopen(sv_of(out_path).c_str(), "rb");
        expect(f != nullptr);
        if (f != nullptr) {
            char buf[64] = {0};
            const size_t n = std::fread(buf, 1, sizeof(buf) - 1, f);
            std::fclose(f);
            expect(std::string(buf, n).find("exported body") !=
                   std::string::npos);
        }
        std::remove(sv_of(out_path).c_str());
    };

    "tool_process_output_hook"_test = [] {
        Session session;
        fake_source fake;
        fake.tasks = {make_task("bash_11", true, 0, "raw", 1.0)};
        JobOutput tool(&session);
        tool.source = fake.make();
        tool.process_output = [](kimix::string_view text) {
            return kimix::string("[filtered]") + kimix::string(text);
        };
        ToolParams params;
        params.values["job_id"] = ValueElement::make_string(kix("bash_11"));
        tool(&params);
        expect(has(tool.serialized_result(), "[filtered]raw"));
    };

      "tool_description_is_capped"_test = [] {
          Session session;
          fake_source fake;
          fake.tasks = {make_task("bash_12", false, 0,
                                  kimix::string(400, 'q'), 0.0)};
          JobOutput tool(&session);
          tool.source = fake.make();
          ToolParams params;
          params.values["job_id"] = ValueElement::make_string(kix("bash_12"));
          tool(&params);
          const std::string json = json_of(tool.serialized_result());
          // The display-block description mirrors output_text[:200].
          const size_t at = json.find("\"description\":\"");
          expect(at != std::string::npos);
          if (at != std::string::npos) {
              const size_t end = json.find('"', at + 15);
              expect(end - (at + 15) <= 200u);
          }
      };

      // --- proc::sanitize_utf8 (captured-output UTF-8 hardening) ------------
      // Regression: a Chinese-locale timeout.exe emits GBK bytes into the
      // captured output; ToolParams::serialize (yyjson) rejects invalid UTF-8
      // and the whole tool result became a hard "tool threw" error.
      "sanitize_utf8_ascii_passthrough"_test = [] {
          expect(proc::sanitize_utf8("") == kimix::string());
          expect(proc::sanitize_utf8("hello world") ==
                 kimix::string("hello world"));
      };
      "sanitize_utf8_valid_multibyte_preserved"_test = [] {
          const kimix::string in = "h\xC3\xA9llo \xE4\xB8\xAD"; // héllo 中
          expect(proc::sanitize_utf8(in) == in);
          const kimix::string in2 = "\xF0\x9F\x98\x80\xC3\xA9"; // 😀 é
          expect(proc::sanitize_utf8(in2) == in2);
      };
      "sanitize_utf8_gbk_bytes_become_replacement"_test = [] {
          // The exact GBK bytes ("错误") captured from timeout.exe in the e2e.
          const kimix::string in = "\xB4\xED\xCE\xF3";
          const kimix::string want =
              "\xEF\xBF\xBD\xEF\xBF\xBD\xEF\xBF\xBD\xEF\xBF\xBD";
          expect(proc::sanitize_utf8(in) == want);
      };
      "sanitize_utf8_invalid_lead_between_ascii"_test = [] {
          expect(proc::sanitize_utf8("a\xFFz") ==
                 kimix::string("a\xEF\xBF\xBDz"));
      };
      "sanitize_utf8_truncated_tail_one_replacement"_test = [] {
          expect(proc::sanitize_utf8("\xE4\xB8") == kimix::string("\xEF\xBF\xBD"));
          expect(proc::sanitize_utf8("ab\xF0\x9F") ==
                 kimix::string("ab\xEF\xBF\xBD"));
      };
      "sanitize_utf8_surrogate_range_rejected"_test = [] {
          // CESU-8 surrogate encoding is not a valid scalar value: every
          // byte is rejected individually.
          expect(proc::sanitize_utf8("\xED\xA0\x80") ==
                 kimix::string("\xEF\xBF\xBD\xEF\xBF\xBD\xEF\xBF\xBD"));
      };
      "sanitize_utf8_embedded_nul_preserved"_test = [] {
          const kimix::string in("a\0\xB4z", 4);
          const kimix::string want("a\0\xEF\xBF\xBDz", 6);
          expect(proc::sanitize_utf8(in) == want);
      };

      // -----------------------------------------------------------------
      // Golden replay: every case is one reference TaskOutput.__call__
      // (scripts/gen_job_output_goldens.py + job_output_goldens.inc).  The
      // cases run in order on ONE tool instance, so the finished-task history
      // carries over exactly as it does across session calls.
      // -----------------------------------------------------------------
      "golden_replay_reference_results"_test = [] {
          Session session;
          JobOutput tool(&session);
          clear_finished_tasks();
          int checked = 0;
          for (int i = 0; i < kJoGoldenCount; ++i) {
              const jo_golden_case &g = *kJoGoldens[i];
              fake_source fake;
              for (int t = 0; t < g.task_count; ++t) {
                  const jo_golden_task &gt = g.tasks[t];
                  job_task task;
                  task.task_id = kix(gt.task_id);
                  task.exists = true;
                  task.exited = gt.exited;
                  if (gt.has_exit_code) {
                      task.exit_code = gt.exit_code;
                  }
                  task.has_elapsed = gt.has_elapsed;
                  task.elapsed_seconds = gt.elapsed;
                  task.output = kix(gt.output);
                  fake.tasks.push_back(task);
              }
              fake.wait_matched = g.wait_matched;
              tool.source = fake.make();

              ToolParams params;
              if (g.job_id != nullptr) {
                  params.values["job_id"] =
                      ValueElement::make_string(kix(g.job_id));
              }
              if (g.action != nullptr) {
                  params.values["action"] =
                      ValueElement::make_string(kix(g.action));
              }
              if (g.has_wait) {
                  params.values["wait"] = ValueElement::make_bool(g.wait);
              }
              if (g.has_timeout) {
                  params.values["timeout"] =
                      ValueElement::make_int(g.timeout);
              }
              if (g.output_path != nullptr) {
                  params.values["output_path"] =
                      ValueElement::make_string(kix(g.output_path));
              }
              if (g.wait_for_pattern != nullptr) {
                  params.values["wait_for_pattern"] =
                      ValueElement::make_string(kix(g.wait_for_pattern));
              }
              if (g.kill_flag) {
                  params.values["kill"] = ValueElement::make_bool(true);
              }
              tool(&params);

              const std::string json = json_of(tool.serialized_result());
              bool ok = false;
              std::string output;
              std::string message;
              std::string brief;
              expect(json_bool_field(json, "ok", ok)) << g.name;
              expect(json_str_field(json, "output", output)) << g.name;
              expect(json_str_field(json, "message", message)) << g.name;
              expect(json_str_field(json, "brief", brief)) << g.name;
              expect(ok == !g.is_error)
                  << g.name << ": error flag (got ok=" << ok << ")";
              expect(output == std::string(g.output))
                  << g.name << ": output\n  got: " << output
                  << "\n want: " << g.output;
              expect(message == std::string(g.message))
                  << g.name << ": message\n  got: " << message
                  << "\n want: " << g.message;
              expect(brief == std::string(g.brief))
                  << g.name << ": brief\n  got: " << brief
                  << "\n want: " << g.brief;
              // Cleanup rules: exactly these ids were dropped, in this order
              // (remove_task_id), and the registry kept the rest.
              expect(join_ids(fake.removed) == std::string(g.removed))
                  << g.name << ": removed ids";
              kimix::vector<kimix::string> left;
              for (const job_task &task : fake.tasks) {
                  bool dropped = false;
                  for (const kimix::string &id : fake.removed) {
                      if (id == task.task_id) {
                          dropped = true;
                          break;
                      }
                  }
                  if (!dropped) {
                      left.push_back(task.task_id);
                  }
              }
              expect(join_ids(left) == std::string(g.registry_after))
                  << g.name << ": registry after the call";
              // A blocking wait forwarded the timeout (ms) the reference used.
              if (g.wait_timeout_ms != 0) {
                  expect(fake.wait_calls == 1) << g.name << ": wait calls";
                  expect(fake.last_wait_timeout_ms ==
                         static_cast<int64_t>(g.wait_timeout_ms))
                      << g.name << ": wait timeout ms";
              }
              ++checked;
          }
          expect(checked == static_cast<int>(kJoGoldenCount));
          std::remove(EXPORT_PATH_FOR_TESTS);
          clear_finished_tasks();
      };

      // -----------------------------------------------------------------
      // Finished-task history (background/utils.py FinishedTask/TaskData,
      // __init__.py _get_history_output)
      // -----------------------------------------------------------------
      "history_bounded_and_lru"_test = [] {
          clear_finished_tasks();
          for (int i = 0; i < static_cast<int>(k_max_finished_tasks) + 3; ++i) {
              finished_task_record record;
              record.task_id = kimix::format("t{}", i);
              record.success = true;
              record_finished_task(record);
              expect(finished_task_count() <= k_max_finished_tasks);
          }
          expect(finished_task_count() == k_max_finished_tasks);
          // Oldest evicted first: t0..t2 are gone, the tail is retained.
          expect(!get_finished_task("t0").has_value());
          expect(!get_finished_task("t2").has_value());
          expect(get_finished_task("t3").has_value());
          expect(get_finished_task(kimix::format("t{}", k_max_finished_tasks + 2))
                     .has_value());
          // Re-recording refreshes recency and fields.
          finished_task_record rich;
          rich.task_id = "t4";
          rich.output = "updated";
          rich.processed = "updated";
          record_finished_task(rich);
          expect(get_finished_task("t4").has_value());
          expect((*get_finished_task("t4")).processed == kix("updated"));
          // The id is stripped on lookup, like the reference.
          expect(get_finished_task("  t4  ").has_value());
          expect(!get_finished_task("nope").has_value());
          expect(!get_finished_task("").has_value());
          clear_finished_tasks();
          expect(finished_task_count() == 0u);
      };

      "history_serves_second_read"_test = [] {
          // The reported regression: the first read of a finished job dropped it
          // from the registry, so the second read answered "not found".
          Session session;
          JobOutput tool(&session);
          clear_finished_tasks();
          fake_source fake;
          fake.tasks = {make_task("bash_1", true, 0, "saved output\n", 2.0)};
          tool.source = fake.make();
          ToolParams first_params;
          first_params.values["job_id"] =
              ValueElement::make_string(kix("bash_1"));
          tool(&first_params);
          expect(has(tool.serialized_result(), "saved output"));
          expect(!has(tool.serialized_result(), "finished-task history"));

          // Second read: the registry is empty now.
          fake.tasks.clear();
          tool.source = fake.make();
          ToolParams second_params;
          second_params.values["job_id"] =
              ValueElement::make_string(kix("bash_1"));
          tool(&second_params);
          const std::string json = json_of(tool.serialized_result());
          std::string output;
          expect(json_str_field(json, "output", output));
          expect(output ==
                 std::string("saved output\n\n[Process completed in 2.00s]\n"
                             "[retrieved from finished-task history]"))
              << "got: " << output;
          expect(json.find("\"ok\":true") != std::string::npos);
          expect(json.find("\"status_text\":\"completed\"") != std::string::npos);
          expect(json.find("\"kind\":\"bash\"") != std::string::npos);
          std::string message;
          expect(json_str_field(json, "message", message));
          expect(message == std::string("(2.00s)"));
          clear_finished_tasks();
      };

      "history_of_a_failed_job_is_an_error"_test = [] {
          Session session;
          JobOutput tool(&session);
          clear_finished_tasks();
          fake_source fake;
          job_task failed = make_task("fail_job", true, 1, "bad\n", 2.0);
          fake.tasks = {failed};
          tool.source = fake.make();
          ToolParams params;
          params.values["job_id"] = ValueElement::make_string(kix("fail_job"));
          tool(&params);
          fake.tasks.clear();
          tool.source = fake.make();
          tool(&params);
          const std::string json = json_of(tool.serialized_result());
          expect(json.find("\"ok\":false") != std::string::npos);
          expect(json.find("Task 'fail_job' failed") != std::string::npos);
          expect(has(tool.serialized_result(), "finished-task history"));
          clear_finished_tasks();
      };

      // -----------------------------------------------------------------
      // _kill_task output fallbacks (the two branches differ)
      // -----------------------------------------------------------------
      "kill_success_output_fallback"_test = [] {
          clear_finished_tasks();
          Session session;
          fake_source fake;
          job_task running = make_task("k0", false, 0, "", 2.0);
          running.exit_code = 0; // the killed worker reported success
          fake.tasks = {running};
          JobOutput tool(&session);
          tool.source = fake.make();
          ToolParams params;
          params.values["job_id"] = ValueElement::make_string(kix("k0"));
          params.values["action"] = ValueElement::make_string(kix("kill"));
          tool(&params);
          const std::string json = json_of(tool.serialized_result());
          expect(json.find("\"ok\":true") != std::string::npos);
          expect(json.find("\"output\":\"(no output)\"") != std::string::npos);
          expect(json.find("Task 'k0' killed\"") != std::string::npos);
          expect(json.find("[status:") == std::string::npos);
          clear_finished_tasks();
      };

      "kill_failure_output_stays_empty"_test = [] {
          clear_finished_tasks();
          Session session;
          fake_source fake;
          job_task running = make_task("k1", false, 0, "", 2.0);
          running.exit_code = 7;
          fake.tasks = {running};
          JobOutput tool(&session);
          tool.source = fake.make();
          ToolParams params;
          params.values["job_id"] = ValueElement::make_string(kix("k1"));
          params.values["action"] = ValueElement::make_string(kix("kill"));
          tool(&params);
          const std::string json = json_of(tool.serialized_result());
          expect(json.find("\"ok\":false") != std::string::npos);
          // Python: `output=processed if processed else ""` -- NOT "(no
          // output)" (that fallback belongs to the success branch only).
          expect(json.find("\"output\":\"\"") != std::string::npos);
          expect(json.find("killed (non-zero exit)") != std::string::npos);
          clear_finished_tasks();
      };

      "export_writes_the_raw_output_of_a_finished_job"_test = [] {
          clear_finished_tasks();
          Session session;
          fake_source fake;
          fake.tasks = {make_task("bash_20", true, 0, "raw\nlines\n", 1.5)};
          JobOutput tool(&session);
          tool.source = fake.make();
          const kimix::string out_path =
              kimix::to_string(kimix::filesystem::temp_directory_path() /
                               kimix::filesystem::path("jo_test_finished.txt"));
          ToolParams params;
          params.values["job_id"] = ValueElement::make_string(kix("bash_20"));
          params.values["output_path"] = ValueElement::make_string(out_path);
          tool(&params);
          const std::string json = json_of(tool.serialized_result());
          expect(json.find("output exported to file `") != std::string::npos);
          expect(json.find("is still running") == std::string::npos);
          expect(json.find("[Process completed in 1.50s]") != std::string::npos);
          std::FILE *f = std::fopen(sv_of(out_path).c_str(), "rb");
          expect(f != nullptr);
          if (f != nullptr) {
              char buf[64] = {0};
              const size_t n = std::fread(buf, 1, sizeof(buf) - 1, f);
              std::fclose(f);
              expect(std::string(buf, n) == std::string("raw\nlines\n"));
          }
          std::remove(sv_of(out_path).c_str());
          clear_finished_tasks();
      };
  }
