#pragma once

// KimixBase STL umbrella header — includes all stl/* wrappers.

#include "stl/algorithm.h"
#include "stl/deque.h"
#include "stl/filesystem.h"
#include "stl/fixed_map.h"
#include "stl/format.h"
#include "stl/functional.h"
#include "stl/hash.h"
#include "stl/hash_fwd.h"
#include "stl/iterator.h"
#include "stl/list.h"
#include "stl/lru_cache.h"
#include "stl/map.h"
#include "stl/memory.h"
#include "stl/optional.h"
#include "stl/pdqsort.h"
#include "stl/priority_queue.h"
#include "stl/queue.h"
#include "stl/ring_buffer.h"
#include "stl/sstream.h"
#include "stl/stack.h"
#include "stl/string.h"
#include "stl/type_traits.h"
#include "stl/unordered_dense.h"
#include "stl/unordered_map.h"
#include "stl/variant.h"
#include "stl/vector.h"
#include "stl/vector_map.h"
