"""Generate the native BashFix data tables and the byte-exact golden vectors.

The C++ port of the Windows Git Bash compatibility fix (bash_fix.py /
``_shell_compat.py`` in C:/dev/kimi-agent) is verified against the canonical
pure-Python reference implementation.  This script is the single source of the
derived data, so nothing is transcribed by hand:

* ``--tables``   rewrites the generated region of ``src/builtin_tools/bash_tool.cpp``
                 (between the ``GENERATED:BASH-FIX-DATA`` markers) with

                   - ``_FALLBACK_BODIES`` (names + bodies, reference order),
                   - ``_UNSUPPORTED_BODIES`` (name + reason).

* ``--goldens``  writes ``tests/unit/builtin_tools/bash_fix_goldens.inc``
                 (compact expectations, one row per input) and
                 ``tests/unit/builtin_tools/bash_fix_prefix_goldens.inc``
                 (full expected command / prelude for a subset), by running the
                 reference implementation over

                   - every string literal used by the ``TestBashFix*`` classes
                     of C:/dev/kimi-agent/tests/test_bash.py,
                   - a curated feature corpus,
                   - a deterministic fuzz corpus.

Usage (from the project root, with the reference checkout available):

    python scripts/gen_bash_fix_data.py --all

The reference module is located via ``--reference`` (default:
``C:/dev/kimi-agent/bin/kimix_native/_shell_compat.py``); the golden vectors use
a fixed Windows temp directory (``C:/Temp``) so they do not depend on the host
that generated them.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import os
import random
import sys
from pathlib import Path
from unittest import mock

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BASH_TOOL_CPP = PROJECT_ROOT / "src" / "builtin_tools" / "bash_tool.cpp"
GOLDENS_INC = PROJECT_ROOT / "tests" / "unit" / "builtin_tools" / "bash_fix_goldens.inc"
PREFIX_GOLDENS_INC = (
    PROJECT_ROOT / "tests" / "unit" / "builtin_tools" / "bash_fix_prefix_goldens.inc"
)
DEFAULT_REFERENCE = Path("C:/dev/kimi-agent/bin/kimix_native/_shell_compat.py")
DEFAULT_REFERENCE_TESTS = Path("C:/dev/kimi-agent/tests/test_bash.py")

DATA_BEGIN = "// >>> GENERATED:BASH-FIX-DATA >>>"
DATA_END = "// <<< GENERATED:BASH-FIX-DATA <<<"

# Fixed Windows temp directory used for the golden vectors (the reference test
# suite monkeypatches ``_windows_temp_dir`` the same way).
GOLDEN_TEMP_DIR = "C:/Temp"

# Unit separator: joins list fields inside one golden row.
SEP = "\x1f"


def load_reference(path: Path):
    spec = importlib.util.spec_from_file_location("_kimix_bash_fix_reference", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load reference module: {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    module._windows_temp_dir = lambda: GOLDEN_TEMP_DIR
    return module


# ---------------------------------------------------------------------------
# tables
# ---------------------------------------------------------------------------

def c_string(value: str, chunk: int = 4000) -> str:
    """Render *value* as a C++ string literal (UTF-8 source escapes).

    Non-printable bytes become three-digit octal escapes: a ``\\xNN`` escape is
    greedy, so a following hex digit would extend it (``"\\x1Fde"`` would be
    parsed as one out-of-range escape).  Values longer than *chunk* bytes are
    emitted as adjacent literals because MSVC rejects a single literal over
    16380 bytes (C2026).
    """
    data = value.encode("utf-8")
    pieces = []
    for start in range(0, max(len(data), 1), chunk):
        out = ['"']
        for byte in data[start : start + chunk]:
            if byte == 0x22:
                out.append('\\"')
            elif byte == 0x5C:
                out.append("\\\\")
            elif 0x20 <= byte < 0x7F:
                out.append(chr(byte))
            else:
                out.append(f"\\{byte:03o}")
        out.append('"')
        pieces.append("".join(out))
    return "\n".join(pieces) if len(pieces) > 1 else pieces[0]


def render_tables(shell) -> str:
    lines = [
        "// GENERATED by scripts/gen_bash_fix_data.py from kimi-agent's",
        "// bin/kimix_native/_shell_compat.py - DO NOT EDIT BY HAND.",
        "//",
        "// _FALLBACK_BODIES (88 entries: reference insertion order is preserved",
        "// because _FALLBACKS - and therefore the exported definitions prefix and",
        "// bash_compatibility_prelude() - iterate in that order) and",
        "// _UNSUPPORTED_BODIES (commands with no faithful Git Bash equivalent).",
        "const bash_fix_fallback_body k_bash_fix_fallback_bodies[] = {",
    ]
    for name, body in shell._FALLBACK_BODIES.items():
        lines.append(f"    {{{c_string(name)}, {c_string(body)}}},")
    lines.append("};")
    lines.append("")
    reasons = getattr(shell, "_UNSUPPORTED_BODIES", {})
    if reasons:
        lines.append("const bash_fix_unsupported_reason k_bash_fix_unsupported_reasons[] = {")
        for name, reason in reasons.items():
            lines.append(f"    {{{c_string(name)}, {c_string(reason)}}},")
        lines.append("};")
    else:
        lines.append("const bash_fix_unsupported_reason k_bash_fix_unsupported_reasons[] = {};")
    return "\n".join(lines)


def write_tables(shell) -> None:
    text = BASH_TOOL_CPP.read_text(encoding="utf-8")
    begin = text.index(DATA_BEGIN) + len(DATA_BEGIN)
    end = text.index(DATA_END)
    block = "\n" + render_tables(shell) + "\n"
    updated = text[:begin] + block + text[end:]
    BASH_TOOL_CPP.write_text(updated, encoding="utf-8")
    print(f"tables: {BASH_TOOL_CPP} ({len(shell._FALLBACK_BODIES)} fallbacks, "
          f"{len(getattr(shell, '_UNSUPPORTED_BODIES', {}))} unsupported)")


# ---------------------------------------------------------------------------
# corpus
# ---------------------------------------------------------------------------

CURATED = [
    # fallbacks / command positions
    "rev", "'rev' <<< abc", '"rev" <<< abc', r"\rev <<< abc", 'r""ev <<< abc',
    "rev first.txt second.txt", "printf x | rev", "gtimeout 1 true",
    "gtimeout 1 true; printf x | rev", "xdg-open .", "open README.md",
    "printf text | pbcopy", "pbpaste", "wget https://example.com/f.zip",
    "wget -O out.zip https://example.com/f.zip", "wget -q -c -T 5 https://x/y",
    "xclip -selection clipboard", "xsel -bo", "gsed -n 1p file", "gawk '{print}'",
    "zip -r out.zip dir", "zip -q -9 out.zip a b", "nc -z example.com 80",
    "netcat -z -v -w 3 example.com 80", "pgrep bash", "pgrep -lf python",
    "pkill -f python", "tree -L 1 dir", "tree -a -d --noreport", "say hello",
    "wl-copy < file", "wl-paste -n", "python3 --version", "pip3 install x",
    "traceroute -n -m 5 example.com", "column -t -s , file",
    "killall python", "pidof python", "watch -n 1 rev", "watch 'rev <<< abc'",
    "watch -n1 'cd D:\\x && rev'", "htop", "free -h", "free", "uptime -s",
    "top -b -n 1", "ss -s", "ss -tlnp", "ip addr", "ip route", "man ls",
    "systemctl status sshd", "journalctl -u svc -f", "sudo ls",
    # cmd.exe style / misc
    "copy a b", "move a b", "del file.txt", "ren a b", "md dir", "rd dir",
    "cls", "xcopy src dst", "mklink link target", "findstr foo file",
    "fc a b", "where git", "tasklist", "taskkill /F /IM python.exe",
    "systeminfo",
    # wrappers / operands
    "timeout 5 rev <<< abc", "timeout 5s rev <<< abc",
    "timeout --foreground 5 rev <<< abc", "timeout -s KILL 5 rev <<< abc",
    "timeout --signal KILL 5 rev <<< abc", "timeout --kill-after 1 5 rev <<< abc",
    "timeout -- 5 rev <<< abc", "stdbuf -oL rev <<< abc",
    "stdbuf --output=L rev <<< abc", "stdbuf -o L -e L rev <<< abc",
    "nice -n 5 rev <<< abc", "nice --adjustment 5 rev <<< abc",
    "nice rev <<< abc", "xargs rev", "xargs -0 rev", "xargs -n 2 rev",
    "xargs -I {} rev", "printf x | xargs rev", "time timeout 5 rev <<< abc",
    "nohup timeout 5 rev <<< abc", "env timeout 5 rev <<< abc",
    "timeout 5 python3 --version", "gtimeout 5 rev <<< abc",
    "env bash rev <<< abc", "nohup bash rev <<< abc", "env bash -c 'rev <<< abc'",
    "sudo bash -c 'rev <<< abc'", "timeout 5 bash -c 'rev <<< abc'",
    "xargs -a C:\\in.txt rev", "xargs --arg-file=C:\\in.txt rev",
    "env -C C:\\x rev", "env --chdir=C:\\x rev", "time -o C:\\out.txt rev",
    "sudo -D C:\\x rev", "watch -t -d -n 1 rev <<< abc",
    "timeout 3 watch -n 1 rev <<< abc",
    # shell wrappers
    "bash cd /c/dev/x && echo ok", "sh cd /c/dev/x && echo ok",
    "bash grep -rn kimix src tests --include=*.h | head -40",
    "bash -c 'rev'", 'bash -c "rev"', "bash -lc 'rev'", "bash -cl 'rev'",
    "bash -l -c 'rev'", "sh -c 'rev'", "dash -c 'rev'", "ash -c 'rev'",
    "bash -c 'rev' && echo done", "echo $(bash -c 'rev')",
    "bash -c 'echo $HOME'", "bash -c 'cd C:\\x && rev'", "bash cd /c/dev/x && rev",
    "'bash' cd /c/dev/x && echo ok", '"bash" cd /c/dev/x && echo ok',
    r"\bash cd /c/dev/x && echo ok",
    "bash script.sh", "bash ./script.sh", "bash ../tools/run", "bash scripts/deploy.sh",
    "sh build.sh --release", "bash -c 'echo hi' arg1", 'bash -e -c "rev"',
    'bash -ec "rev"', 'bash -x "rev"', "bash -s", "bash --", "bash", "echo bash",
    "ls sh", "bash -c", "FOO=1 bash -c 'printf %s \"$FOO\"'",
    "env FOO=1 bash -c 'printf %s \"$FOO\"'", "timeout 5 bash -c 'rev <<< abc && rev <<< xyz'",
    # nul redirection
    "echo hi > nul", "echo hi >NUL", "echo hi 2> nul", "echo hi &> nul",
    "echo hi >> nul", "echo hi 2>> nul", "echo hi>nul",
    "echo hi > nul; echo bye > nul", "echo 'nul' > nul",
    "echo a > nul; echo b > NUL; echo c >nul", "echo hi > 'nul'",
    'echo hi > "nul"', "echo hi < nul", "echo nul", "echo /dev/null > nul.txt",
    "echo hi > null", "echo hi > /dev/null",
    # Windows paths
    r"cd D:\repo\src", r"C:\Windows\System32\where.exe git", r"d:\tools\run.exe --help",
    r"\\server\share\tool.exe arg", r".\build\tool.exe arg", r"..\scripts\run.sh",
    r"~\bin\tool.exe --help", r"\Users\me\tool.exe", r"build\dist\tool.exe arg",
    r"echo a && C:\x\tool.exe", r"echo a; C:\x\tool.exe | cat", r"(C:\x\tool.exe)",
    r"{ C:\x\tool.exe; }", r"if C:\x\probe.exe; then echo ok; fi",
    r"while C:\x\poll.exe; do :; done", r"command C:\x\tool.exe",
    r"env FOO=1 D:\x\tool.exe", r"nohup D:\x\tool.exe &", r"D:\x\*.exe",
    r"D:\Program\ Files\x.exe", r"x=$(C:\x\tool.exe)", r"echo `C:\x\tool.exe`",
    r"echo \033\015", r"a\nb arg", r"\a\b", r"x\n\t", r"foo\bar arg",
    r"cd /d D:\x", "cd /d", "cd /d && echo x", "cd /d # comment",
    r"cd /d D:\x && echo /d && cd /d/foo", r"cd D:\x", r"echo a > C:\x\y.txt",
    r"env FOO=D:\x true", r"cat D:\x\y.txt", r"declare -a arr=(D:\x\y.txt)",
    # Git Bash virtual paths
    "echo /tmp/x.txt", "cat > /tmp/out.txt", "cd /tmp", "rm -f /tmp/a /tmp/b",
    "echo /c/dev/file.cpp", "echo /C/Dev/file.cpp", "cd /d/foo",
    "/c/Windows/System32/where.exe cmd",
    "cd /c/dev/RoboCute && cat > /tmp/test_util.cpp <<'EOF'\nx\nEOF",
    "echo $(cat /tmp/x)", "env --chdir=/tmp cmd", "arr=(/tmp/a.txt /c/b.txt)",
    "echo '/tmp/x'", 'echo "/tmp/x"', "cat <<'EOF'\n/tmp/x\nEOF",
    "cat <<< /tmp/x", "echo /tmpfile", "echo /d", "echo /c", "x=/tmp/x",
    "alias cd=/c/x", "echo ok # cd /tmp/x", "chdir /tmp",
    # arrays
    "arr=(D:\\x\\y.txt D:\\a\\b.txt)", "arr+=(D:\\x\\y.txt)",
    "arr=(C:\\data\\*.csv)", "declare -a arr=(D:\\x\\y.txt)",
    "declare -a arr=(D:\\x\\y.txt plain)", "local arr=(D:\\x\\y.txt)",
    "arr=(D:\\Program\\ Files\\x.txt)", "arr=(D:\\x\\y.txt); echo ${arr[0]}",
    "arr=('D:\\x\\y.txt')", 'arr=("D:\\x\\y.txt")', "array=(rev open pbcopy)",
    "declare -a x=(rev)", "declare -a x=(wget xclip xsel)", "arr=([k]=D:\\x)",
    "arr=(a\\nb)", "arr=($(rev <<< abc))",
    # heredocs / operators / robustness
    "cat <<EOF\nhi\nEOF", "cat <<EOF\nhi\nEOF\n&& echo done",
    "cat <<EOF\nhi\nEOF\n&& rev", "cat <<-EOF\n\thi\n\tEOF\n&& echo x",
    "cat <<'EOF'\n$(rev)\nEOF", "cat <<EOF\n$(rev)\nEOF",
    "cat <<EOF\nD:\\x\nEOF", "echo a && rev <<< abc",
    "echo x; rev; echo y", "printf x | rev | cat", "rev | rev",
    "rev || rev", "rev & rev", "rev && (rev)", "if rev; then rev; fi",
    "for f in a b; do rev; done", "while rev; do :; done", "case x in rev) rev;; esac",
    "case $f in D:\\x) echo ok;; esac", "case $(rev) in *) :;; esac",
    "function rev { :; }", "rev() { :; }", "f() { rev; }", "declare -f rev",
    "{ rev; }", "! rev", "time rev", "command -v rev", "command -p rev",
    "exec -a name rev", "coproc NAME { rev; }", "coproc rev",
    # quotes / escapes / substitutions
    "echo \"a ; b\"", "echo 'a ; b'", "echo `rev`", "echo $(rev)",
    "echo \"$(rev)\"", "echo \"${rev}\"", "echo ${rev:-x}", "echo $((1+2))",
    "echo [[", "[[ -f x ]] && rev", "(( x = 1 ))", "rev <(cat x)", "rev > >(cat)",
    "echo '", 'echo "', "echo `", "echo $(", "echo ${", "((", "cat <<EOF\nunterminated",
    "echo \\", "rev '", 'rev "', "echo $(rev", "echo `rev", "if rev; then",
    "case x in rev)", "\x01rev\x01", "rev\r\n rev", "rev\t&&\trev",
    "sudo rev", "nohup rev &", "echo rev > /tmp/x", "rev; echo done",
    "env PATH=/x rev", "env -u PATH rev", "env -S 'rev' x",
    "xargs -n1 -I{} rev", "time -o C:\\out.txt rev", "stdbuf -i0 -o0 rev",
    "nice --adjustment=5 rev", "timeout -k 1 5 rev", "timeout 5 /bin/rev",
    "watch -n 5 'date && rev'", "watch --interval=1 rev", "watch -q rev",
    "cd /c/dev/x; rev; cd /tmp", "echo /c/a /tmp/b /d/c",
    "printf '%s\\n' rev", "echo \"rev\", echo 'rev'", "alias rev='rev'",
    "run=timeout", "echo watch date", "echo 'watch rev'", "echo xargs rev",
    "case x in timeout) echo no;; esac", "alias watch='tail -f log'",
    "function timeout { :; }", "timeout() { :; }", "echo hi # timeout 5 rev",
    "echo timeout 5 rev",
]


def literals_from_reference_tests(path: Path) -> list[str]:
    """Every string literal used inside the TestBashFix* classes."""
    if not path.exists():
        return []
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name.startswith("TestBashFix"):
            for sub in ast.walk(node):
                if isinstance(sub, ast.Constant) and isinstance(sub.value, str):
                    found.append(sub.value)
    return found


FUZZ_TOKENS = [
    "rev", "gtimeout", "watch", "sudo", "timeout", "stdbuf", "nice", "xargs",
    "env", "nohup", "time", "command", "exec", "coproc", "bash", "sh", "dash",
    "ash", "free", "uptime", "top", "ss", "ip", "man", "systemctl", "journalctl",
    "zip", "tree", "wget", "nc", "pgrep", "pkill", "killall", "pidof", "column",
    "traceroute", "say", "python3", "pip3", "copy", "move", "del", "md", "ren",
    "where", "tasklist", "taskkill", "systeminfo", "findstr", "fc", "cls",
    "grep", "ls", "cat", "echo", "cd", "printf", "declare", "local", "export",
    "if", "then", "else", "fi", "for", "do", "done", "while", "case", "esac",
    "in", "function", "return", "true", "xx", "-n", "-r", "-f", "--", "-c",
    "-lc", "-cl", "-l", "-e", "-o", "5", "1", "2", "abc", "EOF",
    "D:\\x\\y.txt", "C:\\Program Files\\a", "\\\\srv\\share", ".\\build", "..\\x",
    "~\\b", "\\a\\b", "foo\\bar", "/tmp/x", "/c/dev", "/d", "/tmp",
    ">", ">>", "2>", "&>", "<", "<<<", "|", "||", "&&", ";", "&", "(", ")",
    "{", "}", "[[", "]]", "((", "))", "`", "'", '"', "\\", "$(", "${", "$((1))",
    "#c", "\n", "\t", " ", "=", "a=", "nul", "NUL",
]


def fuzz_corpus(count: int, seed: int = 20240923) -> list[str]:
    rng = random.Random(seed)
    out: list[str] = []
    for _ in range(count):
        parts = []
        for _ in range(rng.randint(1, 9)):
            parts.append(rng.choice(FUZZ_TOKENS))
            if rng.random() < 0.7:
                parts.append(" ")
        command = "".join(parts)
        if "\n" in command and rng.random() < 0.5:
            command = command.replace("\n", " <<EOF\nEOF\n")
        out.append(command)
    return out


def build_corpus(reference_tests: Path) -> list[str]:
    candidates: list[str] = []
    candidates.extend(literals_from_reference_tests(reference_tests))
    candidates.extend(CURATED)
    candidates.extend(fuzz_corpus(1800))
    seen: set[str] = set()
    corpus: list[str] = []
    for command in candidates:
        if not command or len(command) > 1200:
            continue
        if not command.isascii():
            continue
        if command in seen:
            continue
        seen.add(command)
        corpus.append(command)
    return corpus


# ---------------------------------------------------------------------------
# goldens
# ---------------------------------------------------------------------------

def reference_prefix(result, shell) -> str:
    """The prefix the reference scanner prepends (definitions + exports)."""
    unique = list(dict.fromkeys(result.replacements))
    if not unique:
        return ""
    definitions = "\n".join(shell._FALLBACKS[name] for name in unique)
    exports = "\n".join(
        f"if declare -F {name} >/dev/null; then export -f {name}; fi" for name in unique
    )
    return definitions + "\n" + exports + "\n"


def golden_row(shell, command: str) -> tuple[str, ...]:
    result = shell.fix_bash_command(command)
    prefix = reference_prefix(result, shell)
    assert result.command.startswith(prefix), command
    source = result.command[len(prefix):]
    return (
        command,
        SEP.join(result.replacements),
        SEP.join(result.path_changes),
        SEP.join(result.shell_wrappers),
        SEP.join(result.nul_fixes),
        SEP.join(getattr(result, "unsupported", ())),
        source,
        result.warning,
    )


def render_goldens(shell, corpus: list[str]) -> str:
    lines = [
        "// GENERATED by scripts/gen_bash_fix_data.py - DO NOT EDIT BY HAND.",
        "//",
        "// Byte-exact expectations from the reference implementation",
        "// (kimi-agent bin/kimix_native/_shell_compat.py) for a Windows Git Bash",
        "// host with the temp directory fixed to C:/Temp.  Fields per row:",
        "//   command, replacements, path_changes, shell_wrappers, nul_fixes,",
        "//   unsupported, expected_source, expected_warning",
        "// List fields are joined with \\x1f (unit separator).",
        "// The expected command is prefix + expected_source; the prefix",
        "// composition (fallback definitions + conditional exports) is covered by",
        "// bash_fix_prefix_goldens.inc.",
        "struct bash_fix_golden {",
        "    const char *command;",
        "    const char *replacements;",
        "    const char *path_changes;",
        "    const char *shell_wrappers;",
        "    const char *nul_fixes;",
        "    const char *unsupported;",
        "    const char *expected_source;",
        "    const char *expected_warning;",
        "};",
        "",
        f"// {len(corpus)} golden vectors",
        "const bash_fix_golden k_bash_fix_goldens[] = {",
    ]
    for command in corpus:
        row = golden_row(shell, command)
        lines.append("    {" + ", ".join(c_string(f) for f in row) + "},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def render_prefix_goldens(shell) -> str:
    lines = [
        "// GENERATED by scripts/gen_bash_fix_data.py - DO NOT EDIT BY HAND.",
        "//",
        "// Full expected commands (fallback definitions + conditional exports +",
        "// rewritten source) and the interactive compatibility prelude, taken",
        "// verbatim from the reference implementation.",
        "struct bash_fix_prefix_golden {",
        "    const char *command;",
        "    const char *expected_command;",
        "};",
        "",
        "const bash_fix_prefix_golden k_bash_fix_prefix_goldens[] = {",
    ]
    cases: list[str] = [name for name in shell._FALLBACK_BODIES]
    cases.extend(
        [
            "rev; rev",
            "gtimeout 1 true; printf x | rev",
            "rev && tree",
            "timeout 5 rev <<< abc",
            "xargs rev",
            "env bash rev <<< abc",
            "bash -c 'rev && tree'",
            "watch 'rev'",
            "cd /c/dev/x && rev",
            "journalctl -u svc",
            "rev <<< abc",
            "cat <<EOF\nhi\nEOF\n&& rev",
        ]
    )
    for command in cases:
        result = shell.fix_bash_command(command)
        lines.append(f"    {{{c_string(command)}, {c_string(result.command)}}},")
    lines.append("};")
    lines.append("")
    # bash_compatibility_prelude() is gated on sys.platform in the reference.
    with mock.patch.object(shell.sys, "platform", "win32"):
        prelude = shell.bash_compatibility_prelude()
    lines.append("// bash_compatibility_prelude() on win32.")
    lines.append(f"const char k_bash_fix_prelude[] = {c_string(prelude)};")
    lines.append("")
    return "\n".join(lines)


def write_goldens(shell, reference_tests: Path) -> None:
    corpus = build_corpus(reference_tests)
    GOLDENS_INC.write_text(render_goldens(shell, corpus), encoding="utf-8")
    PREFIX_GOLDENS_INC.write_text(render_prefix_goldens(shell), encoding="utf-8")
    print(f"goldens: {GOLDENS_INC} ({len(corpus)} vectors, "
          f"{GOLDENS_INC.stat().st_size} bytes)")
    print(f"prefix goldens: {PREFIX_GOLDENS_INC} "
          f"({PREFIX_GOLDENS_INC.stat().st_size} bytes)")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=DEFAULT_REFERENCE)
    parser.add_argument("--reference-tests", type=Path, default=DEFAULT_REFERENCE_TESTS)
    parser.add_argument("--tables", action="store_true")
    parser.add_argument("--goldens", action="store_true")
    parser.add_argument("--all", action="store_true")
    args = parser.parse_args()
    if not (args.tables or args.goldens or args.all):
        parser.error("nothing to do: pass --tables, --goldens or --all")
    shell = load_reference(args.reference)
    if args.tables or args.all:
        write_tables(shell)
    if args.goldens or args.all:
        write_goldens(shell, args.reference_tests)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
