#!/usr/bin/env python3
"""Regenerate the Unicode tables embedded in the hashline C++ kernels.

``kimi_cli.tools.file.hash_line`` (the hashline / edit-anchor kernel) has two
full-Unicode per-character predicates, and every C++ port of it therefore embeds
lookup tables for them:

* ``str.isalnum()``  (Unicode categories L* and N*) - drives ``has_significant``
  and hence the seed of a line;
* ``str.isspace()``  - drives the byte filter that strips whitespace before
  hashing (Python counts the ASCII information separators U+001C-U+001F and
  U+0085, unlike C ``isspace()``).

Every value is derived from the *running interpreter's* compiled-in Unicode
database (``chr(cp).isalnum()`` / ``chr(cp).isspace()``), never from a pinned
Unicode version and never typed by hand: the reference runs on that same
interpreter, so this is the only definition that cannot drift.  Surrogates
(U+D800-U+DFFF) are forced to ``False``: Python cannot encode them to UTF-8, so
they never reach the kernel.

Targets (``TARGETS`` below) - three independent copies of the same table live in
this tree, because ``builtin_tools`` must not link the ``runtime`` kernel:

* ``src/runtime/tools/line_hash.cpp``   -> ``kAlnumRanges``, ``kPySpace*``
  (the kernel the ``runtime_py`` bindings expose);
* ``src/builtin_tools/edit_tool.cpp``   -> ``ed_alnum_ranges``, ``ed_py_space*``
  (the ``edit`` tool's own anchor validation);
* ``src/builtin_tools/read_tool.cpp``   -> ``rd_alnum_ranges``
  (the ``read`` tool's anchors) - *verified* here, but regenerated by
  ``scripts/gen_read_goldens.py --write-alnum-table``, the script that owns it.

All three copies were corrupted at some point by a bad transcription (91 values
missing from U+066F onward, which shifted every later ``(start, end)`` pair so
the binary search matched huge fake ranges - the emoji planes and
U+E0100-U+E01EF variation selectors counted as alphanumeric), and two of the
whitespace predicates were missing Python's U+001C-U+001F.  This script is the
fix *and* the guard: ``--check`` fails on a stale check-in, ``--verify``
re-proves what actually compiled, ``--scan`` hunts for any further stale copy
under ``src/``.

Usage:
    python scripts/gen_line_hash_tables.py # rewrite every owned table
    python scripts/gen_line_hash_tables.py --cpp src/builtin_tools/edit_tool.cpp
    python scripts/gen_line_hash_tables.py --check # exit 1 when stale
    python scripts/gen_line_hash_tables.py --verify # all-code-point report
    python scripts/gen_line_hash_tables.py --scan # check every table under src/

``--verify`` re-reads the C++ *files* (not the generator's own derivation), so it
independently proves what actually compiled: sorted, non-overlapping ranges and
``table(cp) == chr(cp).isalnum()`` / ``.isspace()`` for all 1 114 112 code
points, per file.
"""

from __future__ import annotations

import argparse
import functools
import re
import sys
from dataclasses import dataclass
from pathlib import Path

MAX_CP = 0x10FFFF
CP_COUNT = MAX_CP + 1  # 1 114 112

GENERATOR_CMD = "python scripts/gen_line_hash_tables.py"


# ---------------------------------------------------------------------------
# targets: one entry per C++ copy of the tables
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Target:
    """One C++ file holding a copy of the hashline Unicode tables."""

    path: str
    #: name of the ``constexpr uint32_t <alnum>[][2]`` table
    alnum_symbol: str
    alnum_begin: str
    alnum_end: str
    #: extra comment lines emitted inside the alnum marker block (per file)
    alnum_note: tuple[str, ...] = ()
    #: whitespace tables (empty when the file has none)
    space_bits_symbol: str = ""
    space_ranges_symbol: str = ""
    space_begin: str = ""
    space_end: str = ""
    #: False -> the file is somebody else's to write (verified, never rewritten)
    owned: bool = True
    #: the command that regenerates *this* file's tables
    generator: str = GENERATOR_CMD


LH_ALNUM_BEGIN = "// >>> BEGIN GENERATED:LH-ALNUM-TABLE >>>"
LH_ALNUM_END = "// <<< END GENERATED:LH-ALNUM-TABLE <<<"
LH_SPACE_BEGIN = "// >>> BEGIN GENERATED:LH-SPACE-TABLES >>>"
LH_SPACE_END = "// <<< END GENERATED:LH-SPACE-TABLES <<<"

ED_ALNUM_BEGIN = "// >>> BEGIN GENERATED:ED-ALNUM-TABLE >>>"
ED_ALNUM_END = "// <<< END GENERATED:ED-ALNUM-TABLE <<<"
ED_SPACE_BEGIN = "// >>> BEGIN GENERATED:ED-SPACE-TABLES >>>"
ED_SPACE_END = "// <<< END GENERATED:ED-SPACE-TABLES <<<"

RD_ALNUM_BEGIN = "// >>> BEGIN GENERATED:RD-ALNUM-TABLE >>>"
RD_ALNUM_END = "// <<< END GENERATED:RD-ALNUM-TABLE <<<"

TARGETS: tuple[Target, ...] = (
    Target(
        path="src/runtime/tools/line_hash.cpp",
        alnum_symbol="kAlnumRanges",
        alnum_begin=LH_ALNUM_BEGIN,
        alnum_end=LH_ALNUM_END,
        space_bits_symbol="kPySpaceAsciiBits",
        space_ranges_symbol="kPySpaceRanges",
        space_begin=LH_SPACE_BEGIN,
        space_end=LH_SPACE_END,
    ),
    Target(
        path="src/builtin_tools/edit_tool.cpp",
        alnum_symbol="ed_alnum_ranges",
        alnum_begin=ED_ALNUM_BEGIN,
        alnum_end=ED_ALNUM_END,
        alnum_note=(
            "// The `edit` tool validates the anchors `read` printed, and its",
            "// kernel embeds its own copy of this table (builtin_tools must not",
            "// link the runtime kernel), so the two copies have to stay equal:",
            "// `tests/unit/builtin_tools/test_edit_tool.cpp` asserts edit's",
            "// hashes equal read's, and `--scan` fails on any stale copy.",
        ),
        space_bits_symbol="ed_py_space_ascii_bits",
        space_ranges_symbol="ed_py_space_ranges",
        space_begin=ED_SPACE_BEGIN,
        space_end=ED_SPACE_END,
    ),
    Target(
        path="src/builtin_tools/read_tool.cpp",
        alnum_symbol="rd_alnum_ranges",
        alnum_begin=RD_ALNUM_BEGIN,
        alnum_end=RD_ALNUM_END,
        owned=False,
        generator="python scripts/gen_read_goldens.py --write-alnum-table",
    ),
)


# ---------------------------------------------------------------------------
# reference predicates (the running interpreter == the reference interpreter)
# ---------------------------------------------------------------------------


def _is_surrogate(cp: int) -> bool:
    return 0xD800 <= cp <= 0xDFFF


def is_alnum(cp: int) -> bool:
    """``chr(cp).isalnum()``; surrogates are never alphanumeric in UTF-8."""
    if _is_surrogate(cp):
        return False
    return chr(cp).isalnum()


def is_space(cp: int) -> bool:
    """``chr(cp).isspace()``; surrogates are never whitespace in UTF-8."""
    if _is_surrogate(cp):
        return False
    return chr(cp).isspace()


@functools.lru_cache(maxsize=None)
def ranges_of(predicate_name: str) -> list[tuple[int, int]]:
    """Sorted, non-overlapping, maximal ``(start, end)`` runs of a predicate."""
    predicate = {"isalnum": is_alnum, "isspace": is_space}[predicate_name]
    out: list[tuple[int, int]] = []
    start = None
    for cp in range(CP_COUNT):
        if predicate(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX_CP))
    assert_wellformed(out)
    return out


def assert_wellformed(ranges: list[tuple[int, int]]) -> None:
    """The binary search in C++ relies on both invariants; broken = silent junk."""
    for a, b in ranges:
        if a > b:
            raise SystemExit("range with start > end: 0x%04X-0x%04X" % (a, b))
    for i in range(1, len(ranges)):
        if ranges[i - 1][1] >= ranges[i][0]:
            raise SystemExit("ranges overlap/unsorted at %d: 0x%04X-0x%04X then "
                             "0x%04X-0x%04X" % (i, ranges[i - 1][0], ranges[i - 1][1],
                                                ranges[i][0], ranges[i][1]))


def ascii_space_bits() -> list[int]:
    """128-bit bitmap of ``str.isspace()`` over the ASCII range (bit cp set)."""
    words = [0, 0, 0, 0]
    for cp in range(0x80):
        if is_space(cp):
            words[cp >> 5] |= 1 << (cp & 31)
    return words


# ---------------------------------------------------------------------------
# C++ emission
# ---------------------------------------------------------------------------


def _hex_chunks(values: list[int], per_line: int) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        lines.append("    " + " ".join("0x%04X," % v for v in chunk))
    return "\n".join(lines)


def alnum_block(target: Target) -> str:
    ranges = ranges_of("isalnum")
    values = [v for pair in ranges for v in pair]
    note = "".join(line + "\n" for line in target.alnum_note)
    return (
        target.alnum_begin + "\n"
        "// Python str.isalnum() == Unicode categories L* (Lu Ll Lt Lm Lo) and\n"
        "// N* (Nd Nl No), read straight out of the running CPython's compiled-in\n"
        "// Unicode database (never a pinned Unicode version: the reference runs on\n"
        "// the same interpreter). Surrogates are never alphanumeric in UTF-8.\n"
        "// %d ranges. Sorted, non-overlapping; do not edit by hand, run\n"
        "// `%s`.\n" % (len(ranges), target.generator) +
        note +
        "constexpr uint32_t %s[][2] = {\n" % target.alnum_symbol +
        _hex_chunks(values, 12) + "\n"
        "};\n"
        + target.alnum_end
    )


def space_block(target: Target) -> str:
    bits = ascii_space_bits()
    ranges = [(a, b) for a, b in ranges_of("isspace") if a >= 0x80]
    values = [v for pair in ranges for v in pair]
    if target.path.endswith("line_hash.cpp"):
        # keep the original, hand-written range list in the pre-existing file
        ranges_comment = (
            "// Python str.isspace() above ASCII (%d ranges; U+0085, U+00A0, U+1680,\n"
            "// U+2000-U+200A, U+2028-U+2029, U+202F, U+205F, U+3000). Sorted,\n"
            "// non-overlapping.\n" % len(ranges))
    else:
        ranges_comment = (
            "// Python str.isspace() above ASCII (%d ranges; U+0085, U+00A0, U+1680,\n"
            "// U+2000-U+200A, U+2028-U+2029, U+202F, U+205F, U+3000). Sorted,\n"
            "// non-overlapping; do not edit by hand, run `%s`.\n"
            % (len(ranges), target.generator))
    return (
        target.space_begin + "\n"
        "// Python str.isspace() over ASCII: a 128-bit bitmap (bit b is set when\n"
        "// chr(b).isspace()), used by the byte filter's ASCII fast path. Python\n"
        "// counts U+001C-U+001F and U+0085 as whitespace, unlike C isspace().\n"
        "constexpr uint32_t %s[4] = {\n" % target.space_bits_symbol +
        "    " + " ".join("0x%08Xu," % w for w in bits) + "\n"
        "};\n" +
        ranges_comment +
        "constexpr uint32_t %s[][2] = {\n" % target.space_ranges_symbol +
        _hex_chunks(values, 8) + "\n"
        "};\n"
        + target.space_end
    )


# ---------------------------------------------------------------------------
# file read/write (preserve the file's CRLF/LF convention byte-for-byte)
# ---------------------------------------------------------------------------


def read_source(path: Path) -> tuple[str, str]:
    """Return (LF-normalised text, newline the file uses)."""
    text = path.read_bytes().decode("utf-8")
    crlf = text.count("\r\n")
    bare_lf = text.count("\n") - crlf
    newline = "\r\n" if crlf > bare_lf else "\n"
    return text.replace("\r\n", "\n"), newline


def write_source(path: Path, text: str, newline: str) -> None:
    path.write_bytes(text.replace("\n", newline).encode("utf-8"))


def _sub_block(text: str, begin: str, end: str, block: str, path: Path) -> str:
    pattern = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    found = pattern.findall(text)
    if len(found) != 1:
        raise SystemExit("%s: expected exactly one %s..%s block, found %d"
                         % (path, begin, end, len(found)))
    return pattern.sub(lambda _m: block, text, count=1)


def generate(text: str, target: Target, path: Path) -> str:
    """Return *text* with this target's generated blocks replaced."""
    text = _sub_block(text, target.alnum_begin, target.alnum_end,
                      alnum_block(target), path)
    if target.space_ranges_symbol:
        text = _sub_block(text, target.space_begin, target.space_end,
                          space_block(target), path)
    return text


def target_for(path: Path) -> Target | None:
    key = path.as_posix()
    for target in TARGETS:
        if key == target.path or key.endswith("/" + target.path):
            return target
    return None


# ---------------------------------------------------------------------------
# --check
# ---------------------------------------------------------------------------


def check(root: Path, only: Target | None) -> int:
    stale = 0
    for target in TARGETS:
        if only is not None and target is not only:
            continue
        path = root / target.path
        text, _ = read_source(path)
        if target.owned:
            want = generate(text, target, path)
            ok = want == text
            detail = "block text" if not ok else ""
        else:
            ok = parsed_alnum(path, target) == ranges_of("isalnum")
            detail = "table values" if not ok else ""
        print("%-8s %s%s" % ("STALE:" if not ok else "up to date:",
                             target.path,
                             (" (%s; regenerate with `%s`)" % (detail, target.generator))
                             if detail else ""),
              file=sys.stderr if not ok else sys.stdout)
        stale += 0 if ok else 1
    return 1 if stale else 0


# ---------------------------------------------------------------------------
# verification: parse the tables back out of the C++ files
# ---------------------------------------------------------------------------


def parse_pairs(text: str, name: str, path: Path) -> list[tuple[int, int]]:
    """Rows of ``constexpr uint32_t <name>[][2] = {...};``."""
    pattern = re.compile(
        r"constexpr\s+uint32_t\s+" + re.escape(name) + r"\s*\[\]\[2\]\s*=\s*\{(.*?)\n\};",
        re.S)
    match = pattern.search(text)
    if match is None:
        raise SystemExit("%s: table %s not found" % (path, name))
    values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]+)", match.group(1))]
    if len(values) % 2:
        raise SystemExit("%s: %s has an odd value count (%d) - the pairs are "
                         "misaligned, the table is corrupt" % (path, name, len(values)))
    return [(values[i], values[i + 1]) for i in range(0, len(values), 2)]


def parse_words(text: str, name: str, path: Path) -> list[int]:
    """Values of a one-dimensional ``constexpr uint32_t <name>[N] = {...};``."""
    pattern = re.compile(
        r"constexpr\s+uint32_t\s+" + re.escape(name) + r"\s*\[\d+\]\s*=\s*\{(.*?)\n\};",
        re.S)
    match = pattern.search(text)
    if match is None:
        raise SystemExit("%s: table %s not found" % (path, name))
    return [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]+)", match.group(1))]


def parsed_alnum(path: Path, target: Target) -> list[tuple[int, int]]:
    text, _ = read_source(path)
    return parse_pairs(text, target.alnum_symbol, path)


def mask_of(ranges: list[tuple[int, int]]) -> bytearray:
    """1-byte-per-code-point membership mask of *ranges*."""
    mask = bytearray(CP_COUNT)
    for a, b in ranges:
        if a > b:
            raise SystemExit("range with start > end: 0x%04X-0x%04X" % (a, b))
        mask[a:b + 1] = b"\x01" * (b - a + 1)
    return mask


@functools.lru_cache(maxsize=None)
def reference_mask(predicate_name: str) -> bytearray:
    predicate = {"isalnum": is_alnum, "isspace": is_space}[predicate_name]
    mask = bytearray(CP_COUNT)
    for cp in range(CP_COUNT):
        if predicate(cp):
            mask[cp] = 1
    return mask


def verify(root: Path, only: Target | None) -> int:
    failed = 0
    for target in TARGETS:
        if only is not None and target is not only:
            continue
        path = root / target.path
        text, _ = read_source(path)
        alnum = parse_pairs(text, target.alnum_symbol, path)
        assert_wellformed(alnum)
        table_alnum = mask_of(alnum)
        want_alnum = reference_mask("isalnum")
        print("%s (%s)" % (target.path, target.alnum_symbol))
        if target.space_ranges_symbol:
            space = parse_pairs(text, target.space_ranges_symbol, path)
            ascii_bits = parse_words(text, target.space_bits_symbol, path)
            if len(ascii_bits) != 4:
                raise SystemExit("%s: %s must hold 4 words, has %d"
                                 % (path, target.space_bits_symbol, len(ascii_bits)))
            assert_wellformed(space)
            for a, b in space:
                if a < 0x80:
                    raise SystemExit("%s: %s must be ASCII-free, has 0x%04X-0x%04X"
                                     % (path, target.space_ranges_symbol, a, b))
            table_space = mask_of(space)
            for cp in range(0x80):
                table_space[cp] = 1 if (ascii_bits[cp >> 5] >> (cp & 31)) & 1 else 0
            want_space = reference_mask("isspace")
            bad_space = [cp for cp in range(CP_COUNT)
                         if table_space[cp] != want_space[cp]]
            print("  %s: %d ranges, %s: %d ranges, %s: %s"
                  % (target.alnum_symbol, len(alnum),
                     target.space_ranges_symbol, len(space),
                     target.space_bits_symbol,
                     ["0x%08X" % w for w in ascii_bits]))
        else:
            bad_space = []
            print("  %s: %d ranges" % (target.alnum_symbol, len(alnum)))
        print("  sorted, non-overlapping, start <= end: yes")
        bad_alnum = [cp for cp in range(CP_COUNT)
                     if table_alnum[cp] != want_alnum[cp]]
        for label, bad, fn in (("isalnum", bad_alnum, is_alnum),
                               ("isspace", bad_space, is_space)):
            print("  %s mismatches over U+0000..U+10FFFF (%d code points): %d"
                  % (label, CP_COUNT, len(bad)))
            for cp in bad[:5]:
                table = table_alnum if label == "isalnum" else table_space
                print(" U+%04X: table=%d python=%d"
                      % (cp, table[cp], int(fn(cp))))
        failed += 1 if (bad_alnum or bad_space) else 0
    return 1 if failed else 0


# ---------------------------------------------------------------------------
# --scan: hunt for any other copy of these tables (owned or not)
# ---------------------------------------------------------------------------
PAIR_TABLE_RE = re.compile(
    r"constexpr\s+uint32_t\s+(\w+)\s*\[\]\[2\]\s*=\s*\{(.*?)\n\};",
    re.S | re.I)
BITMAP_RE = re.compile(
    r"constexpr\s+uint32_t\s+(\w+)\s*\[\d+\]\s*=\s*\{(.*?)\n\};",
    re.S | re.I)


def _pair_table_kind(name: str) -> str:
    """'alnum' / 'space' when *name* is one of the hashline predicate tables."""
    lowered = name.lower()
    if "alnum" in lowered:
        return "alnum"
    if "space" in lowered and "range" in lowered:
        return "space"
    return ""


def _bitmap_kind(name: str) -> str:
    lowered = name.lower()
    if "space" in lowered and "ascii" in lowered and "range" not in lowered:
        return "space"
    return ""


def scan(root: Path) -> int:
    """Re-derive every Unicode predicate table under *root* and compare."""
    reference_alnum = [v for pair in ranges_of("isalnum") for v in pair]
    # the C++ table holds the non-ASCII ranges only; ASCII lives in the bitmap
    reference_space = [v for pair in ranges_of("isspace") if pair[0] >= 0x80
                       for v in pair]
    reference_bits = ascii_space_bits()
    files = sorted(p for ext in ("*.cpp", "*.h", "*.inc")
                   for p in root.rglob(ext))
    checked = 0
    failed = []
    for path in files:
        if "/ext/" in path.as_posix():
            continue
        text, _ = read_source(path)
        for name, body in PAIR_TABLE_RE.findall(text):
            kind = _pair_table_kind(name)
            if not kind:
                continue
            values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]+)", body)]
            want = reference_alnum if kind == "alnum" else reference_space
            ok = values == want
            print("%-46s %-24s values=%4d (want %4d) %s"
                  % (path.as_posix(), name, len(values), len(want),
                     "OK" if ok else "CORRUPT"))
            checked += 1
            if not ok:
                failed.append("%s::%s" % (path.as_posix(), name))
        for name, body in BITMAP_RE.findall(text):
            if not _bitmap_kind(name):
                continue
            values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]+)", body)]
            ok = values == reference_bits
            print("%-46s %-24s words=%4d (want %4d) %s"
                  % (path.as_posix(), name, len(values), len(reference_bits),
                     "OK" if ok else "CORRUPT"))
            checked += 1
            if not ok:
                failed.append("%s::%s" % (path.as_posix(), name))
    print("scanned %d table(s): %d corrupt" % (checked, len(failed)))
    for name in failed:
        print("  CORRUPT: %s" % name, file=sys.stderr)
    return 1 if failed else 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def write_target(path: Path, target: Target) -> int:
    text, newline = read_source(path)
    want = generate(text, target, path)
    if want == text:
        print("unchanged: %s" % target.path)
        return 0
    write_source(path, want, newline)
    print("rewrote the generated tables in %s (%+d bytes)"
          % (target.path, len(want.encode("utf-8")) - len(text.encode("utf-8"))))
    return 0


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="regenerate the hashline Unicode tables embedded in the C++ "
                    "kernels (see TARGETS: line_hash.cpp, edit_tool.cpp, and the "
                    "read_tool.cpp copy owned by gen_read_goldens.py)")
    parser.add_argument("--root", default=".",
                        help="repository root (default: %(default)s)")
    parser.add_argument("--cpp", default=None,
                        help="limit every mode to this target file "
                             "(default: all of %s)"
                             % ", ".join(t.path for t in TARGETS))
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the checked-in tables are stale")
    parser.add_argument("--verify", action="store_true",
                        help="verify the tables in the files over every code point")
    parser.add_argument("--scan", nargs="?", const="src", default=None,
                        metavar="DIR",
                        help="report every predicate table under DIR (default src)")
    args = parser.parse_args(argv)

    root = Path(args.root)
    if args.scan is not None:
        return scan(Path(args.scan))
    only: Target | None = None
    if args.cpp is not None:
        only = target_for(Path(args.cpp))
        if only is None:
            parser.error("unknown target %r; known targets: %s"
                         % (args.cpp, ", ".join(t.path for t in TARGETS)))
    for target in TARGETS:
        if only is not None and target is not only:
            continue
        if not (root / target.path).is_file():
            parser.error("no such file: %s" % (root / target.path))
    if args.check:
        return check(root, only)
    if args.verify:
        return verify(root, only)
    rc = 0
    for target in TARGETS:
        if only is not None and target is not only:
            continue
        if not target.owned:
            print("skipped (owned by `%s`): %s" % (target.generator, target.path))
            continue
        rc |= write_target(root / target.path, target)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
