#!/usr/bin/env python3
"""Generate src/agent/compact_prompts.inc from the kimi-cli prompt templates.

Ports kimi-cli/src/kimi_cli/prompts/{compact,compact_cascade}.md into C string
literals byte-exactly the way the Python reference sees them: Path.read_text()
enables universal newlines, so CRLF line endings in the checked-in files are
translated to LF before the string reaches prompts.COMPACT / COMPACT_CASCADE
(compaction.py::_build_prompt_text prepends one more '\\n').

Usage:
    python scripts/gen_compact_prompt_inc.py [--reference <kimi-cli root>]

The default reference root is the kimi-agent checkout next to this repo's
parent directory (D:/kimi-agent); pass --reference to override.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REFERENCE = Path("D:/kimi-agent/kimi-cli/src/kimi_cli/prompts")
OUTPUT = REPO_ROOT / "src" / "agent" / "compact_prompts.inc"

HEADER = (
    "// GENERATED by scripts/gen_compact_prompt_inc.py - DO NOT EDIT.\n"
    "//\n"
    "// Byte-exact port of kimi-cli/src/kimi_cli/prompts/compact.md and\n"
    "// compact_cascade.md (the reference's prompts.COMPACT / prompts.COMPACT_CASCADE,\n"
    "// kimi_cli/prompts/__init__.py reads them with universal newlines, so CRLF\n"
    "// becomes LF). Included inside soul.cpp's anonymous namespace; the strings\n"
    "// are the full file contents INCLUDING the leading '---' frontmatter line,\n"
    "// exactly like the Python module-level constants.\n"
)


def c_escape(line: str) -> str:
    """Escape one line (without its newline) as a C string literal body."""
    out = []
    for ch in line:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20 or ord(ch) == 0x7F:
            out.append("\\x%02x" % ord(ch))
        else:
            out.append(ch)
    return "".join(out)


def emit(name: str, text: str) -> str:
    """Emit one constexpr string built from per-line literals."""
    lines = text.split("\n")
    # split() leaves a trailing "" when the text ends with "\n"; every real
    # line becomes one "...\n" literal.
    parts = []
    for i, line in enumerate(lines):
        last = i == len(lines) - 1
        if last and line == "":
            break
        suffix = "" if last else "\\n"
        parts.append('        "%s%s"' % (c_escape(line), suffix))
    body = "\n".join(parts)
    return "constexpr const char *%s =\n%s;\n" % (name, body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", default=str(DEFAULT_REFERENCE),
                        help="kimi-cli prompts directory")
    parser.add_argument("--output", default=str(OUTPUT))
    args = parser.parse_args()
    prompt_dir = Path(args.reference)
    compact = (prompt_dir / "compact.md").read_bytes().decode("utf-8")
    cascade = (prompt_dir / "compact_cascade.md").read_bytes().decode("utf-8")
    # Universal newlines translation (Path.read_text with newline=None).
    compact = compact.replace("\r\n", "\n").replace("\r", "\n")
    cascade = cascade.replace("\r\n", "\n").replace("\r", "\n")
    out = HEADER + "\n" + emit("k_compact_prompt", compact) + "\n" + emit(
        "k_compact_cascade_prompt", cascade)
    Path(args.output).write_text(out, encoding="utf-8", newline="\n")
    print("wrote %s (%d bytes)" % (args.output, len(out.encode("utf-8"))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
