#!/usr/bin/env python3
"""Generate the native CLI's help text from the kimi-agent reference.

``src/kimix/cli_impl/constants.py`` holds the CLI's ``HELP_STR`` as an f-string
whose only dynamic parts are ``{colorful_text('<name>', fg=Color.YELLOW)}``
wrappers around the slash-command names.  The native CLI (``src/cli/cli_args.cpp``)
must print that text byte-for-byte, so the text is *generated* here instead of
being transcribed by hand - a hand copy silently loses the column alignment and
the two-space indents the reference uses.

The generator splits the f-string into alternating segments and writes
``src/cli/cli_help_text.inc``:

    { "<literal text>", false },          # plain text
    { "/file:<path>",   true  },          # wrapped in Color.YELLOW by the caller

``cli_help_text(colorful)`` concatenates the segments, wrapping the ``true``
ones in ANSI yellow when colour is enabled, which reproduces the f-string
exactly (with ``_colorful_print`` off the reference returns the text unchanged,
which is the ``false`` path).

Usage:
    python scripts/gen_cli_help.py            # regenerate the .inc
    python scripts/gen_cli_help.py --check    # fail if the file is out of date
    python scripts/gen_cli_help.py --reference D:/path/to/kimi-agent
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REFERENCE = Path(os.environ.get("KIMI_AGENT_ROOT", r"C:/dev/kimi-agent"))
DEFAULT_OUT = PROJECT_ROOT / "src" / "cli" / "cli_help_text.inc"

#: The f-string body of HELP_STR, up to the closing triple quote.
_HELP_RE = re.compile(r"HELP_STR = f'''(.*?)'''", re.S)
#: One dynamic part: colorful_text('...', fg=Color.YELLOW)
_DYNAMIC_RE = re.compile(r"\{colorful_text\('(.*?)', fg=Color\.YELLOW\)\}")


def extract_segments(reference: Path) -> list[tuple[str, bool]]:
    """Return the (text, is_command) segments of the reference HELP_STR."""
    constants = reference / "src" / "kimix" / "cli_impl" / "constants.py"
    if not constants.is_file():
        raise SystemExit(f"reference constants.py not found: {constants}")
    source = constants.read_text(encoding="utf-8")
    match = _HELP_RE.search(source)
    if match is None:
        raise SystemExit(f"HELP_STR not found in {constants}")

    body = match.group(1)
    segments: list[tuple[str, bool]] = []
    position = 0
    for hit in _DYNAMIC_RE.finditer(body):
        if hit.start() > position:
            segments.append((body[position : hit.start()], False))
        segments.append((hit.group(1), True))
        position = hit.end()
    if position < len(body):
        segments.append((body[position:], False))
    joined = "".join(text for text, _ in segments)
    plain = _DYNAMIC_RE.sub(lambda m: m.group(1), body)
    if joined != plain:
        raise SystemExit("segment split does not reproduce the reference text")
    return segments


def c_literal(text: str) -> str:
    """Render `text` as a single C++ string literal."""
    out = ['"']
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        elif ord(ch) < 0x20:
            out.append(f"\\x{ord(ch):02x}")
            # A following hex digit would extend the escape.
            out.append('""')
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def render(segments: list[tuple[str, bool]], reference: Path) -> str:
    lines = [
        "// GENERATED by scripts/gen_cli_help.py - DO NOT EDIT.",
        "//",
        "// The reference CLI's help text (kimix/cli_impl/constants.py::HELP_STR) as",
        "// alternating segments; `true` marks a slash-command name that the caller",
        "// wraps in Color.YELLOW (33) when colour is enabled.",
        "//",
        f"// Source: {reference / 'src' / 'kimix' / 'cli_impl' / 'constants.py'}",
        "",
        "static const cli_help_segment kCliHelpSegments[] = {",
    ]
    for text, is_command in segments:
        lines.append(f"    {{{c_literal(text)}, {'true' if is_command else 'false'}}},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, default=DEFAULT_REFERENCE,
                        help="kimi-agent checkout (default: %(default)s)")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT,
                        help="generated include path (default: %(default)s)")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the generated file is out of date")
    args = parser.parse_args()

    segments = extract_segments(args.reference)
    text = render(segments, args.reference)

    if args.check:
        if not args.out.is_file():
            print(f"missing generated file: {args.out}")
            return 1
        current = args.out.read_text(encoding="utf-8")
        if current != text:
            print(f"out of date: {args.out}")
            return 1
        plain = "".join(t for t, _ in segments)
        commands = sum(1 for _, is_command in segments if is_command)
        print(f"in sync: {args.out} ({len(segments)} segments, {commands} command "
              f"names, {len(plain)} chars)")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" keeps the generated file LF-only (the repo's .gitattributes
    # normalises it on checkout) so --check compares like for like.
    args.out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(segments)} segments)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
