"""Regenerate tests/unit/builtin_tools/read_image_goldens.inc from the Python reference.

The read_image C++ port (src/builtin_tools/read_image_tool.{h,cpp}) mirrors
kimi-agent's read_image tool.  Some of its kernels are *not* reachable from
Python (the compression-ladder planner, the mip-map pyramid, the payload
builders, ``_is_animated_webp``), so they cannot be compared by a differential
harness; instead the expected values are derived here from the reference
implementation and baked into a header the Boost.UT target replays.

Everything below is computed by *running* the kimi-agent code:

* ``sniff_image_dimensions`` / ``_is_animated_webp`` -- called directly.
* the ladder rung sequence -- ``_encode_within_budget`` is executed with a
  byte budget of 1 (so no rung ever fits and the whole ladder is traversed)
  while ``_encode_png`` / ``_encode_jpeg`` are instrumented to record every
  encode (format, quality, and the *actual* fitted dimensions).
* the mip-map level list -- the level loop of ``mipmap_downsample`` is
  replayed with ``_mipmap_one_level`` instrumented on a real image, which also
  cross-checks the plain-arithmetic model emitted into the goldens.
* ``_fit_within_edge`` -- called on a real PIL image and read back with ``.size``.

Usage:  python scripts/gen_read_image_goldens.py
        python scripts/gen_read_image_goldens.py --reference C:/dev/kimi-agent
"""

from __future__ import annotations

import argparse
import io
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REFERENCE = Path(os.environ.get("KIMI_AGENT_ROOT", r"C:/dev/kimi-agent"))
OUT = ROOT / "tests" / "unit" / "builtin_tools" / "read_image_goldens.inc"


def add_reference_to_path(reference: Path) -> None:
    for sub in ("kimi-cli/src", "src"):
        p = str(reference / sub)
        if os.path.isdir(p):
            sys.path.insert(0, p)


def c_str(text: str) -> str:
    """A C++ raw string literal (round-trippable, no escaping needed)."""
    assert ")KX\"" not in text, text
    return 'R"KX(' + text + ')KX"'


def c_hex(data: bytes) -> str:
    return '"' + data.hex() + '"'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", default=str(DEFAULT_REFERENCE),
                        help="kimi-agent checkout root")
    args = parser.parse_args()
    reference = Path(args.reference)
    if not (reference / "kimi-cli" / "src").is_dir():
        print(f"reference checkout not found: {reference}", file=sys.stderr)
        return 1
    add_reference_to_path(reference)

    from PIL import Image

    import kimi_cli.utils.image_compress as ic
    from kimi_cli.tools.file.read_media_shared import ImageDelivery, build_media_note

    print("image_compress:", ic.__file__)

    lines: list[str] = []
    out = lines.append

    out("// GENERATED by scripts/gen_read_image_goldens.py -- DO NOT EDIT BY HAND.")
    out("// Every value below was produced by running the kimi-agent Python")
    out("// reference (kimi_cli.utils.image_compress / read_media_shared) on the")
    out("// input recorded beside it; see the generator for provenance.")
    out("")

    # ------------------------------------------------------------------
    # 1. sniff_image_dimensions
    # ------------------------------------------------------------------
    def save(img, fmt, **kw):
        buf = io.BytesIO()
        img.save(buf, format=fmt, **kw)
        return buf.getvalue()

    sniff_cases: list[tuple[str, bytes]] = []

    def sniff(name: str, data: bytes) -> None:
        sniff_cases.append((name, data))

    sniff("empty", b"")
    sniff("text", b"not an image")
    sniff("png_magic_only", b"\x89PNG\r\n\x1a\n")
    sniff("png_3x4", save(Image.new("RGB", (3, 4), (51, 102, 204)), "PNG"))
    sniff("png_max_u32", b"\x89PNG\r\n\x1a\n" + bytes(8) +
          (0xFFFFFFFF).to_bytes(4, "big") + (0xFFFFFFFF).to_bytes(4, "big") + bytes(16))
    sniff("png_2_31_plus", b"\x89PNG\r\n\x1a\n" + bytes(8) +
          (0x80000000).to_bytes(4, "big") + (0x80000001).to_bytes(4, "big") + bytes(16))
    sniff("apng", save(Image.new("RGB", (32, 16), (255, 0, 0)), "PNG", save_all=True,
                       append_images=[Image.new("RGBA", (32, 16), (0, 0, 255))], duration=100))
    gif = save(Image.new("RGB", (5, 6)), "GIF")
    sniff("gif89_5x6", gif)
    sniff("gif_comment_ext", gif[:6] + gif[6:13] + b"\x21\xfe\x05hello\x00" + gif[13:])
    sniff("gif_frame_rect", b"GIF89a" + (10).to_bytes(2, "little") + (20).to_bytes(2, "little") +
          bytes([0x00, 0x00, 0x00]) + b"\x2c" + bytes(4) + (5).to_bytes(2, "little") +
          (5).to_bytes(2, "little") + bytes(10))
    sniff("gif_short", b"GIF89a\x01")
    sniff("bmp_7x8", save(Image.new("RGB", (7, 8)), "BMP"))
    sniff("bmp_topdown", b"BM" + bytes(16) + (100).to_bytes(4, "little", signed=True) +
          (-200).to_bytes(4, "little", signed=True) + bytes(40))
    sniff("bmp_min_height", b"BM" + bytes(16) + (100).to_bytes(4, "little", signed=True) +
          (-2147483648).to_bytes(4, "little", signed=True) + bytes(40))
    sniff("bmp_max_width", b"BM" + bytes(16) + (2147483647).to_bytes(4, "little", signed=True) +
          (5).to_bytes(4, "little", signed=True) + bytes(40))
    sniff("bmp_os2", b"BM" + bytes(2) + (12).to_bytes(4, "little") + bytes(4) +
          (12).to_bytes(4, "little") + (3).to_bytes(2, "little") + (4).to_bytes(2, "little") + bytes(40))
    sniff("bmp_short", b"BMxxxx")
    sniff("webp_lossy_9x10", save(Image.new("RGB", (9, 10), (51, 102, 204)), "WEBP"))
    sniff("webp_lossless_11x12", save(Image.new("RGB", (11, 12), (1, 2, 3)), "WEBP", lossless=True))
    sniff("webp_vp8x_13x17", b"RIFF" + bytes(4) + b"WEBPVP8X" + bytes(8) + bytes([0x02]) + bytes(5) +
          (12).to_bytes(3, "little") + (16).to_bytes(3, "little"))
    sniff("webp_vp8_masked", b"RIFF" + bytes(4) + b"WEBPVP8 " + bytes(8) +
          (0xE234).to_bytes(2, "little") + (0xD345).to_bytes(2, "little") + bytes(4))
    sniff("webp_vp8l_packed", b"RIFF" + bytes(4) + b"WEBPVP8L" + bytes(8) +
          ((12) | (16 << 14)).to_bytes(4, "little") + bytes(4))
    sniff("webp_riff_short", b"RIFF\x00\x00\x00\x00WEBP")
    for orientation in range(1, 9):
        exif = Image.Exif()
        exif[0x0112] = orientation
        sniff(f"jpeg_exif{orientation}_60x20",
              save(Image.new("RGB", (60, 20), (9, 9, 9)), "JPEG", exif=exif))
        # big-endian TIFF ('MM') APP1 block, like camera output
        payload = b"Exif\x00\x00" + b"MM" + b"\x00\x2a" + (8).to_bytes(4, "big")
        payload += (1).to_bytes(2, "big") + (0x0112).to_bytes(2, "big") + (3).to_bytes(2, "big")
        payload += (1).to_bytes(4, "big") + orientation.to_bytes(2, "big") + bytes(2)
        seg_len = len(payload) + 2
        mm = (b"\xff\xd8" + b"\xff\xe1" + seg_len.to_bytes(2, "big") + payload +
              b"\xff\xc0\x00\x08\x08" + (20).to_bytes(2, "big") + (60).to_bytes(2, "big") + b"\x00")
        sniff(f"jpeg_exif_mm{orientation}_60x20", mm)
    sniff("jpeg_progressive_60x20",
          save(Image.new("RGB", (60, 20), (1, 2, 3)), "JPEG", progressive=True))
    sniff("jpeg_restart_300x300",
          save(Image.new("RGB", (300, 300), (7, 8, 9)), "JPEG", restart_marker_blocks=1))
    sniff("jpeg_junk", b"\xff\xd8" + bytes(40))
    sniff("jpeg_sof_without_exif",
          b"\xff\xd8" + b"\xff\xc0\x00\x11\x08" + (17).to_bytes(2, "big") +
          (13).to_bytes(2, "big") + b"\x03" + bytes(9))
    sniff("tiff_5x5", save(Image.new("RGB", (5, 5)), "TIFF"))
    sniff("ico_16x16", save(Image.new("RGB", (16, 16)), "ICO"))

    out("// sniff_image_dimensions(data)")
    out("struct read_image_sniff_golden { const char* name; const char* hex; bool has_value;")
    out("                              int64_t width; int64_t height; bool transposed; };")
    out("static const read_image_sniff_golden k_read_image_sniff_goldens[] = {")
    for name, data in sniff_cases:
        dims = ic.sniff_image_dimensions(data)
        if dims is None:
            out(f'    {{"{name}", {c_hex(data)}, false, 0, 0, false}},')
        else:
            out(f'    {{"{name}", {c_hex(data)}, true, {dims.width}, {dims.height}, '
                f'{"true" if dims.transposed else "false"}}},')
    out("};")
    out("")

    # ------------------------------------------------------------------
    # 2. _is_animated_webp (not reachable from Python through runtime_py)
    # ------------------------------------------------------------------
    anim_cases = {
        "anim_flag": b"RIFF" + bytes(4) + b"WEBPVP8X" + bytes(8) + bytes([0x02]) + bytes(5) +
                     (12).to_bytes(3, "little") + (16).to_bytes(3, "little"),
        "no_anim_flag": b"RIFF" + bytes(4) + b"WEBPVP8X" + bytes(8) + bytes([0x00]) + bytes(5) +
                        (12).to_bytes(3, "little") + (16).to_bytes(3, "little"),
        "alpha_flag_only": b"RIFF" + bytes(4) + b"WEBPVP8X" + bytes(8) + bytes([0x10]) + bytes(5) +
                           (12).to_bytes(3, "little") + (16).to_bytes(3, "little"),
        "not_vp8x": b"RIFF" + bytes(4) + b"WEBPVP8 " + bytes(8) + bytes([0x02]) + bytes(5) +
                    (12).to_bytes(3, "little") + (16).to_bytes(3, "little"),
        "not_webp": b"RIFF" + bytes(4) + b"AVI " + bytes(8) + bytes([0x02]) + bytes(5) +
                    (12).to_bytes(3, "little") + (16).to_bytes(3, "little"),
        "too_short": b"RIFF" + bytes(4) + b"WEBPVP8X" + bytes(8) + bytes([0x02]),
        "animated_file": save(Image.new("RGB", (32, 16), (255, 0, 0)), "WEBP", save_all=True,
                              append_images=[Image.new("RGB", (32, 16), (0, 255, 0))],
                              duration=100, loop=0),
    }
    out("// _is_animated_webp(data)")
    out("struct read_image_anim_golden { const char* name; const char* hex; bool animated; };")
    out("static const read_image_anim_golden k_read_image_anim_goldens[] = {")
    for name, data in anim_cases.items():
        out(f'    {{"{name}", {c_hex(data)}, {"true" if ic._is_animated_webp(data) else "false"}}},')
    out("};")
    out("")

    # ------------------------------------------------------------------
    # 3. _fit_within_edge -> fit_dimensions
    # ------------------------------------------------------------------
    fit_cases = [(4000, 3000, 2000), (3000, 1000, 2000), (3000, 1000, 1000), (1000, 1000, 1000),
                 (999, 900, 768), (2000, 1000, 2000), (1, 1, 2000), (5000, 1, 1000),
                 (1400, 100, 1000), (2000, 2000, 256), (3, 4, 2), (2200, 1100, 2000),
                 (2000, 1, 1), (1234, 567, 999)]
    out("// _fit_within_edge(image, edge) -> fit_dimensions(w, h, edge)")
    out("struct read_image_fit_golden { int32_t w; int32_t h; int32_t edge; bool changed;")
    out("                               int32_t new_w; int32_t new_h; };")
    out("static const read_image_fit_golden k_read_image_fit_goldens[] = {")
    for w, h, edge in fit_cases:
        img = Image.new("RGB", (w, h))
        fitted = ic._fit_within_edge(img, edge)
        changed = fitted is not img
        out(f'    {{{w}, {h}, {edge}, {"true" if changed else "false"}, '
            f'{fitted.width}, {fitted.height}}},')
    out("};")
    out("")

    # ------------------------------------------------------------------
    # 4. _encode_within_budget rung sequence (instrumented encoder calls)
    # ------------------------------------------------------------------
    orig_png, orig_jpeg = ic._encode_png, ic._encode_jpeg
    called: list[tuple[str, int, int, int]] = []

    def rec_png(image):
        called.append(("png", 0, image.width, image.height))
        return orig_png(image)

    def rec_jpeg(image, quality):
        called.append(("jpeg", quality, image.width, image.height))
        return orig_jpeg(image, quality)

    ladder_cases = [(True, 3000, 1000), (True, 4000, 3000), (True, 2000, 2000),
                    (True, 1000, 1000), (True, 999, 900), (True, 256, 256),
                    (True, 1300, 1300), (True, 2200, 1100), (True, 2000, 1),
                    (False, 3000, 1000), (False, 500, 500), (False, 256, 256)]
    ladder_rows = []
    for prefer_lossless, w, h in ladder_cases:
        image = Image.new("RGB", (w, h), (51, 102, 204))
        called.clear()
        ic._encode_png, ic._encode_jpeg = rec_png, rec_jpeg
        try:
            ic._encode_within_budget(image, prefer_lossless=prefer_lossless, byte_budget=1)
        finally:
            ic._encode_png, ic._encode_jpeg = orig_png, orig_jpeg
        ladder_rows.append((prefer_lossless, w, h, list(called)))
        print(f"ladder {prefer_lossless} {w}x{h}: {len(called)} encode calls")

    out("// _encode_within_budget traversed with byte_budget = 1: every encoder call")
    out("// the reference makes, in order, as (format, quality, fitted w, fitted h).")
    out("// The executor replays build_ladder_plan the same way (edge == 0 means")
    out("// 'encode at the current size', otherwise fit the current size to the edge).")
    out("struct read_image_ladder_golden { bool prefer_lossless; int32_t w; int32_t h;")
    out("                                  const char* rungs; };")
    out("// rungs: 'png:0:WxH' / 'jpeg:Q:WxH', space separated.")
    out("static const read_image_ladder_golden k_read_image_ladder_goldens[] = {")
    for prefer_lossless, w, h, calls in ladder_rows:
        sig = " ".join(f"{f}:{q}:{cw}x{ch}" for f, q, cw, ch in calls)
        out(f'    {{{"true" if prefer_lossless else "false"}, {w}, {h}, {c_str(sig)}}},')
    out("};")
    out("")

    # ------------------------------------------------------------------
    # 5. mip-map pyramid levels
    # ------------------------------------------------------------------
    def model_levels(w: int, h: int) -> list[tuple[int, int]]:
        """The level loop of mipmap_downsample, in plain arithmetic."""
        levels = [(w, h)]
        cw, ch = w, h
        while cw > 2 and ch > 2:
            nw, nh = cw // 2, ch // 2
            if nw < 2 or nh < 2:
                break
            levels.append((nw, nh))
            cw, ch = nw, nh
        return levels

    # cross-check the model against the real code path: run mipmap_downsample on
    # a real image with _mipmap_one_level instrumented and compare the shapes.
    orig_one_level = ic._mipmap_one_level
    shapes: list[tuple[int, int]] = []

    def rec_one_level(arr):
        result = orig_one_level(arr)
        shapes.append((int(result.shape[1]), int(result.shape[0])))
        return result

    mip_cases = [(4000, 3000), (2000, 2000), (1000, 563), (300, 300), (5, 4), (3, 2),
                 (2, 2), (1, 1), (2200, 1100), (256, 512), (33, 17)]
    mip_rows = []
    for w, h in mip_cases:
        img = Image.new("RGB", (w, h), (10, 20, 30))
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        shapes.clear()
        ic._mipmap_one_level = rec_one_level
        try:
            ic.mipmap_downsample(buf.getvalue(), "image/png", max_edge=2000, byte_budget=1)
        finally:
            ic._mipmap_one_level = orig_one_level
        model = model_levels(w, h)
        # _mipmap_one_level is called once more than there are levels: the loop
        # breaks *after* producing a level with an edge < 2, and that level is
        # discarded.  Reconstruct the appended levels from the recorded shapes
        # (append happens only when both halved edges are >= 2).
        recorded = [(w, h)] + [s for s in shapes if s[0] >= 2 and s[1] >= 2]
        assert recorded == model, f"level model mismatch for {w}x{h}: {recorded} != {model}"
        mip_rows.append((w, h, model))
    print("mip-map level model cross-checked against mipmap_downsample on real images")

    out("// mipmap_downsample level dimensions (decoded image first, then 2x2 halving)")
    out("struct read_image_mipmap_golden { int32_t w; int32_t h; const char* levels; };")
    out("// levels: 'WxH' pairs, space separated.")
    out("static const read_image_mipmap_golden k_read_image_mipmap_goldens[] = {")
    for w, h, levels in mip_rows:
        sig = " ".join(f"{lw}x{lh}" for lw, lh in levels)
        out(f'    {{{w}, {h}, {c_str(sig)}}},')
    out("};")
    out("")

    out("// mipmap_downsample level selection: first level whose longest edge <= max_edge,")
    out("// else the last (smallest) level.")
    out("struct read_image_mipselect_golden { int32_t w; int32_t h; int32_t max_edge; int32_t idx; };")
    out("static const read_image_mipselect_golden k_read_image_mipselect_goldens[] = {")
    for w, h, levels in mip_rows:
        for max_edge in (2000, 1000, 768, 100, 1):
            idx = None
            for i, (lw, lh) in enumerate(levels):
                if max(lw, lh) <= max_edge:
                    idx = i
                    break
            if idx is None:
                idx = len(levels) - 1
            out(f'    {{{w}, {h}, {max_edge}, {idx}}},')
    out("};")
    out("")

    # ------------------------------------------------------------------
    # 6. payload builders (build_media_note / pdf preview line)
    # ------------------------------------------------------------------
    out("// read_media_shared.build_media_note / read_pdf_pages._build_pdf_delivery_preview")
    out("struct read_image_note_golden { const char* kind; const char* mime; int64_t byte_size;")
    out("                                int32_t dw; int32_t dh; bool has_dims;")
    out("                                const char* delivery_kind; int32_t d_width; int32_t d_height;")
    out("                                int64_t d_bytes; const char* d_mime; bool mipmap;")
    out("                                int32_t rx; int32_t ry; int32_t rw; int32_t rh; bool has_region;")
    out("                                bool resized; const char* expected; };")
    out("static const read_image_note_golden k_read_image_note_goldens[] = {")
    note_cases = [
        ("image", "image/png", 123456, (800, 600), None),
        ("image", "image/png", 123456, None, None),
        ("image", "image/jpeg", 4096, (2000, 1000),
         dict(kind="downsampled", width=1000, height=500, byte_length=12345, mime_type="image/jpeg")),
        ("image", "image/jpeg", 4096, (2000, 1000),
         dict(kind="downsampled", width=1000, height=500, byte_length=12345,
              mime_type="image/jpeg", mipmap=True)),
        ("image", "image/png", 4096, (4000, 3000),
         dict(kind="crop", width=500, height=400, byte_length=9999, mime_type="image/png",
              region=(10, 20, 500, 400))),
        ("image", "image/png", 4096, (4000, 3000),
         dict(kind="crop", width=500, height=400, byte_length=9999, mime_type="image/png",
              region=(10, 20, 500, 400), resized=True)),
        ("image", "image/png", 4096, (4000, 3000),
         dict(kind="full", width=4000, height=3000, byte_length=4096, mime_type="image/png")),
        ("video", "video/mp4", 250000, (1920, 1080), None),
        ("video", "video/mp4", 250000, None, None),
    ]
    for kind, mime, byte_size, dims, delivery_spec in note_cases:
        delivery = None
        region = None
        if delivery_spec is not None:
            region = delivery_spec.pop("region", None)
            crop = ic.CropRegion(x=region[0], y=region[1], width=region[2], height=region[3]) if region else None
            delivery = ImageDelivery(region=crop, **delivery_spec)
        expected = build_media_note(kind=kind, mime_type=mime, byte_size=byte_size,
                                    dimensions=dims, delivery=delivery)
        dk = ""
        dw = dh = 0
        db = 0
        dm = ""
        mip = False
        resized = False
        if delivery is not None:
            dk = delivery.kind
            dw, dh, db, dm = delivery.width, delivery.height, delivery.byte_length, delivery.mime_type
            mip, resized = delivery.mipmap, bool(delivery.resized)
        rx = ry = rw = rh = 0
        if region:
            rx, ry, rw, rh = region
        out(f'    {{{c_str(kind)}, {c_str(mime)}, {byte_size}, {dims[0] if dims else 0}, '
            f'{dims[1] if dims else 0}, {"true" if dims else "false"}, '
            f'{c_str(dk)}, {dw}, {dh}, {db}, {c_str(dm)}, {"true" if mip else "false"}, '
            f'{rx}, {ry}, {rw}, {rh}, {"true" if region else "false"}, '
            f'{"true" if resized else "false"}, {c_str(expected)}}},')
    out("};")
    out("")

    out("// read_pdf_pages._DPI_SEQUENCE")
    out("static const int32_t k_read_image_pdf_dpi_sequence[] = {"
        + ", ".join(str(d) for d in __import__("kimi_cli.tools.file.read_pdf_pages", fromlist=["x"])._DPI_SEQUENCE)
        + "};")
    out("")

    # ------------------------------------------------------------------
    # 7. reported metadata text: format_byte_size, error builders,
    #    conversion guidance
    # ------------------------------------------------------------------
    from kimi_cli.tools.file.read_media import (
        _build_full_resolution_limit_error,
        _build_image_decode_limit_error,
    )
    from kimi_cli.tools.file.read_media_shared import build_image_delivery_limit_error
    from kimi_cli.utils.image_format_policy import build_image_conversion_guidance

    out("// image_compress.format_byte_size (JS Math.round / Python .1f parity)")
    out("struct read_image_bytesize_golden { int64_t n; const char* expected; };")
    out("static const read_image_bytesize_golden k_read_image_bytesize_goldens[] = {")
    for n in (0, 1, 1023, 1024, 1025, 1536, 2560, 4096, 262144, 3932160, 4194304,
              1048575, 1048576, 5242880, 1073741824, 999, 9000000):
        out(f'    {{{n}, {c_str(ic.format_byte_size(n))}}},')
    out("};")
    out("")

    out("// the three delivery/limit error builders")
    out("struct read_image_error_golden { int32_t which; const char* arg; int64_t n1; int64_t n2;")
    out("                               int32_t n3; const char* expected; };")
    out("// which: 0 delivery_limit(final, budget, edge), 1 decode_limit(final),")
    out("//        2 full_resolution_limit(path, final)")
    out("static const read_image_error_golden k_read_image_error_goldens[] = {")
    for final_bytes, budget, edge in ((300000, 262144, 2000), (262145, 262144, 2000),
                                      (1, 1, 1), (5000000, 262144, 1000)):
        text = build_image_delivery_limit_error(final_bytes, budget, edge)
        out(f'    {{0, "", {final_bytes}, {budget}, {edge}, {c_str(text)}}},')
    for final_bytes in (70000000, 67108865, 0):
        out(f'    {{1, "", {final_bytes}, 0, 0, {c_str(_build_image_decode_limit_error(final_bytes))}}},')
    for path, final_bytes in (("big.png", 5000000), ("C:\\tmp\\a b.png", 3932161), ("x", 0)):
        text = _build_full_resolution_limit_error(path, final_bytes)
        out(f'    {{2, {c_str(path)}, {final_bytes}, 0, 0, {c_str(text)}}},')
    out("};")
    out("")

    out("// image_format_policy.build_image_conversion_guidance(path, mime, os_kind)")
    out("struct read_image_guidance_golden { const char* path; const char* mime; const char* os_kind;")
    out("                                   const char* expected; };")
    out("static const read_image_guidance_golden k_read_image_guidance_goldens[] = {")
    for path, mime in (("a.avif", "image/avif"), ("photo.HEIC", "image/heic"), ("dir.b/x.heif", "image/heif"),
                       ("scan.bmp", "image/bmp"), ("page.tiff", "image/tiff"), ("icon.ico", "image/x-icon"),
                       ("weird", "image/jxl"), ("a.b.svgz", "image/svg+xml")):
        for os_kind in ("macOS", "Linux", "Windows", "Plan9"):
            text = build_image_conversion_guidance(path, mime, os_kind)
            out(f'    {{{c_str(path)}, {c_str(mime)}, {c_str(os_kind)}, {c_str(text)}}},')
    out("};")
    out("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
