"""Differential parity tests for the bash builtin tool (kimix-base <-> kimi-agent).

``src/builtin_tools/bash_tool.cpp`` is a port of kimi-agent's bash tool.  This
module compares every kernel the ``runtime_py`` extension exposes through
``runtime_py.builtin_tools.shell`` against the *original* implementation in the
kimi-agent checkout (``C:/dev/kimi-agent``, override with ``KIMI_AGENT_ROOT``):

* RTK rewrite scanner -- ``common.py`` ``_split_shell_segments`` /
  ``_read_shell_word`` / ``_rewrite_shell_segment`` / ``_is_known_rtk_command`` /
  ``_maybe_rewrite_shell_command_with_rtk`` (FOCUS 1).  A silent divergence here
  changes the command that actually runs, so the corpus is adversarial and
  fuzzed with a fixed seed.
* ``fix_bash_command`` -- not exposed to Python (only C++ can call it); it is
  covered by the generated byte-exact vectors in
  ``tests/unit/builtin_tools/bash_fix_goldens.inc`` +
  ``bash_rtk_goldens.inc`` and the Boost.UT target ``test_builtin_bash``, both
  regenerated from the reference by ``scripts/gen_bash_fix_data.py``.
* Output kernels -- ``output_enhance.py`` (``interpret_exit_code``,
  ``is_expected_exit``, ``annotate_failure``) and ``common.py``
  (``_find_error_line_index``, ``_truncate_lines``), byte-exact messages.
* Safety kernels -- ``safety.py`` ``command_detection_variants`` /
  ``check_hardline_blocked`` / ``foreground_background_guidance``.

Provenance rules (learned the hard way):

* The pure-Python bodies of ``safety.py`` / ``output_enhance.py`` live in
  ``<kimi-agent>/bin/kimix_native/tools.py`` (the ``_compat_*`` functions) and
  are what kimi-agent runs when its native gate is off.  They are loaded *by
  path* from the kimi-agent checkout so that neither ``kimix_native`` on
  ``sys.path`` (the kimix-base mirror) nor a shared ``sys.modules`` entry can
  silently substitute the wrong implementation.
* ``kimix.tools.common`` (RTK + truncation + error-line kernels) is pure Python
  in the reference checkout; its four quote helpers delegate to
  ``_shell_compat.py``, which is pinned to the kimi-agent copy as well.
* ``detect_self_kill``/``self_kill_hint`` are owned by the pwsh tool and are not
  covered here.

Non-ASCII input: every kernel below is exact for ASCII only -- that is the
project-wide ASCII-gate convention, and the reference's own callers gate on
``str.isascii()`` (``safety.py`` ``_native_use_native("TOOLS") and
command.isascii()``).  ``test_ascii_gate_is_documented`` pins the two places
where an ungated non-ASCII call would differ.
"""

from __future__ import annotations

import importlib
import importlib.util
import os
import random
import sys
from pathlib import Path
from unittest import mock

import pytest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

_KIMIX_BASE_ROOT = Path(__file__).resolve().parents[2]


def _kimix_base_bin_dir():
    """The kimix-base build directory holding ``runtime_py`` (conftest's order)."""
    for mode in ("release", "releasedbg", "debug", "check"):
        cand = _KIMIX_BASE_ROOT / "bin" / mode
        if cand.is_dir() and any(cand.glob("runtime_py.*")):
            return cand
    for cand in sorted((_KIMIX_BASE_ROOT / "bin").glob("*")):
        if cand.is_dir() and any(cand.glob("runtime_py.*")):
            return cand
    return None


# IMPORT ORDER IS LOAD-BEARING: import the freshly built kimix-base extension
# *before* touching the kimi-agent reference.  Importing kimi-agent runs
# ``kimi_cli.native_loader._setup()``, which puts ``<kimi-agent>/bin`` -- a
# *staged, older* ``runtime_py.pyd`` -- first on ``sys.path``; a later
# ``import runtime_py`` would then quietly compare against that stale binary
# (reproduced: the staged Sep-20 copy still returns the pre-fix results).
_BIN_DIR = _kimix_base_bin_dir()
if _BIN_DIR is not None:
    sys.path.insert(0, str(_BIN_DIR))
import runtime_py  # noqa: E402

if _BIN_DIR is None:  # pragma: no cover - defensive
    pytest.skip("no kimix-base runtime_py build found under bin/",
                allow_module_level=True)

_NATIVE_PATH = Path(runtime_py.__file__).resolve()
assert _BIN_DIR.resolve() in _NATIVE_PATH.parents, (
    f"runtime_py came from {_NATIVE_PATH}, not the kimix-base build "
    f"{_BIN_DIR} -- a staged copy shadowed it; parity results would be bogus")

from _parity_ref import KIMI_AGENT_ROOT, KIMI_CLI_SRC, KIMIX_SRC, ref, ref_available  # noqa: E402

pytestmark = pytest.mark.skipif(
    not ref_available(), reason="kimi-agent checkout not available"
)

SHELL = runtime_py.builtin_tools.shell


# ---------------------------------------------------------------------------
# reference modules (loaded with explicit provenance)
# ---------------------------------------------------------------------------


def _load_by_path(path: Path, name: str):
    """Load a standalone reference module by file path (no package context)."""
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        pytest.skip(f"cannot load reference module {path}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def _load_shim_package(pkg_dir: Path, alias: str):
    """Load ``<kimi-agent>/bin/kimix_native`` under *alias* as a real package.

    ``tools.py`` uses relative imports (``from . import _native, use_native``),
    so it cannot be loaded standalone; importing it under a private alias keeps
    the kimi-agent copy authoritative without touching the ``kimix_native`` entry
    (which a kimix-base shim may legitimately own in this session).
    """
    spec = importlib.util.spec_from_file_location(
        alias, pkg_dir / "__init__.py",
        submodule_search_locations=[str(pkg_dir)])
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        pytest.skip(f"cannot load reference package {pkg_dir}")
    package = importlib.util.module_from_spec(spec)
    sys.modules[alias] = package
    spec.loader.exec_module(package)
    return importlib.import_module(f"{alias}.tools")


_SHIM_DIR = KIMI_AGENT_ROOT / "bin" / "kimix_native"
KIMI_NATIVE_TOOLS = _load_shim_package(_SHIM_DIR, "_parity_bash_native")
KIMI_SHELL_COMPAT = _load_by_path(
    KIMI_AGENT_ROOT / "bin" / "kimix_native" / "_shell_compat.py",
    "_parity_bash_shell_compat",
)

_BASH_DIR = KIMIX_SRC / "kimix" / "tools" / "file" / "bash"
for _path in (str(KIMIX_SRC), str(KIMI_CLI_SRC)):
    if os.path.isdir(_path) and _path not in sys.path:
        sys.path.insert(0, _path)

# ``common.py`` is loaded *by path*: ``import kimix.tools.common`` resolves the
# ``kimix`` package from whatever is first on ``sys.path``/``sys.modules``, and
# the kimi-agent workspace has two candidates -- ``src/kimix`` (the real package)
# and the 22-line ``kimi-cli/src/kimix`` shim, whose ``tools/common.py`` only
# re-exports rtk installation helpers.  A session that already imported the shim
# (several test modules do) would otherwise hand this file the wrong module and
# every comparison here would compare against nothing.
_common_path = KIMIX_SRC / "kimix" / "tools" / "common.py"
common = _load_by_path(_common_path, "_parity_bash_common")
for _required in ("_split_shell_segments", "_rewrite_shell_segment",
                  "_is_known_rtk_command", "_maybe_rewrite_shell_command_with_rtk",
                  "_find_error_line_index", "_truncate_lines"):
    if not hasattr(common, _required):  # pragma: no cover - defensive
        pytest.skip(f"{_common_path} lacks {_required}", allow_module_level=True)

# Pin `common.py`'s quote helpers (``_find_dq_end`` & friends) to the kimi-agent
# scanner; ``_compat_shell()`` would otherwise resolve ``kimix_native`` from
# whatever happens to be first on ``sys.path``.
common._COMPAT_SHELL = KIMI_SHELL_COMPAT

#: Windows path shape kimi-agent's ``_rtk_binary_path()`` returns (``rtk.exe``).
RTK_BINARY = str(Path("C:/Temp/rtk.exe"))

_FG_HINT = (
    "Long-running command detected; use `job_output` to wait for it or to stop it."
)


def py_maybe_rewrite(command, token_kill, exclude_read=False, pwsh=False,
                     *, available=True, rtk_path=None):
    """Reference ``_maybe_rewrite_shell_command_with_rtk`` with its gates injected."""
    with mock.patch.object(common, "_rtk_available", return_value=available), \
            mock.patch.object(
                common, "_rtk_binary_path",
                return_value=None if rtk_path is None else Path(rtk_path)):
        return common._maybe_rewrite_shell_command_with_rtk(
            command, token_kill, exclude_read, pwsh)


def cpp_maybe_rewrite(command, token_kill, exclude_read=False, pwsh=False,
                      *, available=True, rtk_path=None):
    return tuple(SHELL.maybe_rewrite_shell_command_with_rtk(
        command, token_kill, available, "" if rtk_path is None else rtk_path,
        exclude_read, pwsh))


# ---------------------------------------------------------------------------
# corpora
# ---------------------------------------------------------------------------

#: Commands kimi-agent's own suite uses (tests/test_token_filter.py
#: ``rtk_available`` fixture + tests/test_bash.py ``TestBashRtkRewrite``).
KIMI_AGENT_RTK_CASES = [
    ("find . -name '*.cpp' -not -path './build/*'", True, False, False),
    ("git status", True, False, False),
    ("git status && cargo test", True, False, False),
    ("git status; cargo test", True, False, False),
    ("git status || cargo test", True, False, False),
    ("rtk git status", True, False, False),
    ("RTK_DISABLED=1 git status", True, False, False),
    ("unknown-cmd arg", True, False, False),
    ('echo "git status"', True, False, False),
    ("git status", False, False, False),
    ("read var", True, True, False),
    ("git status | grep x", True, False, False),
    ("VAR=value git status", True, False, False),
    ('echo "$(git status)"', True, False, False),
    ("echo `git status`", True, False, False),
    ("git log | head", True, False, False),
    ("git status", True, False, True),
    ("git status; cargo test", True, False, True),
    ("& rtk git status", True, False, True),
]

#: Adversarial corpus: quoting, separators, env prefixes, subshells, comments,
#: escaped separators, path-shaped executable tokens, RTK gates.
RTK_ADVERSARIAL = [
    # bare / leftmost-command detection
    "git", "git status", "git status --short", "ls -la", "npm run build",
    "Git status", "GIT status", "git.exe status", "GIT.EXE status",
    "read x", "READ x", "find .", "find.exe .", "gradlew build", "mvn -q",
    "rg foo", "grep -n x f", "oc get pods", "unknown-cmd arg",
    # quotes / substitutions / subshells
    "'git status'", '"git status"', "git 'status'", 'git "status"',
    'echo "git status"', "echo 'git status'", "echo $(git status)",
    "echo `git status`", 'echo "$(git status)"', "echo ${git}",
    "(git status)", "$(git status)", "x=$(git status) git log",
    "(cd /tmp && git status)", "echo $(cd x; git status)",
    "git log $(git status)", "git log `git status`", "echo $(git status",
    "echo `git status", "echo 'git status", 'echo "git status',
    "echo \\'git status\\'", "echo a\\;b", "echo \"a ; b\"", "echo 'a;b'",
    "printf '%s' git", "echo $'git'", "eval git", "echo `a`git",
    # separators / pipelines / background
    "git log | head", "git log | head | tail", "git log |head", "git log| head",
    "git status && cargo test", "git status||cargo test", "git status;cargo test",
    "git status;;git status", "git log&&&git status", "git log|||git status",
    "git log &", "git log&", "git log & git status", "git log&git status",
    "cd / &&git status", "x;git status", ";git status", "&&git status",
    "|git status", "||git status", "git log \\; git status",
    "git log \\| git status", "git log \\&& git status", "git log \\\\ git status",
    "git status && (cargo test)", "if git status; then cargo test; fi",
    "for f in a b; do git status; done", "git status\ncargo test",
    "git status\t&&\tcargo test", "  git status  ",
    # comments (the reference has no comment awareness)
    "git log # git status", "# git status", "  # git status",
    "git log; # git status", "git log && # git status", "git log # x && ls",
    # env prefixes / assignments / modifiers
    "FOO=1 git status", "FOO=1 BAR=2 git log", "FOO= git log", "_x=1 git log",
    "9x=1 git log", "A_1= git log", "FOO.bar=1 git log", "FOO=1 sudo git log",
    "sudo git log", "time git log", "nohup git log", "nice git log",
    "nice -n5 git log", "time sudo git log", "sudo time nice git log",
    "RTK_DISABLED=1", "RTK_DISABLED=1 sudo git log", "RTK_DISABLED=2 git log",
    "RTK_DISABLED=1x git log", "RTK_DISABLED=1 git log", "x=RTK_DISABLED=1 git log",
    "sudo=true git log", "sudoer git log", "timex git log", "nohupx git log",
    # already-rewritten / rtk spellings
    "rtk", "rtk ", "rtk\tgit log", "rtk.exe", "rtk.exe git log",
    "& rtk", "& rtk git log", "&  rtk git log", "RTK git log",
    "RTK.EXE git log", "rtk.exe.git log", "rtkx git log",
    # path-shaped executables (WindowsPath.stem semantics)
    "/usr/bin/git status", "./git status", "dir/git status", "dir/git/",
    "dir/git/.", "git/.", "//git", "\\\\git", "\\\\srv\\share\\git status",
    "C:\\bin\\git status", "C:\\bin\\git.exe status", "\"C:\\Program Files\\git.exe\" status",
    "'/usr/bin/git' status", "$HOME/bin/git status", "~/bin/git status",
    "../git status", ".../git status", "git.", ".git", "a.b", "x.exe.exe",
    "git.exe.git", "git.git", "read/", "read.", "node_modules/.bin/vite",
    # trailing separators / dots (regression: bash_token_stem)
    "ls\\", "ls\\\\", "npm\\", "gradlew\\\\", "go&$HOME/bin/git\\",
    "git\\\\", "git\\x", "git/..", "git/.", "./git/", "C:git", "C:",
    "C:/", "C:\\", "\\\\?\\C:\\bin\\git",
    # whitespace
    "\tgit status", "\ngit status", " git status", "git\tstatus", "git \t status",
    "\rgit status", "git\rstatus", "   ", "", "\t", "\n",
]

#: Path-flavoured tokens: the reference uses ``Path(...).stem``, which is
#: platform dependent (``WindowsPath`` here, ``PosixPath`` elsewhere).
RTK_PATH_TOKENS = [
    "\\\\git", "//git", "\\\\\\git", "\\\\srv\\share\\git", "dir/git/",
    "dir/git/.", "git/.", "git\\", "git\\\\", "\\\\?\\UNC\\srv\\share\\git",
    "C:git", "C:\\", "c:/git", "C:\\bin\\git", ".\\git", "..\\git",
    "git\\\\x", "git/../git", "dir//git", "dir/./git", "/git", "\\\\git\\",
]

_SPLIT_TOKENS = [
    "git", "ls", "||", "&&", ";", "|", "&", "'", '"', "`", "$(", ")", "(", "}",
    "${x}", "$'a'", "#c", "\\", "\\\\", " ", "\t", "\n", "-rf", "x", "D:\\x",
]
_SPLIT_PIECES = ["git status", "'a;b'", '"a&&b"', "$(x; y)", "`a | b`", ";",
                 "&&", "||", "|", "&", " ; ", " && ", " || ", " | ", " & ",
                 "echo ", "x", "$'a;b'", "'unterminated", '"unterminated',
                 "`unterminated", "$(unterminated", "#c;d", "\\;", "\\|"]


def _seeded_split_corpus(count: int, seed: int) -> list[str]:
    rng = random.Random(seed)
    out: list[str] = []
    for _ in range(count):
        parts = []
        for _ in range(rng.randint(1, 7)):
            parts.append(rng.choice(_SPLIT_TOKENS))
            if rng.random() < 0.6:
                parts.append(rng.choice(_SPLIT_PIECES))
        out.append("".join(parts))
    return out


def _seeded_rtk_corpus(count: int, seed: int) -> list[str]:
    """Realistic shell commands built from RTK-relevant words and separators."""
    rng = random.Random(seed)
    words = [
        "git", "ls", "read", "find", "grep", "rg", "cargo", "npm", "npx", "pnpm",
        "pytest", "ruff", "uv", "go", "docker", "kubectl", "aws", "gh", "curl",
        "wget", "psql", "php", "mvn", "gradlew", "rustup", "echo", "cat", "true",
        "sudo", "time", "nohup", "nice", "env", "command", "exec", "xargs",
        "timeout", "stdbuf", "rtk", "rtk.exe", "RTK", "Git", "GIT", "git.exe",
        "read.exe", "readme", "/usr/bin/git", "./git", "../git", "dir/git",
        "dir/git.exe", "C:\\bin\\git", "C:\\bin\\git.exe", "~/bin/git",
        "$HOME/bin/git", "a.b", "git.", ".git", "x.exe.exe", "FOO=1", "_x=1",
        "9x=1", "RTK_DISABLED=1", "RTK_DISABLED=1x", "'git'", '"git"',
        "'git status'", "$'git'", "${VAR}", "$HOME", "`git status`",
        "$(git status)", "'a;b'", '"a|b"', "status", "-la", "--short", "--", "x",
    ]
    separators = [" ", "  ", "\t", "", " ; ", " && ", " || ", " | ", " & ",
                  ";", "&&", "||", "|", "&", " \\; ", " \\| "]
    punct = ["'", '"', "`", "\\\\", "\\", "$(", "(", ")", "#", "\n", "\r", "!"]
    out: list[str] = []
    for _ in range(count):
        n = rng.randint(1, 8)
        parts: list[str] = []
        for i in range(n):
            parts.append(rng.choice(words))
            if i != n - 1:
                parts.append(rng.choice(separators))
            if rng.random() < 0.1:
                parts.append(rng.choice(punct))
        if rng.random() < 0.15:
            parts.insert(0, rng.choice(["# ", " ", "\t", "\n"]))
        if rng.random() < 0.1:
            parts.append(rng.choice(["'", '"', "`", "$(", "\\"]))
        out.append("".join(parts))
    return out


def _seeded_hardline_corpus(count: int, seed: int) -> list[str]:
    rng = random.Random(seed)
    prefixes = ["", "sudo ", "/bin/", "./", "'/bin/", '"', "x;", "cd / &&",
                "(", "!", "sh -c ", "env ", "x=1 ", "\\", "|", "$(", "`", "if ",
                "time "]
    commands = ["rm", "rmdir", "del", "rm.exe", "rmdir.exe", "del.exe", "RM",
                "kill", "kill.exe", "format", "format.exe", "dd", "mkfs",
                "mkfs.ext4", "shutdown", "reboot", "halt", "poweroff"]
    mids = [" ", "  ", "\t", "/", ".", "-", ""]
    flags = ["-rf", "-r", "-f", "-Rf", "--recursive", "-rfv", "-s", "/s", "/q",
             "/f", "--force", "-fr", "-x", "", "|", ";", "&&"]
    targets = ["/", "~", "$HOME", "${HOME}", "C:\\", "c:/", "/*", "*", "..",
               ".", "/tmp", "x", "'/'", '"/"', "/'", '/"', "/)", "//", "/./",
               "\\", "/home", "$home", "foo/", "-", "1", "$PPID", "2", "C:",
               "D:/", "c:**", "c:*/", "/dev/sda", "/usr/local"]
    ddargs = ["if=x.img", "of=/dev/sda", "of=/dev/nvme0n1", "of=/dev/disk2",
              "of=/dev/rdisk1", "of=/dev/hda", "of=/dev/sdb1", "of=/dev/nv1",
              "of=/dev/rd0", "xof=/dev/sda", "of=/dev/SDA", "of=/dev/sda1",
              "of=/dev/x", "of=/dev/diskx"]
    out: list[str] = []
    for _ in range(count):
        r = rng.random()
        if r < 0.45:
            out.append(rng.choice(prefixes) + rng.choice(commands) +
                       rng.choice(mids) + rng.choice(flags) + " " +
                       rng.choice(targets))
        elif r < 0.6:
            out.append(rng.choice(prefixes) + "dd " +
                       " ".join(rng.sample(ddargs, rng.randint(1, 3))))
        elif r < 0.7:
            out.append(rng.choice(prefixes) + rng.choice(commands) +
                       rng.choice(mids) + rng.choice(targets))
        elif r < 0.8:
            out.append(":(){ :|:& };:" if rng.random() < 0.5 else ":(){ :|: x :&")
        elif r < 0.9:
            out.append(rng.choice(prefixes) + "mkfs" + rng.choice(mids) +
                       rng.choice(["/dev/sda", "ext4", ".ext4", "x", ".x"]))
        else:
            out.append(rng.choice(prefixes) + rng.choice(commands) + " " +
                       rng.choice(targets))
    return out


def _seeded_foreground_corpus(count: int, seed: int) -> list[str]:
    rng = random.Random(seed)
    tokens = [
        "npm", "pnpm", "yarn", "bun", "run", "start", "dev", "serve", "watch",
        "next", "vite", "nodemon", "uvicorn", "gunicorn", "python", "-m",
        "http.server", "docker", "compose", "up", "docker-compose", "nohup",
        "setsid", "&", "&&", "|", ";", "(", ")", "'x'", '"y"', ".", "/", "-",
        "node_modules", ".bin", "exec", "npx", "sudo", "cd", "build", "test",
        "VITE", "Npm", "npmx", "xnpm", "vitex", "xvite", "vite.", ".vite",
        "--host", "-d", "x", " ", "  ", "\t", "echo", "true",
    ]
    return ["".join(rng.choice(tokens) for _ in range(rng.randint(1, 10)))
            for _ in range(count)]


def _seeded_output_corpus(count: int, seed: int) -> list[str]:
    rng = random.Random(seed)
    tokens = [
        "ok", "error: boom", "failed to build", "warning: x",
        "Traceback (most recent call last):", "  at foo", "line", "",
        "Error: nope", "denied", "not found", "cannot access",
        "No such file or directory", "command not found", "ModuleNotFoundError:",
        "No module named 'x'", "Permission", "permission denied", "timeout",
        "connection refused", "unhandled", "does not exist", "ERROR", "FOUND",
        "x" * 200,
    ]
    out: list[str] = []
    for _ in range(count):
        n = rng.randint(0, 30)
        text = "\n".join(rng.choice(tokens) for _ in range(n))
        if rng.random() < 0.3:
            text += "\n"
        if rng.random() < 0.2:
            text = text.replace("\n", "\r\n")
        elif rng.random() < 0.1:
            text = text.replace("\n", "\r")
        out.append(text)
    return out


_EXIT_CASES = [
    ("grep foo file.txt", 1), ("egrep foo file.txt", 1), ("fgrep foo file.txt", 1),
    ("rg foo", 1), ("ag foo", 1), ("ack foo", 1), ("diff a b", 1),
    ("colordiff a b", 1), ("find / -name x", 1), ("test -f x", 1),
    ("[ -f x ]", 1), ("curl https://example.com", 6),
    ("curl https://example.com", 7), ("curl https://example.com", 22),
    ("curl https://example.com", 28), ("git diff", 1), ("/usr/bin/git status", 1),
    ("FOO=1 git diff", 1), ("echo a | grep foo", 1), ("a && b; git diff", 1),
    ("echo hi", 0), ("echo hi", None), ("nosuchcommand_xyz", 127),
    ("python script.py", 2), ("git diff", 2), ("grep foo file", 2),
    ("frobnicate --all", 42), ("seq 1 1000 | head -1", 141),
    ("producer | tail -5", 141), ("echo $(echo x | cat) | head -1", 141),
    ("seq 1 1000", 141), ("seq 1 1000 || head -1", 141), ("echo 'a | b'", 141),
    ("git", 1), ("grep", 1), ("[", 1), ("", 1), ("  ", 1), ("ls", 2),
    ("tree", 1), ("wc -l x", 1), ("git status", 128), ("GIT DIFF", 1),
    ("/bin/git", 1), ("git; git diff", 1), ("(git diff)", 1),
    ("grep 'a|b' f", 1), ('grep "a|b" f', 1), ("grep `a|b` f", 1),
    ("grep $(a|b) f", 1), ("seq 1 3|head", 141), ("seq 1 3 |head", 141),
]

_ANNOTATE_CASES = [
    "bash: foo: command not found",
    "'foo' is not recognized as an internal or external command",
    "cat: nope: No such file or directory",
    "ls: cannot access 'x': No such file or directory",
    "Traceback (most recent call last):\nModuleNotFoundError: No module named 'requests'",
    "Permission denied",
    "mkdir: cannot create directory 'x': Permission denied",
    "everything looks fine", "", "sh: 1: cmd: not found",
    "zsh: command not found: foo", "ImportError: No module named foo",
    "No such file or directory", "cannot find x", "EACCES: permission denied",
    "COMMAND NOT FOUND", "not found", "/bin/sh: rev: command not found",
    "fatal: does not exist", "connection refused", "timeout while connecting",
    "unhandled exception",
    "x" * 3990 + "command not found",          # just inside the 4000-char sample
    "x" * 4000 + " command not found",         # just outside
    "x" * 5000 + "command not found",
]

_KNOWN_NAMES = [
    # every reference name, plus .exe / case / substring mutations
    "ls", "tree", "read", "smart", "grep", "rg", "diff", "wc", "json", "log",
    "env", "deps", "git", "cargo", "vitest", "jest", "tsc", "lint", "prettier",
    "format", "next", "prisma", "playwright", "npm", "npx", "pnpm", "pytest",
    "ruff", "mypy", "pip", "uv", "go", "golangci-lint", "rspec", "rubocop",
    "rake", "dotnet", "docker", "kubectl", "oc", "aws", "gh", "glab", "gt",
    "curl", "wget", "psql", "php", "phpunit", "phpstan", "pest", "paratest",
    "ecs", "pint", "gradlew", "mvn",
    # negatives and near misses
    "find", "find.exe", "echo", "cat", "rtk", "rtk.exe", "", " ", "LS ", " ls",
    "git ", "g", "gi", "gitt", "git--", "git.exe.exe", "smart.exe", "Smart",
    "SMART", "GOLANGCI-LINT", "golangci_lint", "go.exe", "npm.cmd", "npm.exe",
    "ls.exe.exe", "readme", "reading", "formatter", "nextjs", "cargo.lock",
    "docker-compose", "docker.exe", "kubectl.exe", "glab-cli", "psql.exe",
]


# ---------------------------------------------------------------------------
# provenance
# ---------------------------------------------------------------------------


def test_reference_provenance():
    """The compared implementations really come from the kimi-agent checkout."""
    agent_root = str(KIMI_AGENT_ROOT).replace("\\", "/").lower()
    for module in (KIMI_NATIVE_TOOLS, KIMI_SHELL_COMPAT, common):
        path = str(getattr(module, "__file__", "")).replace("\\", "/").lower()
        assert path.startswith(agent_root), (module.__name__, path)
    assert common._compat_shell() is KIMI_SHELL_COMPAT
    for name in ("_split_shell_segments", "_read_shell_word",
                 "_rewrite_shell_segment", "_is_known_rtk_command",
                 "_maybe_rewrite_shell_command_with_rtk",
                 "_find_error_line_index", "_truncate_lines"):
        assert callable(getattr(common, name)), name
    for name in ("_compat_check_hardline_blocked", "_compat_detect_hardline_command",
                 "_compat_command_detection_variants",
                 "_compat_foreground_background_guidance",
                 "_compat_interpret_exit_code", "_compat_is_expected_exit",
                 "_compat_annotate_failure"):
        assert callable(getattr(KIMI_NATIVE_TOOLS, name)), name


def test_reference_public_api_delegates_to_the_compat_bodies():
    """kimi-agent's public shell APIs dispatch to the ``_compat_*`` bodies.

    Verified on the source (works regardless of which ``kimix``/``kimix_native``
    a session already imported): each public function references its
    ``_compat_*`` counterpart, so the bodies compared above are exactly what
    kimi-agent runs on its pure-Python path.
    """
    import ast

    pairs = {
        KIMIX_SRC / "kimix" / "tools" / "file" / "bash" / "safety.py": [
            ("command_detection_variants", "_compat_command_detection_variants"),
            ("detect_hardline_command", "_compat_detect_hardline_command"),
            ("check_hardline_blocked", "_compat_check_hardline_blocked"),
            ("foreground_background_guidance",
             "_compat_foreground_background_guidance"),
        ],
        KIMIX_SRC / "kimix" / "tools" / "file" / "bash" / "output_enhance.py": [
            ("interpret_exit_code", "_compat_interpret_exit_code"),
            ("is_expected_exit", "_compat_is_expected_exit"),
            ("annotate_failure", "_compat_annotate_failure"),
        ],
    }
    for path, mapping in pairs.items():
        assert path.is_file(), path
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source)
        assert source.count("isascii()") >= 1  # the documented ASCII gate
        bodies = {node.name: ast.dump(node) for node in tree.body
                  if isinstance(node, ast.FunctionDef)}
        for public, compat in mapping:
            assert public in bodies, (path.name, public)
            assert compat in bodies[public], (path.name, public, compat)


def test_reference_public_bodies_are_the_compat_bodies():
    """With the native gate off, kimi-agent's public API == the ``_compat_*`` bodies.

    Skipped when the kimi-agent package cannot be imported in this session (its
    import chain depends on which ``kimix``/``kimix_native`` modules other test
    modules already loaded).  The kernels tested below never depend on it: they
    always compare against the by-path ``_compat_*`` bodies.
    """
    try:
        safety = ref("kimix.tools.file.bash.safety")
        output_enhance = ref("kimix.tools.file.bash.output_enhance")
    except Exception:  # pragma: no cover - environment dependent
        pytest.skip("kimi-agent package not importable in this session")
    with mock.patch.object(safety, "_native_use_native", lambda *a, **k: False), \
            mock.patch.object(safety, "_NATIVE_TOOLS", None):
        assert safety.check_hardline_blocked("rm -rf /") == \
            KIMI_NATIVE_TOOLS._compat_check_hardline_blocked("rm -rf /")
        assert safety.foreground_background_guidance("npm run dev") == \
            KIMI_NATIVE_TOOLS._compat_foreground_background_guidance("npm run dev")
        assert safety.command_detection_variants("r\\m -rf /") == \
            KIMI_NATIVE_TOOLS._compat_command_detection_variants("r\\m -rf /")
    with mock.patch.object(output_enhance, "_native_use_native", lambda *a, **k: False), \
            mock.patch.object(output_enhance, "_NATIVE_TOOLS", None):
        assert output_enhance.interpret_exit_code("grep x f", 1) == \
            KIMI_NATIVE_TOOLS._compat_interpret_exit_code("grep x f", 1)
        assert output_enhance.is_expected_exit("diff a b", 1) == \
            KIMI_NATIVE_TOOLS._compat_is_expected_exit("diff a b", 1)
        assert output_enhance.annotate_failure("x: command not found", "x", 1) == \
            KIMI_NATIVE_TOOLS._compat_annotate_failure("x: command not found", "x", 1)


# ---------------------------------------------------------------------------
# FOCUS 1 -- RTK rewrite scanner
# ---------------------------------------------------------------------------


def test_split_shell_segments_curated():
    cases = [
        "", " ", "git status", "a; b && c || d; e", "echo 'a;b' | cat",
        'echo "a&&b" && echo c', "echo $(x; y) ; echo z", "echo `a | b`; ls",
        "a | b & c", "echo 'unterminated && ls", 'echo "unterminated && ls',
        "echo $'a;b' ; ls", "echo $(a;b) ; ls", "ls;", ";ls", "a;;b", "a&&&b",
        "a|||b", "x & y && z", "git log \\; git status",
        "echo \"$(echo 'a;b')\" ; ls", "echo `echo \\` ; x", "f() { a; }; b",
    ]
    for command in cases:
        expected = [tuple(x) for x in common._split_shell_segments(command)]
        got = [tuple(x) for x in SHELL.split_shell_segments(command)]
        assert got == expected, f"split_shell_segments({command!r})"


def test_split_shell_segments_fuzz():
    for command in _seeded_split_corpus(6000, seed=20240923):
        expected = [tuple(x) for x in common._split_shell_segments(command)]
        got = [tuple(x) for x in SHELL.split_shell_segments(command)]
        assert got == expected, f"split_shell_segments({command!r})"


@pytest.mark.parametrize("name", _KNOWN_NAMES)
def test_is_known_rtk_command(name):
    assert SHELL.is_known_rtk_command(name) == \
        common._is_known_rtk_command(name), name


def test_is_known_rtk_command_table_is_the_reference_table():
    table = common._RTK_KNOWN_COMMANDS
    assert "find" not in table  # deliberate exclusion (reference comment)
    for name in sorted(table):
        assert SHELL.is_known_rtk_command(name) is True, name
        assert SHELL.is_known_rtk_command(name.upper()) is True, name
        assert SHELL.is_known_rtk_command(name + ".exe") is True, name
        # No extra names: every ASCII word the kernel accepts is in the table.
    for probe in ("find", "echo", "cat", "rtk", "ls2", "npm2", "gitt", ""):
        assert SHELL.is_known_rtk_command(probe) is (probe.lower() in table), probe


def test_rewrite_shell_segment_curated():
    segments = [
        "git status", "echo hello", "RTK_DISABLED=1 git status",
        "FOO=1 git status", "sudo git status", "sudo time git status",
        "rtk git status", "rtk.exe status", '"git" status', "'git' status",
        "/usr/bin/git status", "./git status", "read x", "ls -la",
        "echo a | grep b", "git status | head", "| git status", "git",
        "  git status", "\tgit status", "", "   ", "|", "(", "$(git status)",
        "`git status`", "git status; ls", "unknown cmd", "RTK git",
        "git status |", "git|status",
    ]
    for segment in segments:
        for exclude_read in (False, True):
            for pwsh in (False, True):
                expected = common._rewrite_shell_segment(segment, exclude_read, pwsh)
                got = tuple(SHELL.rewrite_shell_segment(segment, exclude_read, pwsh))
                assert got == expected, (segment, exclude_read, pwsh)


def test_rewrite_shell_segment_fuzz():
    for segment in _seeded_rtk_corpus(2500, seed=77):
        for exclude_read in (False, True):
            expected = common._rewrite_shell_segment(segment, exclude_read, False)
            got = tuple(SHELL.rewrite_shell_segment(segment, exclude_read, False))
            assert got == expected, (segment, exclude_read)
        expected = common._rewrite_shell_segment(segment, False, True)
        got = tuple(SHELL.rewrite_shell_segment(segment, False, True))
        assert got == expected, segment


@pytest.mark.parametrize("command, token_kill, exclude_read, pwsh", KIMI_AGENT_RTK_CASES)
def test_maybe_rewrite_kimi_agent_cases(command, token_kill, exclude_read, pwsh):
    """The commands kimi-agent's own suite uses (documented expected strings)."""
    expected = py_maybe_rewrite(command, token_kill, exclude_read, pwsh,
                                rtk_path=RTK_BINARY)
    got = cpp_maybe_rewrite(command, token_kill, exclude_read, pwsh,
                            rtk_path=RTK_BINARY)
    assert got == expected, command


def test_maybe_rewrite_kimi_agent_documented_expectations():
    """Spot-check the literal expectations from kimi-agent's test suite."""
    doc = [
        ("git status", "rtk git status"),
        ("git status | grep x", "rtk git status | grep x"),
        ("VAR=value git status", "VAR=value rtk git status"),
        ("git status && cargo test", "git status && cargo test"),
        ("git status; cargo test", "git status; cargo test"),
        ("git status || cargo test", "git status || cargo test"),
        ("rtk git status", "rtk git status"),
        ("RTK_DISABLED=1 git status", "RTK_DISABLED=1 git status"),
        ("unknown-cmd arg", "unknown-cmd arg"),
        ('echo "git status"', 'echo "git status"'),
        ('echo "$(git status)"', 'echo "$(git status)"'),
        ("echo `git status`", "echo `git status`"),
    ]
    for command, rewritten in doc:
        assert cpp_maybe_rewrite(command, True, rtk_path=RTK_BINARY) == \
            (rewritten, rewritten != command), command
    assert cpp_maybe_rewrite("git status", True, pwsh=True,
                             rtk_path=RTK_BINARY) == ("& rtk git status", True)
    assert cpp_maybe_rewrite("git status", True, exclude_read=True,
                             rtk_path=RTK_BINARY) == ("rtk git status", True)
    assert cpp_maybe_rewrite("read var", True, exclude_read=True,
                             rtk_path=RTK_BINARY) == ("read var", False)


@pytest.mark.parametrize("command", RTK_ADVERSARIAL)
def test_maybe_rewrite_adversarial(command):
    for token_kill, exclude_read, pwsh in ((True, False, False), (True, True, False),
                                           (True, False, True), (False, False, False)):
        expected = py_maybe_rewrite(command, token_kill, exclude_read, pwsh,
                                    rtk_path=RTK_BINARY)
        got = cpp_maybe_rewrite(command, token_kill, exclude_read, pwsh,
                                rtk_path=RTK_BINARY)
        assert got == expected, (command, token_kill, exclude_read, pwsh)


@pytest.mark.skipif(sys.platform != "win32",
                    reason="Path(...).stem is WindowsPath semantics in the reference")
@pytest.mark.parametrize("command", RTK_PATH_TOKENS + ["\\\\git status",
                                                       "//git status"])
def test_maybe_rewrite_path_tokens(command):
    """Regression: bash_token_stem must reproduce ``WindowsPath(token).stem``.

    The old "text after the last separator" scan rewrote ``\\\\git`` (a UNC
    drive -> stem "") and refused ``dir/git/`` (trailing separator -> stem
    "git"), i.e. it disagreed with the reference in both directions.
    """
    expected = py_maybe_rewrite(command, True, rtk_path=RTK_BINARY)
    got = cpp_maybe_rewrite(command, True, rtk_path=RTK_BINARY)
    assert got == expected, command


def test_maybe_rewrite_gates():
    # token_kill=False short-circuits.
    assert cpp_maybe_rewrite("git status", False, rtk_path=RTK_BINARY) == \
        py_maybe_rewrite("git status", False, rtk_path=RTK_BINARY) == \
        ("git status", False)
    # rtk unavailable short-circuits (and the reference gate is consulted).
    assert cpp_maybe_rewrite("git status", True, available=False,
                             rtk_path=RTK_BINARY) == ("git status", False)
    assert py_maybe_rewrite("git status", True, available=False,
                            rtk_path=RTK_BINARY) == ("git status", False)
    # Empty / whitespace-only input.
    for command in ("", " ", "\t\n", "   "):
        assert cpp_maybe_rewrite(command, True, rtk_path=RTK_BINARY) == \
            py_maybe_rewrite(command, True, rtk_path=RTK_BINARY), repr(command)
    # rtk_path None (reference: _rtk_binary_path() is None) skips the absolute
    # fast path but still rewrites.
    assert cpp_maybe_rewrite("git status", True, rtk_path=None) == \
        py_maybe_rewrite("git status", True, rtk_path=None) == ("rtk git status", True)


def test_maybe_rewrite_absolute_rtk_path_fast_paths():
    cases = [
        f"{RTK_BINARY} git status",
        f'"{RTK_BINARY}" git status',
        f"& {RTK_BINARY} git status",
        f'& "{RTK_BINARY}" git status',
        f"  &  {RTK_BINARY} git status",
        f"{RTK_BINARY}x git status",   # verbatim prefix match in the reference
        "C:/Temp/rtkx git status",
    ]
    for command in cases:
        expected = py_maybe_rewrite(command, True, rtk_path=RTK_BINARY)
        got = cpp_maybe_rewrite(command, True, rtk_path=RTK_BINARY)
        assert got == expected, command


def test_maybe_rewrite_fuzz():
    corpus = _seeded_rtk_corpus(12000, seed=4242)
    for command in corpus:
        for token_kill, exclude_read, pwsh in ((True, False, False),
                                               (True, True, False),
                                               (True, False, True),
                                               (False, False, False)):
            expected = py_maybe_rewrite(command, token_kill, exclude_read, pwsh,
                                        rtk_path=RTK_BINARY)
            got = cpp_maybe_rewrite(command, token_kill, exclude_read, pwsh,
                                    rtk_path=RTK_BINARY)
            assert got == expected, (command, token_kill, exclude_read, pwsh)
        # The rtk_path=None profile exercises the "binary not found" gate.
        expected = py_maybe_rewrite(command, True, rtk_path=None)
        got = cpp_maybe_rewrite(command, True, rtk_path=None)
        assert got == expected, command


def test_pwsh_binding_shares_the_bash_kernel():
    """``pwsh_maybe_rewrite_with_rtk`` delegates to this tool's kernel (pwsh=True)."""
    for command in ["git status", "git status; cargo test", "rtk git status",
                    "echo 'git status'", "read x", "& rtk git status"]:
        expected = py_maybe_rewrite(command, True, False, True, rtk_path=RTK_BINARY)
        got = tuple(SHELL.pwsh_maybe_rewrite_with_rtk(command, True, True,
                                                      RTK_BINARY, False))
        assert got == expected, command


# ---------------------------------------------------------------------------
# FOCUS 3 -- output kernels (byte-exact messages)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("command, exit_code", _EXIT_CASES)
def test_interpret_exit_code_and_is_expected_exit(command, exit_code):
    assert SHELL.interpret_exit_code(command, exit_code) == \
        KIMI_NATIVE_TOOLS._compat_interpret_exit_code(command, exit_code), command
    assert SHELL.is_expected_exit(command, exit_code) == \
        KIMI_NATIVE_TOOLS._compat_is_expected_exit(command, exit_code), command


def test_interpret_exit_code_fuzz():
    rng = random.Random(2026)
    words = ["grep", "rg", "diff", "find", "test", "[", "curl", "git", "ls",
             "echo", "seq", "head", "|", "||", "&&", ";", "(", ")", "'", '"',
             "`", "$(", "-q", "x", "1", "1000", "/usr/bin/git", "FOO=1", " "]
    for _ in range(4000):
        command = "".join(rng.choice(words) for _ in range(rng.randint(1, 8)))
        for code in (0, 1, 2, 6, 7, 22, 28, 141, 127, None):
            assert SHELL.interpret_exit_code(command, code) == \
                KIMI_NATIVE_TOOLS._compat_interpret_exit_code(command, code), \
                (command, code)
            assert SHELL.is_expected_exit(command, code) == \
                KIMI_NATIVE_TOOLS._compat_is_expected_exit(command, code), \
                (command, code)


@pytest.mark.parametrize("output", _ANNOTATE_CASES)
def test_annotate_failure(output):
    assert SHELL.annotate_failure(output, "some command", 1) == \
        KIMI_NATIVE_TOOLS._compat_annotate_failure(output, "some command", 1)


def test_annotate_failure_fuzz():
    rng = random.Random(11)
    tokens = ["bash:", "foo:", "command", "not", "found", "cat:", "nope:",
              "No", "such", "file", "directory", "Traceback", "(most", "recent",
              "call", "last):", "ModuleNotFoundError:", "module", "named",
              "'x'", "Permission", "denied", "mkdir:", "cannot", "create",
              "Error:", "fatal:", "sh:", "1:", "ENOENT", "ImportError", "\n",
              " ", "timeout", "connection refused", "unhandled", "x"]
    for _ in range(3000):
        output = "".join(rng.choice(tokens) for _ in range(rng.randint(1, 14)))
        assert SHELL.annotate_failure(output, "cmd", rng.choice([0, 1, 2, None])) == \
            KIMI_NATIVE_TOOLS._compat_annotate_failure(output, "cmd", 1), output


def test_find_error_line_index_and_truncate_lines():
    corpus = _seeded_output_corpus(400, seed=7)
    for output in corpus:
        assert SHELL.find_error_line_index(output) == \
            common._find_error_line_index(output), output
        for max_lines in (0, 1, 2, 3, 4, 5, 10):
            for preserve_errors in (True, False):
                for context in (0, 2):
                    assert SHELL.truncate_lines(output, max_lines, preserve_errors,
                                                context) == \
                        common._truncate_lines(output, max_lines,
                                               preserve_errors=preserve_errors,
                                               error_context_lines=context), \
                        (output, max_lines, preserve_errors, context)


def test_truncate_lines_error_preservation_messages():
    """The fold marker + preserved-context note are byte-exact."""
    lines = [f"step_{i} ok" for i in range(500)]
    lines.insert(250, "error: stage 2 failed")
    output = "\n".join(lines)
    for max_lines in (3, 10, 50):
        assert SHELL.truncate_lines(output, max_lines) == \
            common._truncate_lines(output, max_lines)
    assert SHELL.truncate_lines("l1\rl2\rl3\rl4\rl5\rl6", 3) == \
        common._truncate_lines("l1\rl2\rl3\rl4\rl5\rl6", 3)


# ---------------------------------------------------------------------------
# FOCUS 4 -- safety kernels
# ---------------------------------------------------------------------------


def _load_kimi_agent_corpora() -> dict:
    """Corpora from kimi-agent's own ``tests/native/test_shell_security_equivalence.py``.

    Read with ``ast`` so they stay in sync with the checkout instead of being
    transcribed here.
    """
    import ast

    path = KIMI_AGENT_ROOT / "tests" / "native" / "test_shell_security_equivalence.py"
    if not path.is_file():  # pragma: no cover - defensive
        return {}
    tree = ast.parse(path.read_text(encoding="utf-8"))
    ns: dict = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign) or not isinstance(node.targets[0], ast.Name):
            continue
        name = node.targets[0].id
        if not name.endswith("_CORPUS"):
            continue
        try:
            # The corpora are literal expressions (some concatenate long
            # strings); evaluate them without builtins.
            module = ast.Module(body=[node], type_ignores=[])
            exec(compile(module, str(path), "exec"), {"__builtins__": {}}, ns)
        except Exception:  # pragma: no cover - defensive
            continue
    return {k: v for k, v in ns.items() if k.endswith("_CORPUS")}


KIMI_AGENT_CORPORA = _load_kimi_agent_corpora()
_AGENT_HARDLINE = KIMI_AGENT_CORPORA.get("HARDLINE_CORPUS", [])
_AGENT_GUIDANCE = KIMI_AGENT_CORPORA.get("GUIDANCE_CORPUS", [])
_AGENT_EXIT = KIMI_AGENT_CORPORA.get("EXIT_CODE_CORPUS", [])
_AGENT_ANNOTATE = KIMI_AGENT_CORPORA.get("ANNOTATE_CORPUS", [])


@pytest.mark.parametrize("command", RTK_ADVERSARIAL + _ANNOTATE_CASES)
def test_command_detection_variants(command):
    assert list(SHELL.command_detection_variants(command)) == \
        KIMI_NATIVE_TOOLS._compat_command_detection_variants(command), command


def test_command_detection_variants_fuzz():
    for command in _seeded_foreground_corpus(6000, seed=99):
        assert list(SHELL.command_detection_variants(command)) == \
            KIMI_NATIVE_TOOLS._compat_command_detection_variants(command), command


_HARDLINE_CASES = [
    # 1. recursive delete of root / home / drive root
    "rm -rf /", "rm -rf --no-preserve-root /", "rm -rf /*", "sudo rm -rf /",
    "rm -rf ~", "rm -rf .", "rm -rf ..", "rm -rf $HOME", "rm -rf ${HOME}",
    "rm -rf '~'", "rm -rf '*'", "rm -rf '/*'", "rm -r -f /", "rm -fr /",
    "rm -Rf /", "RM -RF /", "rm  -rf   /", "rm --recursive --force /",
    "rmdir /s /q C:\\", "rmdir /s C:\\", "del /f /s /q C:\\", "del C:\\*",
    "rm -rf C:\\", "rm -rf c:/", "rm -rf //", "rm -rf /./", "rm -rf /../",
    "rm -rf c:*", "rm -rf c:/*", "rm -rf c:**", "rm -rf c:*/", "rm -rf c://",
    "rm -rf /tmp", "rm -rf build/", "rm -f x", "rm x", "rm -rf ./build",
    "echo rm -rf /", "echo 'rm -rf /'", 'echo "rm -rf /"',
    "sh -c 'rm -rf /'", "sh -c \"rm -rf /\"", "sh -c rm -rf /",
    "./rm -rf /", "/bin/rm -rf /", "/usr/bin/rm -rf /", "'/bin/rm' -rf /",
    "sudo/bin/rm -rf /", "c:\\windows\\system32\\rm.exe -rf /",
    "rm.exe -rf /", "(rm -rf /)", "$(rm -rf /)", "`rm -rf /`",
    "foo(rm -rf /)", "srm -rf /", "xrm -rf /", "\\rm -rf /",
    "rm -f & x /", "rm -rf / & echo x", "x; rm -rf /", "x;rm -rf /",
    "rm -rf /; echo x", "cd / &&rm -rf /", "if rm -rf /; then :; fi",
    # 2. mkfs
    "mkfs.ext4 /dev/sda", "mkfs /dev/sda", "mkfs.ext4x /dev/sda",
    "a.mkfs.ext4 x", "amkfs x", "echo mkfs",
    # 3. dd to a raw device
    "dd if=/dev/zero of=/dev/sda", "dd if=x.img of=/dev/sda1",
    "dd of=/dev/nvme0n1 if=x", "dd of=/dev/disk2", "dd of=/dev/rdisk1",
    "dd if=x of=/dev/hda", "dd of=/dev/nv1", "dd of=/dev/rd0",
    "xof=/dev/sda dd", "dd of=/dev/sdaX", "dd of=/dev/x", "dd of=/dev/diskx",
    "dd if=x of=/tmp/x", "echo dd", "dd if=/dev/zero of=/dev/sda; echo x",
    # 4. power commands
    "shutdown -h now", "reboot", "init 0", "halt", "poweroff",
    "sudo shutdown -h now", " echo reboot", "echo shutdown",
    # 5. fork bomb
    ":(){ :|:& };:", ":(){:|:&};:", ":(){ :|: x :&", "echo ':(){ :|:& };:'",
    # 6. kill PID 1 / $PPID
    "kill -9 1", "kill 1", "kill $PPID", "/bin/kill 1", "./kill 1",
    "'/bin/kill' 1", "kill -9 2", "kill $pid", "echo kill 1",
    # 7. Windows format
    "format C:", "format c:/", "./format C:", "format.exe C:",
    "format C:\\ /q", "format D:", "echo format C:",
    # benign
    "ls -la", "echo hi", "git status", "rm -rf *.o", "kill -9 12345",
]


@pytest.mark.parametrize("command", _HARDLINE_CASES)
def test_check_hardline_blocked(command):
    assert tuple(SHELL.check_hardline_blocked(command)) == \
        KIMI_NATIVE_TOOLS._compat_check_hardline_blocked(command), command


def test_check_hardline_blocked_fuzz():
    for command in _seeded_hardline_corpus(20000, seed=99):
        expected = KIMI_NATIVE_TOOLS._compat_check_hardline_blocked(command)
        got = tuple(SHELL.check_hardline_blocked(command))
        assert got == expected, command


def test_hardline_description_embeds_the_operand_token():
    """Regression: the description quotes the *raw* operand token.

    ``echo 'rm -rf /'`` matched the reference in variant 0 with the operand
    ``/'`` (the reference scans with ``\\b`` word boundaries, so the command word
    is found after the quote); the token-based scan missed it and fell through to
    the deobfuscated variant, printing ``(`/`)`` instead of ``(`/'`)``.
    """
    assert tuple(SHELL.check_hardline_blocked("echo 'rm -rf /'")) == \
        (True, "Recursive delete of protected root/home (`/'`)")
    assert tuple(SHELL.check_hardline_blocked('echo "rm -rf /"')) == \
        (True, 'Recursive delete of protected root/home (`/"`)')
    assert tuple(SHELL.check_hardline_blocked("sh -c 'rm -rf /'")) == \
        (True, "Recursive delete of protected root/home (`/'`)")


@pytest.mark.parametrize("command", _HARDLINE_CASES)
def test_foreground_background_guidance_curated(command):
    assert SHELL.foreground_background_guidance(command) == \
        KIMI_NATIVE_TOOLS._compat_foreground_background_guidance(command), command


_FOREGROUND_CASES = [
    # matching patterns
    "npm run dev", "pnpm run start", "yarn run serve", "bun run watch",
    "npm run dev &", "next dev", "vite", "nodemon x", "uvicorn app:app",
    "gunicorn app", "python -m http.server", "docker compose up",
    "docker compose up -d", "docker-compose up", "nohup x", "setsid x",
    "ls &", "x &", "vite;", "(vite)", "vite.dev", "./node_modules/.bin/vite",
    "cd x && vite", "echo vite", "VITE=1 vite",
    # non-matching
    "yarn dev", "npm start", "pnpm start", "bun serve", "npm test",
    "npm run build", "next build", "echo 'npm run dev'", "echo \"vite\"",
    "ls -la", "xvite", "vitex", "VITE", "xvite.", "npm", "run dev",
    "nohupx", "settid", "docker compose down", "docker-compose down",
    "python -m http.serverx", "python -m http/x", "dockerx compose up",
    "&", " &: ", "echo &", "", " ", "\t\n",
]


@pytest.mark.parametrize("command", _FOREGROUND_CASES)
def test_foreground_background_guidance(command):
    assert SHELL.foreground_background_guidance(command) == \
        KIMI_NATIVE_TOOLS._compat_foreground_background_guidance(command), command


def test_foreground_guidance_long_running_patterns():
    """Regression: the reference patterns all require ``run`` for JS runners.

    The old token-scan treated ``run`` as optional (so ``yarn dev``/``npm start``
    produced a bogus long-running hint) and compared whole whitespace tokens (so
    ``vite.dev`` / ``./node_modules/.bin/vite`` were missed).
    """
    assert SHELL.foreground_background_guidance("yarn dev") is None
    assert SHELL.foreground_background_guidance("npm start") is None
    assert SHELL.foreground_background_guidance("pnpm start") is None
    assert SHELL.foreground_background_guidance("npm run dev") == _FG_HINT
    assert SHELL.foreground_background_guidance("vite.dev") == _FG_HINT
    assert SHELL.foreground_background_guidance("./node_modules/.bin/vite") == _FG_HINT
    assert SHELL.foreground_background_guidance("xvite") is None
    assert SHELL.foreground_background_guidance("VITE") is None


def test_foreground_background_guidance_fuzz():
    for command in _seeded_foreground_corpus(20000, seed=31337):
        expected = KIMI_NATIVE_TOOLS._compat_foreground_background_guidance(command)
        got = SHELL.foreground_background_guidance(command)
        assert got == expected, command


@pytest.mark.parametrize("command", [
    "rm -f & x /",           # lone & is not a token separator in the reference
    "rm -r & /", "del /f & C:\\",
])
def test_hardline_single_ampersand_is_not_a_separator(command):
    assert tuple(SHELL.check_hardline_blocked(command)) == \
        KIMI_NATIVE_TOOLS._compat_check_hardline_blocked(command), command


@pytest.mark.parametrize(
    "command", [c for c in _AGENT_HARDLINE if str(c).isascii()] or [""])
def test_kimi_agent_hardline_corpus(command):
    """kimi-agent's own security-equivalence corpus (ASCII subset)."""
    assert tuple(SHELL.check_hardline_blocked(command)) == \
        KIMI_NATIVE_TOOLS._compat_check_hardline_blocked(command), command


@pytest.mark.parametrize(
    "command", [c for c in _AGENT_GUIDANCE if str(c).isascii()] or [""])
def test_kimi_agent_guidance_corpus(command):
    assert SHELL.foreground_background_guidance(command) == \
        KIMI_NATIVE_TOOLS._compat_foreground_background_guidance(command), command


@pytest.mark.parametrize(
    "command, exit_code",
    [pair for pair in _AGENT_EXIT if str(pair[0]).isascii()] or [("", 1)])
def test_kimi_agent_exit_code_corpus(command, exit_code):
    assert SHELL.interpret_exit_code(command, exit_code) == \
        KIMI_NATIVE_TOOLS._compat_interpret_exit_code(command, exit_code)
    assert SHELL.is_expected_exit(command, exit_code) == \
        KIMI_NATIVE_TOOLS._compat_is_expected_exit(command, exit_code)


@pytest.mark.parametrize(
    "output, command, exit_code",
    [t for t in _AGENT_ANNOTATE if str(t[0]).isascii()] or [("", "x", 1)])
def test_kimi_agent_annotate_corpus(output, command, exit_code):
    assert SHELL.annotate_failure(output, command, exit_code) == \
        KIMI_NATIVE_TOOLS._compat_annotate_failure(output, command, exit_code)


@pytest.mark.parametrize("command, blocked", [
    # /dev/sda is an operand, not a "/s"-style switch: no r|s flag -> no block.
    ("rmdir /dev/sda /", False),
    ("del /usr/local /", False),
    # drive-root regex: one optional separator and at most one trailing '*'
    ("rm -rf c:*", True),
    ("rm -rf c:/*", True),
    ("rm -rf c:**", False),
    ("rm -rf c:*/", False),
    ("rm -rf c://", False),
    # fork bomb needs the literal ":|:&"
    (":(){ :|:& };:", True),
    (":(){ :|: x :&", False),
    # dd device alternatives are exactly sd|nvme|disk|rdisk, with a \b on "of="
    ("dd if=x of=/dev/sda", True),
    ("dd if=x of=/dev/nvme0n1", True),
    ("dd if=x of=/dev/disk2", True),
    ("dd if=x of=/dev/rdisk1", True),
    ("dd if=x of=/dev/hda", False),
    ("dd if=x of=/dev/nv1", False),
    ("dd if=x of=/dev/rd0", False),
    ("dd xof=/dev/sda", False),
])
def test_hardline_rule_regressions(command, blocked):
    """Regression vectors for the four rewritten hardline rules."""
    assert tuple(SHELL.check_hardline_blocked(command)) == \
        KIMI_NATIVE_TOOLS._compat_check_hardline_blocked(command), command
    assert tuple(SHELL.check_hardline_blocked(command))[0] is blocked, command


@pytest.mark.parametrize("command", [
    "./rm -rf /", "/bin/rm -rf /", "/usr/bin/rm -rf /", "'/bin/rm' -rf /",
    "sudo/bin/rm -rf /", "c:\\windows\\system32\\rm.exe -rf /",
    "./format C:", "format.exe C:", "/bin/kill 1", "./kill 1", "'/bin/kill' 1",
])
def test_hardline_command_word_boundaries(command):
    """Regression: the command word is found after any non-word character.

    A token-based scan only looked at whitespace-separated words, so a path
    prefix (``/bin/rm``) or a quote (``'/bin/rm'``) hid the command word and the
    reference's block was not reproduced -- a hardline-floor bypass.
    """
    expected = KIMI_NATIVE_TOOLS._compat_check_hardline_blocked(command)
    got = tuple(SHELL.check_hardline_blocked(command))
    assert got == expected, command
    assert got[0] is True, command


# ---------------------------------------------------------------------------
# documented ASCII gate
# ---------------------------------------------------------------------------


def test_ascii_gate_is_documented():
    """Non-ASCII input is out of contract for these kernels (ASCII gate).

    The reference's callers gate with ``str.isascii()`` before using the native
    kernels (``safety.py``: ``_native_use_native("TOOLS") and command.isascii()``),
    so an ungated non-ASCII call may differ.  This test *pins* the differences
    instead of hiding them:

    * ``find_error_line_index`` uses ASCII ``\\b`` word boundaries while Python's
      ``re`` uses Unicode boundaries -- ``"اnot foundا"`` (Arabic letter alef)
      matches natively but not in the reference.
    * the safety kernels short-circuit to "not blocked" for non-ASCII, so
      kimi-agent's own ``"vite \\u00e9"`` guidance vector differs.
    * ``_read_shell_word``/``lstrip()`` treat Unicode whitespace (``\\xa0``) as
      space in Python but not in the ASCII-only scanner.
    """
    command = "اnot foundا"
    assert common._find_error_line_index(command) is None      # Unicode \b
    assert SHELL.find_error_line_index(command) == 1           # ASCII \b
    assert SHELL.check_hardline_blocked("rm -rf /\u00a0") == (False, None)
    assert SHELL.foreground_background_guidance("npm run dev\u00a0") is None
    # kimi-agent's own non-ASCII guidance vector ("vite \u00e9").
    non_ascii_guidance = [c for c in _AGENT_GUIDANCE if not str(c).isascii()]
    for item in non_ascii_guidance or ["vite \u00e9"]:
        assert SHELL.foreground_background_guidance(item) is None
    # Non-breaking space is whitespace to Python, data to the ASCII scanner.
    assert py_maybe_rewrite("\u00a0git status", True, rtk_path=RTK_BINARY) == \
        ("\u00a0rtk git status", True)
    assert cpp_maybe_rewrite("\u00a0git status", True, rtk_path=RTK_BINARY) == \
        ("\u00a0git status", False)
    # ASCII input is exact, including the same characters via escapes.
    assert SHELL.find_error_line_index("not found") == \
        common._find_error_line_index("not found") == 1
