-- Kimix library
target("kimix-core")
    set_kind("static")
    add_files("core/*.cpp")
    add_files("core/stl/*.cpp")       -- NEW: stl implementations
    add_headerfiles("core/*.h")
    add_headerfiles("core/stl/*.h")   -- NEW: stl headers
    add_headerfiles("core/stl/*.inl") -- if any .inl files
    add_includedirs(".", {public = true})
    -- Dependency rule: all third-party deps are declared HERE (on kimix-core)
    -- only; every other target depends on kimix-core and never on a third-party
    -- target directly. mimalloc's static.c.obj is archived into this lib and its
    -- mi_* symbols are exported again by runtime_py.pyd (shared heap); native
    -- tests import them from the pyd instead of pulling static.c.obj, because
    -- kimix-core API like hash64 is ALSO re-exported by the pyd.
    add_deps("mimalloc", "kimix-xxhash", "kimix-yyjson", "kimix-pybind11")
    kimix_set_pcxxheader("core/pch.h")
    _config_project({batch_size = 8, project_kind = "static"})
    on_load(function(target)
        -- ================================================================
        -- Version header: generated from the single config file
        -- (version.txt in the project root). No C++ source hard-codes the
        -- version; bumping the version means editing version.txt only.
        -- ================================================================
        local text = io.readfile(path.join(os.projectdir(), "version.txt"))
        local version = text and text:gsub("^%s*(.-)%s*$", "%1") or "0.0.0"
        local bd = get_config("buildir")
        if bd == nil or bd == "" then
            bd = "build"
        end
        local gen_dir = path.join(os.projectdir(), bd, "gen")
        os.mkdir(gen_dir)
        io.writefile(
            path.join(gen_dir, "kimix_version.h"),
            "#pragma once\n"
            .. "// GENERATED by xmake from version.txt - DO NOT EDIT.\n"
            .. string.format("#define KIMIX_CORE_VERSION \"%s\"\n", version)
            .. string.format("#define KIMIX_RUNTIME_VERSION \"%s\"\n", version))
        target:add("includedirs", gen_dir, {public = true})
        -- kimix-core is compiled as an exported library: when linked into
        -- runtime_py.pyd its KIMIX_CORE_API symbols (e.g. hash64) are exported,
        -- so native test executables resolve them as pyd imports instead of
        -- pulling kimix-core unity members (which would drag mimalloc's
        -- static.c.obj into the link and collide with the mi_* imports).
        -- Consumers define KIMIX_CORE_STATIC themselves (kimix-test, test_proj,
        -- runtime_py) to keep plain references and link the static copy.
        target:add("defines", "KIMIX_CORE_EXPORT_DLL")
        if has_config('kimix_disable_win_message_box') and target:is_plat('windows') then
            target:add('defines', 'KIMIX_DISABLE_WIN_MESSAGE_BOX', {public = true})
        end
        if target:is_plat("windows") then
            target:add("defines", "NOMINMAX", "_CRT_SECURE_NO_WARNINGS", {public = true})
            target:add("defines", "KIMIX_PLATFORM_WINDOWS", {public = true})  -- NEW
            if is_mode("debug") then
                target:add("syslinks", "Dbghelp")  -- for backtrace
            end
        elseif target:is_plat("linux") then
            target:add("defines", "KIMIX_PLATFORM_UNIX", {public = true})
            target:add("syslinks", "dl", "pthread")
        elseif target:is_plat("macosx") then
            target:add("defines", "KIMIX_PLATFORM_UNIX", "KIMIX_PLATFORM_APPLE", {public = true})
        end
    end)
target_end()

-- Kimix test executable
target("kimix-test")
    set_kind("binary")
    add_files("test/main.cpp")
    add_deps("kimix-core")
    add_defines("KIMIX_CORE_STATIC")
    _config_project({batch_size = 8})

    add_tests("basic", {
        runargs = {},
        group = "unit",
    })
target_end()

-- OpenAI-compatible chat completion streaming demo (uses cpp-httplib).
-- Run with: xmake run openai_chat_demo [config.json]
target("openai_chat_demo")
    set_kind("binary")
    add_files("openai/*.cpp")
    add_includedirs(".", {public = true})
    add_deps("kimix-core", "kimix-cpp-httplib")
    add_defines("KIMIX_CORE_STATIC")
    _config_project({batch_size = 8})
target_end()

-- OpenAI Responses API streaming demo (cpp-httplib + Mbed TLS; HTTPS is
-- provided by the vendored kimix-mbedtls target).
-- Run with: xmake run openai_responses_demo <config.json>  (config path required)
target("openai_responses_demo")
    set_kind("binary")
    add_files("openai_responses/*.cpp")
    add_includedirs(".", {public = true})
    add_deps("kimix-core", "kimix-cpp-httplib", "kimix-mbedtls")
    add_defines("KIMIX_CORE_STATIC", "CPPHTTPLIB_MBEDTLS_SUPPORT")
    _config_project({batch_size = 8})
target_end()

-- Anthropic Messages API streaming demo (cpp-httplib + Mbed TLS; HTTPS is
-- provided by the vendored kimix-mbedtls target).
-- Run with: xmake run anthropic_chat_demo [config.json]
target("anthropic_chat_demo")
    set_kind("binary")
    add_files("anthropic/*.cpp")
    add_includedirs(".", {public = true})
    add_deps("kimix-core", "kimix-cpp-httplib", "kimix-mbedtls")
    add_defines("KIMIX_CORE_STATIC", "CPPHTTPLIB_MBEDTLS_SUPPORT")
    _config_project({batch_size = 8})
target_end()

-- Include extensions
includes("ext")




-- ============================================================================
-- Kimix Runtime Python module (runtime_py.pyd)
--
-- Merged target: all runtime kernels (runtime/**.cpp) plus the pybind11
-- binding layer (runtime/py/**.cpp) are compiled into a single Python
-- extension module. Native C++ tests link against this module as a shared
-- library; the runtime symbols are exported via KIMIX_RUNTIME_API.
-- ============================================================================
target("runtime_py")
    set_kind("shared")
    set_extension(".pyd")
    if is_plat("linux") then
        -- publish.py packages bin/release/runtime_py.pyd; on Linux xmake would
        -- otherwise prepend 'lib' to the shared-library filename.
        set_prefixname("")
    end
    add_rules("kimix_basic_settings")      -- RTTI-off etc., but NO unity build
    add_files("runtime/**.cpp")
    add_headerfiles("runtime/**/*.h")
    add_includedirs("..", {public = true}) -- expose src/ so <runtime/runtime.h> works
    add_deps("kimix-core")
    on_load(function(target)
        -- Export runtime symbols from this module; consumers see dllimport.
        target:add("defines", "KIMIX_RUNTIME_EXPORT_DLL")
        target:add("defines", "KIMIX_CORE_STATIC", {public = true})

        -- Python interpreter discovery.  Windows keeps the original direct
        -- call (python is on PATH).  On Linux the bare name "python" usually
        -- does not exist (only python3) and os.iorunv RAISES when the program
        -- is missing, so resolve the interpreter path through the shell first.
        local function py_conf(var)
            local exe = "python"
            if not is_plat("windows") then
                local probe = os.iorunv("sh", {"-c", "command -v python3 2>/dev/null || command -v python 2>/dev/null"})
                if not probe then
                    return nil
                end
                exe = probe:gsub("%s+$", ""):gsub("^%s+", "")
                if exe == "" then
                    return nil
                end
            end
            local out = os.iorunv(exe, {"-c", "import sysconfig; print(sysconfig." .. var .. ")"})
            if out then
                out = out:gsub("%s+$", "")
                if out ~= "" then return out end
            end
            return nil
        end
        local inc = py_conf("get_paths()['include']")
        if inc and os.isdir(inc) then
            target:add("includedirs", inc)
        end
        local libdir = py_conf("get_config_var('LIBDIR')")
        if libdir and os.isdir(libdir) then
            target:add("linkdirs", libdir)
            if is_plat("windows") then
                target:add("links", "python314")
            else
                -- Linux: link the interpreter's real shared library
                -- (libpython3.10.so -> "python3.10").
                local ldlib = py_conf("get_config_var('LDLIBRARY')")
                local linkname = ldlib and ldlib:gsub("^lib", ""):gsub("%.so$", "")
                if linkname and linkname ~= "" then
                    target:add("links", linkname)
                end
            end
        end
    end)
    after_link(function(target)
        -- Linux: the test executables link this module with -lruntime_py;
        -- provide libruntime_py.so pointing at the actual module file so the
        -- linker can resolve it (the module itself keeps the .pyd extension).
        if target:is_plat("linux") then
            local so = path.join(target:targetdir(), "libruntime_py.so")
            -- remove any pre-existing link (incl. stale/broken symlinks)
            os.rm(so)
            -- same-dir relative link: libruntime_py.so -> <module filename>
            os.ln(target:filename(), so)
            -- CPython on Linux only imports extension modules named *.so, so
            -- publish a real copy under the importable name next to the
            -- module (the module file itself keeps the .pyd extension).
              local imp = path.join(target:targetdir(), "runtime_py.so")
              os.rm(imp)
              os.cp(target:targetfile(), imp)
          end
      end)
  target_end()

target_end()
